function vars = local_summary_metric_vars(T)
vars = { ...
    'badframe_fraction', ...
    'prediction_issue_fraction', ...
    'interpolated_prediction_issue_fraction', ...
    'repaired_prediction_issue_fraction', ...
    'unresolved_prediction_issue_fraction', ...
    'prediction_issue_repair_rate', ...
    'prediction_issue_unresolved_rate'};
vars = vars(ismember(vars, T.Properties.VariableNames));
end