function figureManifest = local_make_figures(T, animalTable, ~, pointSummary, styles, cfg, figDir)
rows = struct([]);
rows = local_add_figure_row(rows, local_plot_story_overview(T, styles, cfg, figDir), ...
    'Overall preprocessing story: prediction flags, repair, unresolved burden, and final bad frames.');
rows = local_add_figure_row(rows, local_plot_point_burden(pointSummary, cfg, figDir), ...
    'Point-level QC burden across SLEAP body points.');
rows = local_add_figure_row(rows, local_plot_animal_repair(animalTable, styles, cfg, figDir), ...
    'Animal-level prediction-issue repair rates by non-pooled analysis group.');
rows = local_add_figure_row(rows, local_plot_session_rank(T, styles, cfg, figDir), ...
    'Dyadic/session-level QC ranking with stable condition colors.');
rows = local_add_figure_row(rows, local_plot_condition_arena_summary(T, styles, cfg, figDir), ...
    'Condition-by-arena QC summary without pooling arenas.');
rows = local_add_figure_row(rows, local_plot_color_key(styles, cfg, figDir), ...
    'Stable experimental-group color key used by paper pipeline figures.');
figureManifest = struct2table(rows);
end