function vars = local_preprocess_audit_vars()
vars = [ ...
    "n_prediction_issue_animal_frames"; ...
    "n_interpolated_prediction_issue_animal_frames"; ...
    "n_usable_prediction_issue_animal_frames"; ...
    "n_repaired_prediction_issue_animal_frames"; ...
    "n_unresolved_prediction_issue_animal_frames"; ...
    "prediction_issue_fraction"; ...
    "interpolated_prediction_issue_fraction"; ...
    "usable_prediction_issue_fraction"; ...
    "repaired_prediction_issue_fraction"; ...
    "unresolved_prediction_issue_fraction"; ...
    "prediction_issue_usable_rate"; ...
    "prediction_issue_repair_rate"; ...
    "prediction_issue_unresolved_rate"; ...
    "n_prediction_issue_frames_any_animal"; ...
    "n_repaired_prediction_issue_frames_any_animal"; ...
    "n_unresolved_prediction_issue_frames_any_animal"; ...
    "prediction_issue_any_animal_fraction"; ...
    "repaired_prediction_issue_any_animal_fraction"; ...
    "unresolved_prediction_issue_any_animal_fraction"];
end