function tests = test_10_scale_usefulness_basic()
%TEST_SCALE_USEFULNESS_BASIC Basic tests for scale-usefulness scoring.
tests = functiontests(localfunctions);
end

function testScoreLayerRuns(testCase)
dyad = i_make_mock_dyad(1200, 80);
ChunkSet = build_multiscale_chunk_dataset({dyad}, ...
    'useLogScaleBank', true, ...
    'minScaleSec', 0.2, ...
    'maxScaleSec', 4.0, ...
    'nScales', 12, ...
    'strideSec', 0.1, ...
    'anchorMode', 'center', ...
    'minValidFrac', 0.90);

ScaleScore = score_multiscale_chunk_bank(ChunkSet, ...
    'nPCs', 4, ...
    'nClusters', 5, ...
    'maxChunksPerScale', 1200, ...
    'verbose', false);

verifyTrue(testCase, isfield(ScaleScore, 'scaleTable'));
verifyEqual(testCase, height(ScaleScore.scaleTable), 12);
verifyTrue(testCase, height(ScaleScore.selectedTable) >= 3);
verifyTrue(testCase, isfield(ScaleScore, 'embeddingDimensionAudit'));
verifyEqual(testCase, height(ScaleScore.embeddingDimensionAudit), 12);
verifyTrue(testCase, all(ScaleScore.scaleTable.representation_mode == "multiresolution"));
verifyTrue(testCase, all(ScaleScore.scaleTable.representation_dims > 0));
verifyTrue(testCase, any(ScaleScore.scaleTable.representation_dims < ScaleScore.scaleTable.raw_flattened_dims));
end

function testValidateLayerRuns(testCase)
dyad = i_make_mock_dyad(1000, 80);
ChunkSet = build_multiscale_chunk_dataset({dyad}, ...
    'useLogScaleBank', true, ...
    'minScaleSec', 0.2, ...
    'maxScaleSec', 3.0, ...
    'nScales', 10, ...
    'strideSec', 0.1, ...
    'anchorMode', 'center', ...
    'minValidFrac', 0.90);

ScaleScore = score_multiscale_chunk_bank(ChunkSet, ...
    'nPCs', 4, ...
    'nClusters', 4, ...
    'maxChunksPerScale', 1000, ...
    'verbose', false);

Report = validate_scale_usefulness_scores(ScaleScore, 'makePlots', false, 'verbose', false);
verifyTrue(testCase, Report.isValid);

Stability = estimate_scale_selection_stability(ScaleScore, ...
    'nBootstraps', 3, ...
    'nMicro', 2, ...
    'nMotif', 2, ...
    'nContext', 2, ...
    'minLogGap', 0.05, ...
    'rngSeed', 77);
verifyEqual(testCase, height(Stability), height(ScaleScore.scaleTable));
verifyTrue(testCase, all(Stability.labels_used_for_stability == "none"));
verifyTrue(testCase, all(Stability.selection_frequency >= 0 & Stability.selection_frequency <= 1));

LoadingStability = estimate_pca_loading_stability(ScaleScore, ...
    'nSplits', 2, ...
    'nPCs', 3, ...
    'rngSeed', 81);
verifyEqual(testCase, height(LoadingStability), height(ScaleScore.scaleTable));
verifyTrue(testCase, all(LoadingStability.labels_used_for_loading_stability == "none"));
verifyTrue(testCase, all(LoadingStability.median_subspace_similarity >= 0 | isnan(LoadingStability.median_subspace_similarity)));

ArenaAudit = audit_arena_embedding_sensitivity(ScaleScore, dyad.featureMeta, ...
    'nEmbeddingPCs', 2, ...
    'topNFeatures', 3);
verifyEqual(testCase, height(ArenaAudit), height(ScaleScore.scaleTable));
verifyTrue(testCase, all(ArenaAudit.audit_only_not_selection));
verifyTrue(testCase, all(ArenaAudit.condition_used_for_embedding_fit == 0));
end

function dyad = i_make_mock_dyad(T, fps)
[featureNames, featureMeta] = default_dyad_feature_metadata();
time_s = (0:T-1)' ./ fps;
X = zeros(T, numel(featureNames));
for f = 1:numel(featureNames)
    if featureMeta.IsBoolean(f)
        x = double(rand(T,1) > 0.7);
    elseif featureMeta.IsCircular(f)
        x = mod(cumsum(randn(T,1) * 5), 360) - 180;
    elseif string(featureMeta.TransformHint{f}) == "log1p"
        x = abs(40 + cumsum(randn(T,1) * 0.5));
    else
        x = cumsum(randn(T,1) * 0.15);
    end
    X(:,f) = x;
end
raw = struct();
for f = 1:numel(featureNames)
    raw.(featureNames{f}) = X(:,f);
end
frameMask = true(T,1);
frameMask(randperm(T, round(0.03*T))) = false;
dyad = struct('time_s', time_s, 'fps', fps, 'X', X, ...
    'featureNames', {featureNames}, 'featureMeta', featureMeta, ...
    'raw', raw, 'frameMask', frameMask);
end
