function params = load_multiscale_chunking_config(configPath)
%LOAD_MULTISCALE_CHUNKING_CONFIG Load run-06 chunking parameters.
%
% Defaults live in config/multiscale_chunking_config.csv. Environment
% variables listed in the env_override column may override values for a run.

if nargin < 1 || strlength(string(configPath)) == 0
    repoRoot = fileparts(fileparts(mfilename('fullpath')));
    configPath = fullfile(repoRoot, 'config', 'multiscale_chunking_config.csv');
end

importOpts = detectImportOptions(configPath, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
importOpts.DataLines = [2 Inf];
importOpts.VariableNamesLine = 1;
importOpts.VariableUnitsLine = 0;
importOpts = setvartype(importOpts, importOpts.VariableNames, 'string');
T = readtable(configPath, importOpts);

required = ["parameter", "value", "type", "env_override", "description"];
missing = setdiff(required, string(T.Properties.VariableNames));
assert(isempty(missing), 'load_multiscale_chunking_config:MissingColumn', ...
    'Config %s is missing required columns: %s', configPath, strjoin(missing, ', '));
assert(height(T) >= 1, 'load_multiscale_chunking_config:EmptyConfig', ...
    'Config %s must contain at least one parameter row.', configPath);

params = struct();
effectiveValue = strings(height(T), 1);
envOverrideUsed = false(height(T), 1);
for i = 1:height(T)
    name = matlab.lang.makeValidName(T.parameter(i));
    rawValue = string(T.value(i));
    envName = strtrim(string(T.env_override(i)));
    if ismissing(envName)
        envName = "";
    end
    if envName ~= ""
        envValue = strtrim(string(getenv(envName)));
        if envValue ~= ""
            rawValue = envValue;
            envOverrideUsed(i) = true;
        end
    end
    params.(name) = local_parse_value(rawValue, lower(strtrim(string(T.type(i)))), T.parameter(i));
    effectiveValue(i) = local_value_to_string(params.(name));
end

T.env_override_used = envOverrideUsed;
[params, T] = local_apply_mode_defaults(params, T);
T.effective_value = effectiveValue;
T = local_refresh_effective_values(T, params);
T.config_path = repmat(string(configPath), height(T), 1);
params.config_path = string(configPath);
params.config_table = T;

local_validate_params(params);
end

function [params, T] = local_apply_mode_defaults(params, T)
canonicalSmokeOutput = "derived/chunks_motif_discovery_smoke";
canonicalFullOutput = "derived/chunks_motif_discovery";

outputExplicit = local_env_override_used(T, "output_dir");

if params.run_mode == "full"
    if ~outputExplicit && any(params.output_dir == [canonicalSmokeOutput, canonicalFullOutput])
        params.output_dir = canonicalFullOutput;
    end
else
    if ~outputExplicit && any(params.output_dir == [canonicalSmokeOutput, canonicalFullOutput])
        params.output_dir = canonicalSmokeOutput;
    end
end
end

function tf = local_env_override_used(T, parameterName)
idx = string(T.parameter) == string(parameterName);
tf = any(T.env_override_used(idx));
end

function T = local_refresh_effective_values(T, params)
effectiveValue = strings(height(T), 1);
for i = 1:height(T)
    name = matlab.lang.makeValidName(T.parameter(i));
    if isfield(params, name)
        effectiveValue(i) = local_value_to_string(params.(name));
    end
end
T.effective_value = effectiveValue;
end

function local_validate_params(params)
assert(any(params.run_mode == ["smoke", "full"]), ...
    'load_multiscale_chunking_config:BadRunMode', ...
    'run_mode must be smoke or full.');
assert(any(lower(params.anchor_mode) == ["center", "past"]), ...
    'load_multiscale_chunking_config:BadAnchorMode', ...
    'anchor_mode must be center or past.');
assert(params.min_scale_sec > 0 && params.max_scale_sec > params.min_scale_sec, ...
    'load_multiscale_chunking_config:BadScaleRange', ...
    'min_scale_sec and max_scale_sec must be positive and ordered.');
assert(params.fps > 0, ...
    'load_multiscale_chunking_config:BadFps', ...
    'fps must be positive.');
assert(params.n_scales >= 3 && params.smoke_n_scales >= 3, ...
    'load_multiscale_chunking_config:BadScaleCount', ...
    'n_scales and smoke_n_scales must be at least 3.');
assert(params.scale_band_micro_max_sec > params.min_scale_sec && ...
    params.scale_band_motif_max_sec > params.scale_band_micro_max_sec && ...
    params.scale_band_motif_max_sec < params.max_scale_sec, ...
    'load_multiscale_chunking_config:BadScaleBandCutoffs', ...
    'Scale band cutoffs must lie inside min/max scale range and be ordered.');
assert(params.stride_sec > 0, ...
    'load_multiscale_chunking_config:BadStride', ...
    'stride_sec must be positive.');
assert(params.min_chunk_valid_frac >= 0 && params.min_chunk_valid_frac <= 1, ...
    'load_multiscale_chunking_config:BadValidFraction', ...
    'min_chunk_valid_frac must be in [0, 1].');
assert(params.min_chunk_feature_finite_frac >= 0 && params.min_chunk_feature_finite_frac <= 1, ...
    'load_multiscale_chunking_config:BadFiniteFraction', ...
    'min_chunk_feature_finite_frac must be in [0, 1].');
assert(params.max_scaling_frames_per_session >= 1, ...
    'load_multiscale_chunking_config:BadScalingSample', ...
    'max_scaling_frames_per_session must be positive.');
assert(islogical(params.save_chunk_mat_artifact) || isnumeric(params.save_chunk_mat_artifact), ...
    'load_multiscale_chunking_config:BadSaveChunkMatArtifact', ...
    'save_chunk_mat_artifact must be logical.');
assert(islogical(params.use_scale_summary_shards) || isnumeric(params.use_scale_summary_shards), ...
    'load_multiscale_chunking_config:BadUseScaleSummaryShards', ...
    'use_scale_summary_shards must be logical.');
assert(islogical(params.reuse_scale_summary_shards) || isnumeric(params.reuse_scale_summary_shards), ...
    'load_multiscale_chunking_config:BadReuseScaleSummaryShards', ...
    'reuse_scale_summary_shards must be logical.');
assert(strlength(string(params.scale_summary_shard_dir)) > 0, ...
    'load_multiscale_chunking_config:BadScaleSummaryShardDir', ...
    'scale_summary_shard_dir must be nonempty.');
assert(params.smoke_max_sessions >= 1, ...
    'load_multiscale_chunking_config:BadSmokeSessions', ...
    'smoke_max_sessions must be positive.');
assert(params.max_anchor_manifest_anchors >= 1 && params.smoke_max_anchor_manifest_anchors >= 1, ...
    'load_multiscale_chunking_config:BadAnchorCap', ...
    'Anchor materialization caps must be positive.');
assert(params.min_materialized_anchors_per_session >= 0, ...
    'load_multiscale_chunking_config:BadSessionMinimum', ...
    'min_materialized_anchors_per_session must be nonnegative.');
assert(params.score_n_pcs >= 2 && params.score_n_clusters >= 2, ...
    'load_multiscale_chunking_config:BadScoreParams', ...
    'score_n_pcs and score_n_clusters must be at least 2.');
assert(params.score_variance_target_pct > 0 && params.score_variance_target_pct < 100, ...
    'load_multiscale_chunking_config:BadVarianceTarget', ...
    'score_variance_target_pct must be between 0 and 100.');
assert(params.score_max_chunks_per_scale >= 200, ...
    'load_multiscale_chunking_config:BadScoreChunkCap', ...
    'score_max_chunks_per_scale must be at least 200.');
assert(any(lower(params.score_representation_mode) == ["multiresolution", "flattened"]), ...
    'load_multiscale_chunking_config:BadRepresentationMode', ...
    'score_representation_mode must be multiresolution or flattened.');
assert(params.summary_temporal_bins >= 1 && params.summary_dct_coeffs >= 0, ...
    'load_multiscale_chunking_config:BadSummaryParams', ...
    'summary_temporal_bins must be positive and summary_dct_coeffs must be nonnegative.');
assert(params.stability_bootstraps >= 1 && params.smoke_stability_bootstraps >= 1, ...
    'load_multiscale_chunking_config:BadStabilityBootstraps', ...
    'Stability bootstrap counts must be positive.');
assert(params.stability_selection_frequency_threshold >= 0 && params.stability_selection_frequency_threshold <= 1, ...
    'load_multiscale_chunking_config:BadStabilityThreshold', ...
    'stability_selection_frequency_threshold must be in [0, 1].');
assert(params.embedding_dim_micro_min_pcs <= params.embedding_dim_micro_max_pcs && ...
    params.embedding_dim_motif_min_pcs <= params.embedding_dim_motif_max_pcs && ...
    params.embedding_dim_context_min_pcs <= params.embedding_dim_context_max_pcs, ...
    'load_multiscale_chunking_config:BadEmbeddingDimCaps', ...
    'Embedding dimension min PCs must not exceed max PCs.');
assert(params.dimension_guard_min_effective_dim >= 1 && ...
    params.dimension_guard_max_pc1_explained_pct > 0 && params.dimension_guard_max_pc1_explained_pct <= 100, ...
    'load_multiscale_chunking_config:BadDimensionGuard', ...
    'Dimension guard thresholds must be positive and bounded.');
assert(params.primary_scale_rule == "stable_and_dimension_supported", ...
    'load_multiscale_chunking_config:BadPrimaryScaleRule', ...
    'primary_scale_rule must currently be stable_and_dimension_supported.');
assert(params.scale_specific_max_anchors_per_scale >= 1 && ...
    params.smoke_scale_specific_max_anchors_per_scale >= 1 && ...
    params.scale_specific_min_anchors_per_session >= 0, ...
    'load_multiscale_chunking_config:BadScaleSpecificAnchorParams', ...
    'Scale-specific anchor caps must be positive and session minimum nonnegative.');
assert(params.pca_loading_stability_splits >= 1 && params.smoke_pca_loading_stability_splits >= 1 && ...
    params.pca_loading_stability_threshold >= 0 && params.pca_loading_stability_threshold <= 1, ...
    'load_multiscale_chunking_config:BadPcaLoadingStabilityParams', ...
    'PCA loading stability split counts and threshold are invalid.');
assert(params.event_contact_threshold >= 0 && params.event_state_threshold >= 0 && ...
    params.event_turn_threshold_deg > 0, ...
    'load_multiscale_chunking_config:BadEventSummaryParams', ...
    'Event summary thresholds must be nonnegative and turn threshold positive.');
assert(params.arena_sensitivity_n_embedding_pcs >= 1 && params.arena_sensitivity_top_n_features >= 1, ...
    'load_multiscale_chunking_config:BadArenaSensitivityParams', ...
    'Arena sensitivity PC and top-feature counts must be positive.');
local_validate_run_mode_paths(params);
end

function local_validate_run_mode_paths(params)
outputDir = lower(replace(string(params.output_dir), "\", "/"));
if params.run_mode == "full"
    assert(~contains(outputDir, "smoke"), ...
        'load_multiscale_chunking_config:BadFullOutputDir', ...
        'Full run_06 output_dir must not point to a smoke directory.');
end
end

function value = local_parse_value(rawValue, valueType, parameterName)
rawValue = string(rawValue);
switch valueType
    case "number"
        if lower(strtrim(rawValue)) == "nan"
            value = NaN;
        else
            value = str2double(rawValue);
        end
        assert(isfinite(value) || isnan(value), ...
            'load_multiscale_chunking_config:BadNumber', ...
            '%s must be numeric.', parameterName);
    case "logical"
        raw = lower(strtrim(rawValue));
        assert(any(raw == ["true", "false", "1", "0", "yes", "no"]), ...
            'load_multiscale_chunking_config:BadLogical', ...
            '%s must be logical.', parameterName);
        value = any(raw == ["true", "1", "yes"]);
    case "string"
        value = rawValue;
    case "string_list"
        if lower(strtrim(rawValue)) == "all"
            value = "all";
        else
            value = string(split(rawValue, {';', '|', ','}))';
            value = strtrim(value);
            value = value(value ~= "");
        end
    otherwise
        error('load_multiscale_chunking_config:BadType', ...
            'Unknown config type "%s" for parameter "%s".', valueType, parameterName);
end
end

function value = local_value_to_string(x)
if islogical(x)
    value = string(x);
elseif isnumeric(x)
    if isscalar(x) && isnan(x)
        value = "NaN";
    elseif isscalar(x)
        value = string(sprintf('%.15g', x));
    else
        value = strjoin(string(compose('%.15g', x(:)')), ";");
    end
elseif isstring(x) || ischar(x)
    value = strjoin(string(x), ";");
else
    value = string(evalc('disp(x)'));
    value = strtrim(value);
end
end
