function Analysis = analyze_run09_partition_ensemble(Adapter, Ensemble, params, Consensus)
%ANALYZE_RUN09_PARTITION_ENSEMBLE Topology-only stability and hierarchy audit.
%
% The locked partition at each resolution is the replicate medoid under
% mean pairwise adjusted Rand index, with quality and seed as deterministic
% topology-only tie breakers. No node metadata enter this function.

Audit = Ensemble.replicate_audit;
Memberships = Ensemble.memberships;
useConsensus = nargin >= 4 && ~isempty(Consensus);
assert(size(Memberships, 1) == numel(Adapter.node_ids) && ...
    size(Memberships, 2) == height(Audit), ...
    'analyze_run09_partition_ensemble:DimensionMismatch', ...
    'Membership matrix dimensions do not match nodes and replicate audit.');
assert(all(Audit.status == "success") && all(Audit.converged), ...
    'analyze_run09_partition_ensemble:IncompleteEnsemble', ...
    'Stability analysis requires successful converged replicates only.');

PartitionStability = i_all_pairwise_metrics(Audit, Memberships);
primaryMask = Audit.objective == "cpm";
resolutionIndices = unique(Audit.resolution_index(primaryMask), 'sorted');
nResolutions = numel(resolutionIndices);
nNodes = numel(Adapter.node_ids);
stage = i_membership_stage(params);
if useConsensus
    assert(isequal(size(Consensus.memberships), [nNodes nResolutions]) && ...
        numel(Consensus.resolution_ids) == nResolutions, ...
        'analyze_run09_partition_ensemble:BadConsensusDimensions', ...
        'Consensus dimensions must match nodes and CPM resolutions.');
    PartitionStability = [PartitionStability; ...
        Consensus.partition_stability];
end

SensitivityRows = cell(nResolutions, 1);
AmbiguityRows = cell(nResolutions, 1);
MembershipRows = cell(nResolutions, 1);
DefinitionRows = cell(nResolutions, 1);
ReferenceMemberships = zeros(nNodes, nResolutions, 'uint32');
ResolutionIds = strings(nResolutions, 1);
ReferenceReplicateIds = strings(nResolutions, 1);

for level = 1:nResolutions
    resolutionIndex = resolutionIndices(level);
    idx = find(primaryMask & Audit.resolution_index == resolutionIndex);
    groupAudit = Audit(idx, :);
    groupMemberships = Memberships(:, idx);
    [referenceLocalIndex, meanAriByReplicate] = ...
        i_choose_reference(groupAudit, groupMemberships);
    reference = uint32(groupMemberships(:, referenceLocalIndex));
    partitionSource = "raw_seed_ari_medoid";
    representativeId = groupAudit.replicate_id(referenceLocalIndex);
    representativeSeed = groupAudit.seed(referenceLocalIndex);
    voteSupport = nan(nNodes, 1);
    consensusMinAri = NaN;
    consensusMaxNvi = NaN;
    consensusMeanNodeStability = NaN;
    consensusMeanVoteSupport = NaN;
    consensusGateConvergence = false;
    consensusGateAri = false;
    consensusGateVi = false;
    consensusGateNodeStability = false;
    consensusGateVoteSupport = false;
    if useConsensus
        reference = uint32(Consensus.memberships(:, level));
        partitionSource = ...
            "label_aligned_plurality_then_frozen_graph_refinement";
        representativeId = "run09_consensus_" + ...
            lower(Consensus.resolution_ids(level)) + "_full";
        representativeSeed = params.consensus_refinement_seed;
        voteSupport = Consensus.vote_support(:, level);
        consensusRows = Consensus.partition_stability( ...
            Consensus.partition_stability.resolution_index == level, :);
        consensusMinAri = min(consensusRows.adjusted_rand_index);
        consensusMaxNvi = max( ...
            consensusRows.normalized_variation_of_information);
        consensusMeanNodeStability = mean( ...
            Consensus.split_node_stability_mean(:, level));
        consensusMeanVoteSupport = mean(voteSupport);
        consensusAuditRows = Consensus.audit( ...
            Consensus.audit.hierarchy_level == level, :);
        consensusGateConvergence = ...
            all(consensusAuditRows.converged & ...
            consensusAuditRows.status == "success");
        consensusGateAri = consensusMinAri >= ...
            params.consensus_retention_min_split_ari;
        consensusGateVi = consensusMaxNvi <= ...
            params.consensus_retention_max_normalized_vi;
        consensusGateNodeStability = consensusMeanNodeStability >= ...
            params.consensus_retention_min_mean_node_stability;
        consensusGateVoteSupport = consensusMeanVoteSupport >= ...
            params.consensus_retention_min_mean_vote_support;
    end
    ReferenceMemberships(:, level) = reference;
    multiplier = groupAudit.density_multiplier(1);
    resolutionId = i_resolution_id(multiplier);
    ResolutionIds(level) = resolutionId;
    ReferenceReplicateIds(level) = representativeId;

    if useConsensus
        nodeStability = Consensus.split_node_stability_mean(:, level);
        nodeStabilityMin = Consensus.split_node_stability_min(:, level);
        mappedRate = Consensus.split_mapped_assignment_rate(:, level);
    else
        [nodeStability, nodeStabilityMin, mappedRate] = ...
            i_node_stability(reference, groupMemberships, ...
            referenceLocalIndex);
    end
    ambiguity = 1 - nodeStability;
    boundary = nodeStability < params.ambiguity_min_node_stability;
    candidateCount = double(max(reference));
    candidateIds = i_candidate_ids(multiplier, candidateCount);
    candidateForNode = candidateIds(double(reference));

    AmbiguityRows{level} = table( ...
        uint64(Adapter.node_ids), repmat(resolutionId, nNodes, 1), ...
        repmat(level, nNodes, 1), candidateForNode, nodeStability, ...
        nodeStabilityMin, mappedRate, voteSupport, ambiguity, boundary, ...
        repmat(stage, nNodes, 1), ...
        'VariableNames', {'graph_node_id', 'resolution_id', ...
        'hierarchy_level', 'motif_candidate_id', ...
        'coassignment_jaccard_mean', 'coassignment_jaccard_min', ...
        'mapped_assignment_rate', 'consensus_vote_support', ...
        'ambiguity_score', ...
        'is_boundary_ambiguous', 'membership_status'});
    MembershipRows{level} = table( ...
        uint64(Adapter.node_ids), repmat(resolutionId, nNodes, 1), ...
        repmat(level, nNodes, 1), candidateForNode, ...
        repmat(representativeId, nNodes, 1), ...
        repmat(compute_run09_membership_sha256(reference), ...
        nNodes, 1), repmat(stage, nNodes, 1), ...
        'VariableNames', {'graph_node_id', 'resolution_id', ...
        'hierarchy_level', 'motif_candidate_id', ...
        'representative_replicate_id', ...
        'representative_membership_sha256', 'membership_status'});

    sizes = accumarray(double(reference), 1, [candidateCount 1]);
    prevalence = sizes / nNodes;
    meanStability = accumarray(double(reference), nodeStability, ...
        [candidateCount 1], @mean);
    minStability = accumarray(double(reference), nodeStability, ...
        [candidateCount 1], @min);
    boundaryFraction = accumarray(double(reference), double(boundary), ...
        [candidateCount 1], @mean);
    DefinitionRows{level} = table(candidateIds, ...
        repmat(resolutionId, candidateCount, 1), ...
        repmat(level, candidateCount, 1), (1:candidateCount)', ...
        sizes, prevalence, meanStability, minStability, ...
        boundaryFraction, repmat(stage, candidateCount, 1), ...
        'VariableNames', {'motif_candidate_id', 'resolution_id', ...
        'hierarchy_level', 'candidate_local_index', 'node_count', ...
        'node_prevalence', 'mean_node_stability', ...
        'minimum_node_stability', 'boundary_node_fraction', ...
        'membership_status'});

    pairMask = PartitionStability.objective == "cpm" & ...
        PartitionStability.resolution_index == resolutionIndex;
    pairRows = PartitionStability(pairMask, :);
    qualityValues = double(groupAudit.quality);
    candidateCounts = double(groupAudit.candidate_count);
    singletonCount = nnz(sizes == 1);
    smallMask = sizes <= params.small_candidate_max_nodes;
    smallCount = nnz(smallMask);
    singletonNodeFraction = singletonCount / nNodes;
    smallNodeFraction = sum(sizes(smallMask)) / nNodes;
    countRelativeRange = (max(candidateCounts) - min(candidateCounts)) / ...
        max(median(candidateCounts), 1);
    if isempty(pairRows)
        meanPairAri = 1;
        minPairAri = 1;
        meanPairVi = 0;
        maxPairNvi = 0;
    else
        meanPairAri = mean(pairRows.adjusted_rand_index);
        minPairAri = min(pairRows.adjusted_rand_index);
        meanPairVi = mean(pairRows.variation_of_information);
        maxPairNvi = max(pairRows.normalized_variation_of_information);
    end
    successfulReplicates = height(groupAudit);
    gateReplicates = successfulReplicates >= ...
        params.active_retention_min_successful_replicates;
    gateConvergence = all(groupAudit.converged & ...
        groupAudit.status == "success");
    gateFiniteQuality = all(isfinite(qualityValues));
    gateAri = minPairAri >= params.retention_min_pairwise_ari;
    gateVi = maxPairNvi <= params.retention_max_normalized_vi;
    gateCount = candidateCount >= params.retention_min_candidate_count && ...
        candidateCount <= params.retention_max_candidate_count;
    gateCountRange = countRelativeRange <= ...
        params.retention_max_candidate_count_relative_range;
    gateSingleton = singletonNodeFraction <= ...
        params.retention_max_singleton_node_fraction;
    gateSmall = smallNodeFraction <= ...
        params.retention_max_small_candidate_node_fraction;
    gateNodeStability = mean(nodeStability) >= ...
        params.retention_min_mean_node_stability;
    rawRetained = all([gateReplicates, gateConvergence, ...
        gateFiniteQuality, gateAri, gateVi, gateCount, gateCountRange, ...
        gateSingleton, gateSmall, gateNodeStability]);
    if useConsensus
        retained = all([gateReplicates, gateConvergence, ...
            gateFiniteQuality, gateCount, gateSingleton, gateSmall, ...
            consensusGateConvergence, consensusGateAri, ...
            consensusGateVi, consensusGateNodeStability, ...
            consensusGateVoteSupport]);
    else
        retained = rawRetained;
    end

    SensitivityRows{level} = table(resolutionId, level, multiplier, ...
        groupAudit.resolution(1), successfulReplicates, ...
        representativeId, representativeSeed, ...
        meanAriByReplicate(referenceLocalIndex), candidateCount, ...
        min(candidateCounts), max(candidateCounts), ...
        countRelativeRange, singletonCount, singletonNodeFraction, ...
        smallCount, smallNodeFraction, mean(qualityValues), ...
        std(qualityValues, 0), min(qualityValues), max(qualityValues), ...
        meanPairAri, minPairAri, meanPairVi, maxPairNvi, ...
        mean(nodeStability), median(nodeStability), ...
        i_quantile(nodeStability, 0.05), mean(boundary), ...
        gateReplicates, gateConvergence, gateFiniteQuality, gateAri, ...
        gateVi, gateCount, gateCountRange, gateSingleton, gateSmall, ...
        gateNodeStability, retained, ...
        partitionSource, rawRetained, consensusMinAri, ...
        consensusMaxNvi, consensusMeanNodeStability, ...
        consensusMeanVoteSupport, consensusGateConvergence, ...
        consensusGateAri, consensusGateVi, ...
        consensusGateNodeStability, consensusGateVoteSupport, ...
        NaN, NaN, NaN, false, ...
        'VariableNames', {'resolution_id', 'hierarchy_level', ...
        'density_multiplier', 'resolution', 'successful_replicates', ...
        'representative_replicate_id', 'representative_seed', ...
        'representative_mean_pairwise_ari', ...
        'representative_candidate_count', 'minimum_candidate_count', ...
        'maximum_candidate_count', 'candidate_count_relative_range', ...
        'singleton_candidate_count', 'singleton_node_fraction', ...
        'small_candidate_count', 'small_candidate_node_fraction', ...
        'mean_quality', 'sd_quality', 'minimum_quality', ...
        'maximum_quality', 'mean_pairwise_ari', ...
        'minimum_pairwise_ari', 'mean_variation_of_information', ...
        'maximum_normalized_variation_of_information', ...
        'mean_node_stability', 'median_node_stability', ...
        'p05_node_stability', 'boundary_node_fraction', ...
        'gate_minimum_replicates', 'gate_all_converged', ...
        'gate_finite_quality', 'gate_pairwise_ari', ...
        'gate_normalized_vi', 'gate_candidate_count', ...
        'gate_candidate_count_range', 'gate_singleton_fraction', ...
        'gate_small_candidate_fraction', 'gate_node_stability', ...
        'retained_by_predeclared_rules', ...
        'partition_source', 'pilot_raw_stability_gate_pass', ...
        'minimum_consensus_split_ari', ...
        'maximum_consensus_split_normalized_vi', ...
        'mean_consensus_split_node_stability', ...
        'mean_consensus_vote_support', ...
        'gate_consensus_convergence', 'gate_consensus_split_ari', ...
        'gate_consensus_normalized_vi', ...
        'gate_consensus_node_stability', ...
        'gate_consensus_vote_support', ...
        'previous_level_weighted_child_purity', ...
        'previous_level_linked_node_fraction', ...
        'previous_level_linked_candidate_fraction', ...
        'previous_level_hierarchy_supported'});
end

ResolutionSensitivity = vertcat(SensitivityRows{:});
NodeAmbiguity = vertcat(AmbiguityRows{:});
NodeMembership = vertcat(MembershipRows{:});
CandidateDefinition = vertcat(DefinitionRows{:});
[HierarchyResolutionAudit, NestingSummary] = i_build_hierarchy( ...
    ReferenceMemberships, ResolutionIds, ResolutionSensitivity, ...
    CandidateDefinition, params);
for level = 2:nResolutions
    ResolutionSensitivity.previous_level_weighted_child_purity(level) = ...
        NestingSummary.weighted_child_purity(level - 1);
    ResolutionSensitivity.previous_level_linked_node_fraction(level) = ...
        NestingSummary.linked_node_fraction(level - 1);
    ResolutionSensitivity.previous_level_linked_candidate_fraction(level) = ...
        NestingSummary.linked_candidate_fraction(level - 1);
    ResolutionSensitivity.previous_level_hierarchy_supported(level) = ...
        NestingSummary.hierarchy_supported(level - 1);
end

retainedMask = logical( ...
    ResolutionSensitivity.retained_by_predeclared_rules);
if params.run_mode == "full"
    retainedIds = ResolutionIds(retainedMask);
    retainedReferences = ReferenceMemberships(:, retainedMask);
    retainedSensitivity = ResolutionSensitivity(retainedMask, :);
    NodeAmbiguity = i_filter_and_relevel( ...
        NodeAmbiguity, retainedIds);
    NodeMembership = i_filter_and_relevel( ...
        NodeMembership, retainedIds);
    CandidateDefinition = i_filter_and_relevel( ...
        CandidateDefinition, retainedIds);
    Hierarchy = i_build_retained_hierarchy( ...
        retainedReferences, retainedIds, retainedSensitivity, ...
        CandidateDefinition, params);
    frozenResolutionIds = retainedIds;
    frozenReferenceMemberships = retainedReferences;
    frozenReferenceReplicateIds = ReferenceReplicateIds(retainedMask);
else
    Hierarchy = HierarchyResolutionAudit;
    frozenResolutionIds = ResolutionIds;
    frozenReferenceMemberships = ReferenceMemberships;
    frozenReferenceReplicateIds = ReferenceReplicateIds;
end

Analysis = struct();
Analysis.partition_stability = PartitionStability;
Analysis.resolution_sensitivity = ResolutionSensitivity;
Analysis.node_ambiguity = NodeAmbiguity;
Analysis.hierarchy = Hierarchy;
Analysis.hierarchy_resolution_audit = HierarchyResolutionAudit;
Analysis.candidate_definition = CandidateDefinition;
Analysis.node_membership = NodeMembership;
Analysis.reference_memberships = frozenReferenceMemberships;
Analysis.resolution_ids = frozenResolutionIds;
Analysis.reference_replicate_ids = frozenReferenceReplicateIds;
Analysis.all_resolution_reference_memberships = ReferenceMemberships;
Analysis.all_resolution_ids = ResolutionIds;
Analysis.all_active_resolutions_retained = ...
    ~isempty(retainedMask) && all(retainedMask);
Analysis.n_retained_resolutions = nnz(retainedMask);
Analysis.has_retained_resolution = any(retainedMask);
Analysis.multilevel_hierarchy_supported = ...
    Analysis.n_retained_resolutions >= 2 && ...
    ~isempty(Hierarchy) && ...
    all(Hierarchy.pair_hierarchy_supported( ...
    Hierarchy.link_status ~= "retained_root_no_parent"));
end

function T = i_filter_and_relevel(T, retainedIds)
keep = ismember(T.resolution_id, retainedIds);
T = T(keep, :);
for level = 1:numel(retainedIds)
    T.hierarchy_level(T.resolution_id == retainedIds(level)) = level;
end
end

function Hierarchy = i_build_retained_hierarchy( ...
        Memberships, ResolutionIds, Sensitivity, Definition, params)
if isempty(ResolutionIds)
    Hierarchy = i_empty_hierarchy_table();
    return
end
rootDefinition = Definition( ...
    Definition.resolution_id == ResolutionIds(1), :);
nRoots = height(rootDefinition);
rootNodeCount = double(rootDefinition.node_count);
Root = table( ...
    repmat("H_ROOT_" + ResolutionIds(1), nRoots, 1), ...
    repmat("", nRoots, 1), repmat(ResolutionIds(1), nRoots, 1), ...
    rootDefinition.motif_candidate_id, repmat("", nRoots, 1), ...
    repmat("", nRoots, 1), rootNodeCount, rootNodeCount, ...
    nan(nRoots, 1), ones(nRoots, 1), nan(nRoots, 1), ...
    nan(nRoots, 1), nan(nRoots, 1), nan(nRoots, 1), ...
    true(nRoots, 1), false(nRoots, 1), false(nRoots, 1), ...
    repmat("retained_root_no_parent", nRoots, 1), ...
    false(nRoots, 1), true(nRoots, 1), ...
    'VariableNames', i_hierarchy_variable_names());
if isscalar(ResolutionIds)
    Hierarchy = Root;
    return
end
[CrossLevel, ~] = i_build_hierarchy( ...
    Memberships, ResolutionIds, Sensitivity, Definition, params);
Hierarchy = [Root; CrossLevel];
end

function Pairwise = i_all_pairwise_metrics(Audit, Memberships)
Pairwise = i_empty_pairwise_table();
keys = unique(Audit(:, {'objective', 'resolution_index'}), 'rows', 'stable');
for g = 1:height(keys)
    idx = find(Audit.objective == keys.objective(g) & ...
        Audit.resolution_index == keys.resolution_index(g));
    nPairs = numel(idx) * (numel(idx) - 1) / 2;
    if nPairs == 0
        continue
    end
    rows = cell(nPairs, 1);
    cursor = 0;
    for a = 1:numel(idx)-1
        for b = a+1:numel(idx)
            cursor = cursor + 1;
            ia = idx(a);
            ib = idx(b);
            [ari, vi, nvi] = i_partition_metrics( ...
                Memberships(:, ia), Memberships(:, ib));
            rows{cursor} = table(Audit.objective(ia), ...
                Audit.resolution_index(ia), Audit.density_multiplier(ia), ...
                Audit.resolution(ia), Audit.replicate_id(ia), ...
                Audit.replicate_id(ib), Audit.seed(ia), Audit.seed(ib), ...
                Audit.candidate_count(ia), Audit.candidate_count(ib), ...
                ari, vi, nvi, "raw_seed_pair", ...
                'VariableNames', Pairwise.Properties.VariableNames);
        end
    end
    Pairwise = [Pairwise; vertcat(rows{:})]; %#ok<AGROW>
end
end

function T = i_empty_pairwise_table()
T = table(strings(0, 1), zeros(0, 1), nan(0, 1), nan(0, 1), ...
    strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), nan(0, 1), nan(0, 1), nan(0, 1), ...
    strings(0, 1), ...
    'VariableNames', {'objective', 'resolution_index', ...
    'density_multiplier', 'resolution', 'replicate_id_a', ...
    'replicate_id_b', 'seed_a', 'seed_b', 'candidate_count_a', ...
    'candidate_count_b', 'adjusted_rand_index', ...
    'variation_of_information', 'normalized_variation_of_information', ...
    'comparison_type'});
end

function [ari, vi, normalizedVi] = i_partition_metrics(a, b)
a = double(canonicalize_run09_membership(a));
b = double(canonicalize_run09_membership(b));
n = numel(a);
ka = max(a);
kb = max(b);
joint = sparse(a, b, 1, ka, kb);
jointCounts = nonzeros(joint);
rowCounts = full(sum(joint, 2));
columnCounts = full(sum(joint, 1))';
comb2 = @(x) x .* (x - 1) / 2;
index = sum(comb2(jointCounts));
rowPairs = sum(comb2(rowCounts));
columnPairs = sum(comb2(columnCounts));
totalPairs = comb2(n);
expected = rowPairs * columnPairs / max(totalPairs, eps);
maximum = 0.5 * (rowPairs + columnPairs);
denominator = maximum - expected;
if abs(denominator) <= eps(maximum)
    ari = double(isequal(a, b));
else
    ari = (index - expected) / denominator;
end

[jointRow, jointColumn, counts] = find(joint);
pJoint = counts / n;
pRow = rowCounts / n;
pColumn = columnCounts / n;
hA = -sum(pRow(pRow > 0) .* log(pRow(pRow > 0)));
hB = -sum(pColumn(pColumn > 0) .* log(pColumn(pColumn > 0)));
mutualInformation = sum(pJoint .* log(pJoint ./ ...
    (pRow(jointRow) .* pColumn(jointColumn))));
vi = max(0, hA + hB - 2 * mutualInformation);
normalizedVi = vi / max(log(n), eps);
end

function [referenceIndex, meanAri] = i_choose_reference(Audit, Memberships)
nReplicates = width(Memberships);
ariMatrix = eye(nReplicates);
for a = 1:nReplicates-1
    for b = a+1:nReplicates
        ari = i_partition_metrics(Memberships(:, a), Memberships(:, b));
        ariMatrix(a, b) = ari;
        ariMatrix(b, a) = ari;
    end
end
if nReplicates == 1
    meanAri = 1;
else
    meanAri = (sum(ariMatrix, 2) - 1) / (nReplicates - 1);
end
tieBreak = table(-meanAri(:), -double(Audit.quality), ...
    double(Audit.seed), (1:nReplicates)', ...
    'VariableNames', {'negative_mean_ari', 'negative_quality', ...
    'seed', 'local_index'});
tieBreak = sortrows(tieBreak, {'negative_mean_ari', ...
    'negative_quality', 'seed', 'local_index'});
referenceIndex = tieBreak.local_index(1);
end

function [meanJaccard, minimumJaccard, mappedRate] = ...
        i_node_stability(reference, Memberships, referenceIndex)
n = numel(reference);
nReplicates = width(Memberships);
comparisonIndices = setdiff(1:nReplicates, referenceIndex, 'stable');
if isempty(comparisonIndices)
    meanJaccard = ones(n, 1);
    minimumJaccard = ones(n, 1);
    mappedRate = ones(n, 1);
    return
end
jaccardSum = zeros(n, 1);
minimumJaccard = ones(n, 1);
mappedSum = zeros(n, 1);
reference = double(reference);
referenceCount = accumarray(reference, 1);
for column = comparisonIndices
    other = double(Memberships(:, column));
    otherCount = accumarray(other, 1);
    overlap = sparse(reference, other, 1, ...
        numel(referenceCount), numel(otherCount));
    linear = sub2ind(size(overlap), reference, other);
    intersection = full(overlap(linear));
    unionCount = referenceCount(reference) + otherCount(other) - ...
        intersection;
    jaccard = intersection ./ unionCount;
    jaccardSum = jaccardSum + jaccard;
    minimumJaccard = min(minimumJaccard, jaccard);
    [~, mapToReference] = max(overlap, [], 1);
    mapToReference = mapToReference(:);
    mapped = double(mapToReference(other(:))) == reference;
    mappedSum = mappedSum + mapped(:);
end
meanJaccard = jaccardSum / numel(comparisonIndices);
mappedRate = mappedSum / numel(comparisonIndices);
end

function [Hierarchy, Summary] = i_build_hierarchy( ...
        Memberships, ResolutionIds, Sensitivity, Definition, params)
nLevels = width(Memberships);
rows = cell(max(nLevels - 1, 0), 1);
weightedPurity = nan(max(nLevels - 1, 0), 1);
linkedNodeFraction = nan(max(nLevels - 1, 0), 1);
linkedCandidateFraction = nan(max(nLevels - 1, 0), 1);
supported = false(max(nLevels - 1, 0), 1);
for level = 2:nLevels
    parent = double(Memberships(:, level - 1));
    child = double(Memberships(:, level));
    nParent = max(parent);
    nChild = max(child);
    overlap = sparse(child, parent, 1, nChild, nParent);
    [bestCount, bestParent] = max(overlap, [], 2);
    bestCount = full(bestCount);
    bestParent = full(bestParent);
    childSize = accumarray(child, 1, [nChild 1]);
    parentSize = accumarray(parent, 1, [nParent 1]);
    childFraction = bestCount ./ childSize;
    parentFraction = bestCount ./ parentSize(bestParent);
    jaccard = bestCount ./ ...
        (childSize + parentSize(bestParent) - bestCount);
    weightedPurity(level - 1) = sum(bestCount) / numel(child);
    candidateLink = childFraction >= ...
        params.hierarchy_min_child_parent_fraction;
    linkedNodeFraction(level - 1) = ...
        sum(childSize(candidateLink)) / numel(child);
    linkedCandidateFraction(level - 1) = mean(candidateLink);
    supported(level - 1) = ...
        weightedPurity(level - 1) >= ...
        params.hierarchy_min_pair_weighted_child_purity && ...
        linkedNodeFraction(level - 1) >= ...
        params.hierarchy_min_linked_node_fraction;
    retainedLink = candidateLink & supported(level - 1);

    fineDefinition = Definition( ...
        Definition.resolution_id == ResolutionIds(level), :);
    coarseDefinition = Definition( ...
        Definition.resolution_id == ResolutionIds(level - 1), :);
    childIds = fineDefinition.motif_candidate_id;
    bestParentIds = coarseDefinition.motif_candidate_id(bestParent);
    parentIds = repmat("", nChild, 1);
    parentIds(retainedLink) = bestParentIds(retainedLink);
    linkStatus = repmat("unsupported_empirical_nesting", nChild, 1);
    linkStatus(retainedLink) = "retained_parent_link";
    hierarchyId = "H_" + ResolutionIds(level - 1) + "_TO_" + ...
        ResolutionIds(level);
    rows{level - 1} = table(repmat(hierarchyId, nChild, 1), ...
        repmat(ResolutionIds(level - 1), nChild, 1), ...
        repmat(ResolutionIds(level), nChild, 1), childIds, ...
        bestParentIds, parentIds, bestCount, childSize, ...
        parentSize(bestParent), childFraction, parentFraction, jaccard, ...
        repmat(weightedPurity(level - 1), nChild, 1), ...
        repmat(linkedNodeFraction(level - 1), nChild, 1), ...
        candidateLink, repmat(supported(level - 1), nChild, 1), ...
        retainedLink, linkStatus, ...
        repmat(Sensitivity.retained_by_predeclared_rules(level - 1), ...
        nChild, 1), ...
        repmat(Sensitivity.retained_by_predeclared_rules(level), ...
        nChild, 1), ...
        'VariableNames', {'hierarchy_id', 'coarse_resolution_id', ...
        'fine_resolution_id', 'child_motif_candidate_id', ...
        'best_match_parent_candidate_id', ...
        'hierarchy_parent_candidate_id', 'overlap_node_count', ...
        'child_node_count', 'parent_node_count', ...
        'child_parent_consistency', 'parent_coverage_fraction', ...
        'parent_child_jaccard', 'pair_weighted_child_purity', ...
        'pair_linked_node_fraction', 'candidate_link_gate_pass', ...
        'pair_hierarchy_supported', 'parent_link_retained', ...
        'link_status', 'coarse_resolution_retained', ...
        'fine_resolution_retained'});
end
if isempty(rows)
    Hierarchy = i_empty_hierarchy_table();
else
    Hierarchy = vertcat(rows{:});
end
Summary = table(weightedPurity, linkedNodeFraction, ...
    linkedCandidateFraction, supported, ...
    'VariableNames', {'weighted_child_purity', ...
    'linked_node_fraction', 'linked_candidate_fraction', ...
    'hierarchy_supported'});
end

function T = i_empty_hierarchy_table()
T = table(strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), nan(0, 1), nan(0, 1), ...
    nan(0, 1), nan(0, 1), nan(0, 1), nan(0, 1), ...
    false(0, 1), false(0, 1), false(0, 1), strings(0, 1), ...
    false(0, 1), false(0, 1), ...
    'VariableNames', i_hierarchy_variable_names());
end

function names = i_hierarchy_variable_names()
names = {'hierarchy_id', 'coarse_resolution_id', ...
    'fine_resolution_id', 'child_motif_candidate_id', ...
    'best_match_parent_candidate_id', ...
    'hierarchy_parent_candidate_id', 'overlap_node_count', ...
    'child_node_count', 'parent_node_count', ...
    'child_parent_consistency', 'parent_coverage_fraction', ...
    'parent_child_jaccard', 'pair_weighted_child_purity', ...
    'pair_linked_node_fraction', 'candidate_link_gate_pass', ...
    'pair_hierarchy_supported', 'parent_link_retained', ...
    'link_status', 'coarse_resolution_retained', ...
    'fine_resolution_retained'};
end

function value = i_quantile(x, probability)
x = sort(double(x(:)));
if isempty(x)
    value = NaN;
    return
end
position = 1 + (numel(x) - 1) * probability;
lowerIndex = floor(position);
upperIndex = ceil(position);
if lowerIndex == upperIndex
    value = x(lowerIndex);
else
    value = x(lowerIndex) + (position - lowerIndex) * ...
        (x(upperIndex) - x(lowerIndex));
end
end

function value = i_resolution_id(multiplier)
value = compose("CPM_M%06d", round(1000 * multiplier));
end

function values = i_candidate_ids(multiplier, nCandidates)
values = compose("MC_M%06d_C%04d", round(1000 * multiplier), ...
    (1:nCandidates)');
end

function value = i_membership_stage(params)
if params.run_mode == "full"
    value = "locked_graph_partition_pre_annotation";
else
    value = "provisional_full_graph_pilot";
end
end
