function Postfit = build_run09_postfit_candidate_audits( ...
        repoRoot, outRoot, Validation, Adapter, Analysis, ...
        TopologyAudits, params)
%BUILD_RUN09_POSTFIT_CANDIDATE_AUDITS Build interpretation-only artifacts.
%
% Membership and graph-only eligibility must already be frozen. Scale and
% session composition, behavioral/event summaries, exemplars, and
% provisional annotations are downstream audits and cannot revise either.

repoRoot = string(repoRoot);
outRoot = string(outRoot);
membershipPath = fullfile(outRoot, params.node_membership_file);
membershipHashBefore = compute_file_sha256(membershipPath);
i_assert_membership_freeze(membershipHashBefore, params);

[Membership, candidateIds, candidateIndex] = ...
    i_align_membership(Adapter, Analysis, params);
Topology = i_align_topology(candidateIds, ...
    TopologyAudits.candidate_topology);
eligible = logical(Topology.eligible_for_behavioral_interpretation);

Session = i_load_session_metadata(repoRoot, Validation, Adapter, params);
ScaleAudit = i_composition_audit(candidateIds, candidateIndex, ...
    double(Session.scale_index), double(Session.chunk_sec), "scale", ...
    eligible, membershipHashBefore, params);
SessionAudit = i_composition_audit(candidateIds, candidateIndex, ...
    double(Session.session_index), string(Session.session_id), "session", ...
    eligible, membershipHashBefore, params);

[behaviorValues, behaviorMeta, behaviorSource] = ...
    i_load_behavior_matrix(repoRoot, Session, params);
BehaviorProfile = i_profile_table(candidateIds, candidateIndex, ...
    behaviorValues, behaviorMeta, "behavior", eligible, ...
    membershipHashBefore, params);

[eventValues, eventMeta, eventSource] = ...
    i_load_event_matrix(repoRoot, Session, params);
EventProfile = i_profile_table(candidateIds, candidateIndex, ...
    eventValues, eventMeta, "event", eligible, ...
    membershipHashBefore, params);

Exemplars = i_select_exemplars(Adapter, Membership, Session, ...
    candidateIds, candidateIndex, Analysis.node_ambiguity, ...
    eligible, membershipHashBefore, params);

sourcePaths = [ ...
    string(behaviorSource)
    string(eventSource)
    fullfile(Validation.input_root, ...
        params.postfit_graph_node_manifest_file)
    membershipPath
    fullfile(outRoot, params.candidate_topology_audit_file)
    string(params.config_path)];
sourceIds = [ ...
    "run07_condition_blind_summary_matrices"
    "run06_condition_blind_event_summaries"
    "run08_postfit_session_manifest"
    "frozen_candidate_membership"
    "graph_only_interpretation_eligibility"
    "frozen_postfit_rule_config"];
sourceHashes = strings(numel(sourcePaths), 1);
for i = 1:numel(sourcePaths)
    sourceHashes(i) = compute_file_sha256(sourcePaths(i));
end
Source = table(sourceIds, sourcePaths, sourceHashes, ...
    'VariableNames', {'source_id','source_path','sha256'});

[Annotation, AnnotationProvenance] = ...
    build_run09_provisional_candidate_annotations( ...
    BehaviorProfile, EventProfile, Topology, Source, ...
    membershipHashBefore, params);

membershipHashAfter = compute_file_sha256(membershipPath);
assert(membershipHashAfter == membershipHashBefore, ...
    'build_run09_postfit_candidate_audits:MembershipChanged', ...
    'A post-fit audit changed the frozen membership artifact.');
assert(all(Topology.candidate_id_retained) && ...
    ~any(Topology.postfreeze_merge_allowed) && ...
    ~any(Topology.postfreeze_split_allowed), ...
    'build_run09_postfit_candidate_audits:FreezePolicyChanged', ...
    'Post-fit work requires all candidate IDs and prohibits merges/splits.');

Postfit = struct();
Postfit.scale_composition = ScaleAudit;
Postfit.session_composition = SessionAudit;
Postfit.behavioral_profile = BehaviorProfile;
Postfit.event_profile = EventProfile;
Postfit.exemplar_manifest = Exemplars;
Postfit.annotation = Annotation;
Postfit.annotation_provenance = AnnotationProvenance;
Postfit.behavior_values = behaviorValues;
Postfit.event_values = eventValues;
Postfit.behavior_feature_names = string(behaviorMeta.feature_name);
Postfit.event_feature_names = string(eventMeta.feature_name);
Postfit.candidate_ids = candidateIds;
Postfit.candidate_index = candidateIndex;
Postfit.eligible = eligible;
Postfit.membership_sha256 = membershipHashBefore;
Postfit.sources = Source;
end

function i_assert_membership_freeze(hashValue, params)
if params.run_mode == "full"
    assert(hashValue == params.locked_candidate_membership_sha256, ...
        'build_run09_postfit_candidate_audits:MembershipFreezeMismatch', ...
        ['Post-fit audits are blocked because the byte-exact frozen ' ...
         'membership hash differs from config.']);
end
end

function [M, candidateIds, candidateIndex] = ...
        i_align_membership(Adapter, Analysis, params)
M = Analysis.node_membership;
if params.run_mode == "smoke"
    assert(params.postfit_smoke_resolution_rule == ...
        "lowest_configured_cpm_resolution_schema_audit_only" && ...
        isfield(Analysis, 'resolution_sensitivity'), ...
        'build_run09_postfit_candidate_audits:BadSmokeResolutionRule', ...
        'Smoke post-fit schema audits require the predeclared resolution rule.');
    [~, row] = min(Analysis.resolution_sensitivity.resolution);
    smokeResolutionId = string( ...
        Analysis.resolution_sensitivity.resolution_id(row));
    M = M(string(M.resolution_id) == smokeResolutionId, :);
end
assert(height(M) == numel(Adapter.node_ids) && ...
    numel(unique(M.graph_node_id)) == height(M), ...
    'build_run09_postfit_candidate_audits:BadMembershipCardinality', ...
    'Post-fit work requires exactly one frozen candidate per graph node.');
[tf, loc] = ismember(Adapter.node_ids, double(M.graph_node_id));
assert(all(tf), ...
    'build_run09_postfit_candidate_audits:MissingMembershipNode', ...
    'Every adapted graph node must have one frozen membership.');
M = M(loc, :);
candidateIds = unique(string(M.motif_candidate_id), 'sorted');
[tf, candidateIndex] = ismember(string(M.motif_candidate_id), ...
    candidateIds);
assert(all(tf), ...
    'build_run09_postfit_candidate_audits:BadCandidateId', ...
    'Candidate IDs could not be indexed deterministically.');
candidateIndex = double(candidateIndex);
end

function T = i_align_topology(candidateIds, topology)
[tf, loc] = ismember(candidateIds, ...
    string(topology.motif_candidate_id));
assert(all(tf) && numel(unique(topology.motif_candidate_id)) == ...
    height(topology), ...
    'build_run09_postfit_candidate_audits:BadTopologyJoin', ...
    'Graph-only topology eligibility must match every frozen candidate.');
T = topology(loc, :);
end

function Session = i_load_session_metadata( ...
        repoRoot, Validation, Adapter, params)
pathText = fullfile(Validation.input_root, ...
    params.postfit_graph_node_manifest_file);
names = [ ...
    "graph_node_id", "embedding_row_id", "scale_index", "chunk_sec", ...
    "session_index", "session_id", "raw_index", "anchor_frame", ...
    "anchor_time_s", "expanded_anchor_global_id", ...
    "labels_used_for_consensus", "arena_used_for_consensus", ...
    "condition_used_for_consensus"];
Session = i_read_selected(pathText, names);
[tf, loc] = ismember(Adapter.node_ids, double(Session.graph_node_id));
assert(all(tf) && numel(unique(Session.graph_node_id)) == ...
    height(Session), ...
    'build_run09_postfit_candidate_audits:BadSessionJoin', ...
    'The post-fit session manifest must uniquely cover frozen nodes.');
Session = Session(loc, :);
assert(all(string(Session.labels_used_for_consensus) == "none") && ...
    ~any(i_logical(Session.arena_used_for_consensus)) && ...
    ~any(i_logical(Session.condition_used_for_consensus)), ...
    'build_run09_postfit_candidate_audits:NonblindSessionSource', ...
    'Run_08 session provenance must come from a label-free consensus graph.');
assert(isequal(double(Session.scale_index), ...
    double(Validation.nodes.scale_index)), ...
    'build_run09_postfit_candidate_audits:ScaleProvenanceMismatch', ...
    'Post-fit scale provenance differs from the frozen node input.');
end

function Audit = i_composition_audit(candidateIds, candidateIndex, ...
        categoryIndex, categoryLabel, categoryType, eligible, ...
        membershipHash, params)
categories = unique(categoryIndex, 'sorted');
nCandidate = numel(candidateIds);
nCategory = numel(categories);
n = numel(candidateIndex);
candidateCounts = accumarray(candidateIndex, 1, [nCandidate 1]);
[~, categoryLoc] = ismember(categoryIndex, categories);
overallCounts = accumarray(categoryLoc, 1, [nCategory 1]);

candidateId = strings(nCandidate * nCategory, 1);
categoryValue = zeros(nCandidate * nCategory, 1);
categoryText = strings(nCandidate * nCategory, 1);
nodeCount = zeros(nCandidate * nCategory, 1);
candidateFraction = zeros(nCandidate * nCategory, 1);
overallNodeCount = zeros(nCandidate * nCategory, 1);
overallFraction = zeros(nCandidate * nCategory, 1);
expectedNodeCount = zeros(nCandidate * nCategory, 1);
enrichmentRatio = zeros(nCandidate * nCategory, 1);
mixingEntropy = zeros(nCandidate * nCategory, 1);
effectiveCategories = zeros(nCandidate * nCategory, 1);
representedCategories = zeros(nCandidate * nCategory, 1);
eligibleColumn = false(nCandidate * nCategory, 1);

cursor = 0;
for c = 1:nCandidate
    counts = accumarray(categoryLoc(candidateIndex == c), 1, ...
        [nCategory 1]);
    p = counts ./ candidateCounts(c);
    positive = p > 0;
    rawEntropy = -sum(p(positive) .* log(p(positive)));
    if nCategory > 1
        normalizedEntropy = rawEntropy / log(nCategory);
    else
        normalizedEntropy = 0;
    end
    for k = 1:nCategory
        cursor = cursor + 1;
        candidateId(cursor) = candidateIds(c);
        categoryValue(cursor) = categories(k);
        if isstring(categoryLabel)
            row = find(categoryIndex == categories(k), 1);
            categoryText(cursor) = categoryLabel(row);
        else
            row = find(categoryIndex == categories(k), 1);
            categoryText(cursor) = compose('%.17g', ...
                double(categoryLabel(row)));
        end
        nodeCount(cursor) = counts(k);
        candidateFraction(cursor) = p(k);
        overallNodeCount(cursor) = overallCounts(k);
        overallFraction(cursor) = overallCounts(k) / n;
        expectedNodeCount(cursor) = ...
            candidateCounts(c) * overallFraction(cursor);
        enrichmentRatio(cursor) = candidateFraction(cursor) / ...
            overallFraction(cursor);
        mixingEntropy(cursor) = normalizedEntropy;
        effectiveCategories(cursor) = exp(rawEntropy);
        representedCategories(cursor) = nnz(positive);
        eligibleColumn(cursor) = eligible(c);
    end
end

Audit = table(candidateId, repmat(categoryType, cursor, 1), ...
    categoryValue, categoryText, nodeCount, candidateFraction, ...
    overallNodeCount, overallFraction, expectedNodeCount, ...
    enrichmentRatio, mixingEntropy, effectiveCategories, ...
    representedCategories, eligibleColumn, ...
    repmat(false, cursor, 1), repmat(false, cursor, 1), ...
    repmat(string(membershipHash), cursor, 1), ...
    repmat(string(params.postfit_rule_version), cursor, 1), ...
    repmat("none", cursor, 1), ...
    'VariableNames', { ...
    'motif_candidate_id','composition_dimension','category_index', ...
    'category_label','node_count','candidate_fraction', ...
    'overall_node_count','overall_fraction','expected_node_count', ...
    'enrichment_ratio','normalized_mixing_entropy', ...
    'effective_category_count','represented_category_count', ...
    'eligible_for_behavioral_interpretation', ...
    'used_for_membership','used_for_interpretation_eligibility', ...
    'frozen_membership_sha256','postfit_rule_version', ...
    'experimental_labels_used'});
end

function [X, Meta, sourcePath] = ...
        i_load_behavior_matrix(repoRoot, Session, params)
sourcePath = resolve_repo_path(repoRoot, ...
    fullfile(params.postfit_embedding_input_dir, ...
    params.postfit_summary_matrix_mat_file));
S = load(sourcePath, 'Input');
Input = S.Input;
assert(string(Input.labels_used_for_matrix) == "none" && ...
    ~logical(Input.arena_used_for_matrix) && ...
    ~logical(Input.condition_used_for_matrix), ...
    'build_run09_postfit_candidate_audits:NonblindBehaviorSource', ...
    'Run_07 summary matrices must declare a condition-blind fit.');

featureNames = strings(0, 1);
featureFamily = strings(0, 1);
featureUnit = strings(0, 1);
for s = 1:numel(Input.scale)
    D = Input.scale(s).dimMeta;
    keep = string(D.summary_kind) == ...
        params.behavior_profile_summary_kind & ...
        string(D.source_tensor) == ...
        params.behavior_profile_source_tensor;
    if isempty(featureNames)
        featureNames = string(D.obs_name(keep));
        featureFamily = string(D.feature_family(keep));
        featureUnit = string(D.unit(keep));
        assert(numel(unique(featureNames)) == numel(featureNames), ...
            'build_run09_postfit_candidate_audits:DuplicateBehaviorFeature', ...
            'Behavioral profile feature names must be unique within scale.');
    end
end
assert(~isempty(featureNames), ...
    'build_run09_postfit_candidate_audits:NoBehaviorFeatures', ...
    'No predeclared condition-blind behavioral mean dimensions were found.');

n = height(Session);
X = nan(n, numel(featureNames));
filled = false(n, 1);
embeddingIds = double(Session.embedding_row_id);
for s = 1:numel(Input.scale)
    Sc = Input.scale(s);
    D = Sc.dimMeta;
    keep = string(D.summary_kind) == ...
        params.behavior_profile_summary_kind & ...
        string(D.source_tensor) == ...
        params.behavior_profile_source_tensor;
    namesHere = string(D.obs_name(keep));
    [featurePresent, featureLoc] = ismember(featureNames, namesHere);
    assert(all(featurePresent), ...
        'build_run09_postfit_candidate_audits:BehaviorFeatureDrift', ...
        'Every scale must expose the same predeclared mean behavior channels.');
    columns = find(keep);
    columns = columns(featureLoc);
    rowIds = double(Sc.rowMeta.embedding_row_id);
    [isFrozen, nodeLoc] = ismember(rowIds, embeddingIds);
    assert(~any(filled(nodeLoc(isFrozen))), ...
        'build_run09_postfit_candidate_audits:DuplicateBehaviorRow', ...
        'A frozen node matched multiple run_07 summary rows.');
    X(nodeLoc(isFrozen), :) = double(Sc.X(isFrozen, columns));
    filled(nodeLoc(isFrozen)) = true;
end
assert(all(filled), ...
    'build_run09_postfit_candidate_audits:MissingBehaviorRow', ...
    'Every frozen graph node must match one run_07 summary row.');
Meta = table(featureNames, featureFamily, featureUnit, ...
    repmat(params.behavior_profile_summary_kind, numel(featureNames), 1), ...
    repmat(params.behavior_profile_source_tensor, ...
    numel(featureNames), 1), ...
    'VariableNames', {'feature_name','feature_family','unit', ...
    'summary_kind','source_tensor'});
end

function [X, Meta, sourcePath] = ...
        i_load_event_matrix(repoRoot, Session, params)
sourcePath = resolve_repo_path(repoRoot, ...
    fullfile(params.postfit_event_input_dir, ...
    params.postfit_event_summary_file));
featureNames = strip(string(split( ...
    params.event_profile_feature_names, ';')));
featureNames = featureNames(featureNames ~= "");
names = [ ...
    "expanded_anchor_global_id", "labels_used_for_event_summary", ...
    "arena_used_for_event_summary", ...
    "condition_used_for_event_summary", featureNames(:)'];
E = i_read_selected(sourcePath, names);
assert(all(string(E.labels_used_for_event_summary) == "none") && ...
    ~any(i_logical(E.arena_used_for_event_summary)) && ...
    ~any(i_logical(E.condition_used_for_event_summary)), ...
    'build_run09_postfit_candidate_audits:NonblindEventSource', ...
    'Run_06 event summaries must declare label-free construction.');
assert(numel(unique(E.expanded_anchor_global_id)) == height(E), ...
    'build_run09_postfit_candidate_audits:DuplicateEventKey', ...
    'expanded_anchor_global_id must uniquely identify event summaries.');
[tf, loc] = ismember(double(Session.expanded_anchor_global_id), ...
    double(E.expanded_anchor_global_id));
assert(all(tf), ...
    'build_run09_postfit_candidate_audits:MissingEventRow', ...
    'Every frozen node must match one condition-blind event summary.');
X = zeros(height(Session), numel(featureNames));
for j = 1:numel(featureNames)
    X(:, j) = double(E.(featureNames(j))(loc));
end
Meta = table(featureNames, repmat("event_summary", ...
    numel(featureNames), 1), i_event_units(featureNames), ...
    repmat("condition_blind_event_summary", ...
    numel(featureNames), 1), ...
    repmat("run06_condition_blind_chunk_event_summary_audit", ...
    numel(featureNames), 1), ...
    'VariableNames', {'feature_name','feature_family','unit', ...
    'summary_kind','source_tensor'});
end

function Profile = i_profile_table(candidateIds, candidateIndex, ...
        X, Meta, profileType, eligible, membershipHash, params)
nCandidate = numel(candidateIds);
nFeature = width(X);
nRows = nCandidate * nFeature;
candidateId = strings(nRows, 1);
profileKind = repmat(profileType, nRows, 1);
featureName = strings(nRows, 1);
featureFamily = strings(nRows, 1);
unit = strings(nRows, 1);
candidateNodeCount = zeros(nRows, 1);
nFinite = zeros(nRows, 1);
finiteFraction = zeros(nRows, 1);
candidateMean = zeros(nRows, 1);
candidateMedian = zeros(nRows, 1);
candidateStd = zeros(nRows, 1);
candidateQ10 = zeros(nRows, 1);
candidateQ90 = zeros(nRows, 1);
globalMean = zeros(nRows, 1);
globalMedian = zeros(nRows, 1);
globalStd = zeros(nRows, 1);
standardizedMeanDifference = zeros(nRows, 1);
summaryStatus = strings(nRows, 1);
eligibleColumn = false(nRows, 1);

cursor = 0;
for f = 1:nFeature
    globalValues = X(:, f);
    globalValues = globalValues(isfinite(globalValues));
    assert(~isempty(globalValues), ...
        'build_run09_postfit_candidate_audits:EmptyGlobalProfile', ...
        'A predeclared post-fit feature has no finite observations.');
    gMean = mean(globalValues);
    gMedian = median(globalValues);
    gStd = std(globalValues, 0);
    if ~(isfinite(gStd) && gStd > 0)
        gStd = 0;
    end
    for c = 1:nCandidate
        cursor = cursor + 1;
        values = X(candidateIndex == c, f);
        finiteValues = values(isfinite(values));
        candidateId(cursor) = candidateIds(c);
        featureName(cursor) = string(Meta.feature_name(f));
        featureFamily(cursor) = string(Meta.feature_family(f));
        unit(cursor) = string(Meta.unit(f));
        candidateNodeCount(cursor) = numel(values);
        nFinite(cursor) = numel(finiteValues);
        finiteFraction(cursor) = nFinite(cursor) / ...
            candidateNodeCount(cursor);
        globalMean(cursor) = gMean;
        globalMedian(cursor) = gMedian;
        globalStd(cursor) = gStd;
        eligibleColumn(cursor) = eligible(c);
        if isempty(finiteValues)
            candidateMean(cursor) = gMedian;
            candidateMedian(cursor) = gMedian;
            candidateStd(cursor) = 0;
            candidateQ10(cursor) = gMedian;
            candidateQ90(cursor) = gMedian;
            standardizedMeanDifference(cursor) = 0;
            summaryStatus(cursor) = ...
                "no_finite_values_global_median_fallback";
        else
            candidateMean(cursor) = mean(finiteValues);
            candidateMedian(cursor) = median(finiteValues);
            candidateStd(cursor) = std(finiteValues, 0);
            candidateQ10(cursor) = prctile(finiteValues, 10);
            candidateQ90(cursor) = prctile(finiteValues, 90);
            if gStd > 0
                standardizedMeanDifference(cursor) = ...
                    (candidateMean(cursor) - gMean) / gStd;
            else
                standardizedMeanDifference(cursor) = 0;
            end
            if numel(finiteValues) == numel(values)
                summaryStatus(cursor) = "complete_finite";
            else
                summaryStatus(cursor) = "partial_finite";
            end
        end
    end
end

Profile = table(candidateId, profileKind, featureName, ...
    featureFamily, unit, candidateNodeCount, nFinite, finiteFraction, ...
    candidateMean, candidateMedian, candidateStd, candidateQ10, ...
    candidateQ90, globalMean, globalMedian, globalStd, ...
    standardizedMeanDifference, summaryStatus, eligibleColumn, ...
    repmat(false, nRows, 1), repmat(false, nRows, 1), ...
    repmat(string(membershipHash), nRows, 1), ...
    repmat(string(params.postfit_rule_version), nRows, 1), ...
    repmat("none", nRows, 1), ...
    'VariableNames', { ...
    'motif_candidate_id','profile_type','feature_name', ...
    'feature_family','unit','candidate_node_count','n_finite', ...
    'finite_fraction','candidate_mean','candidate_median', ...
    'candidate_std','candidate_q10','candidate_q90','global_mean', ...
    'global_median','global_std','standardized_mean_difference', ...
    'summary_status','eligible_for_behavioral_interpretation', ...
    'used_for_membership','used_for_interpretation_eligibility', ...
    'frozen_membership_sha256','postfit_rule_version', ...
    'experimental_labels_used'});
assert(all(isfinite(Profile{:, vartype('numeric')}), 'all'), ...
    'build_run09_postfit_candidate_audits:NonfiniteProfileMetric', ...
    'Post-fit profile metrics must be finite after the declared fallback.');
end

function Exemplars = i_select_exemplars(Adapter, Membership, Session, ...
        candidateIds, candidateIndex, Ambiguity, eligible, ...
        membershipHash, params)
resolutionIds = unique(string(Membership.resolution_id));
assert(numel(resolutionIds) == 1, ...
    'build_run09_postfit_candidate_audits:NonexclusiveExemplarResolution', ...
    'Exemplar selection requires one full-graph partition at a time.');
Ambiguity = Ambiguity(string(Ambiguity.resolution_id) == ...
    resolutionIds, :);
[tf, ambiguityLoc] = ismember(Adapter.node_ids, ...
    double(Ambiguity.graph_node_id));
assert(all(tf), ...
    'build_run09_postfit_candidate_audits:MissingAmbiguityNode', ...
    'Every frozen node must have a node-stability audit row.');
stability = double(Ambiguity.coassignment_jaccard_mean(ambiguityLoc));
same = candidateIndex(Adapter.source_index) == ...
    candidateIndex(Adapter.target_index);
internalWeightedDegree = accumarray( ...
    [Adapter.source_index(same); Adapter.target_index(same)], ...
    [Adapter.weights(same); Adapter.weights(same)], ...
    [numel(Adapter.node_ids), 1], @sum, 0);
internalWeightedDegreeShare = internalWeightedDegree ./ ...
    Adapter.weighted_degree;

candidateId = strings(0, 1);
exemplarRank = zeros(0, 1);
graphNodeId = zeros(0, 1);
exemplarScore = zeros(0, 1);
nodeStability = zeros(0, 1);
centralityPercentile = zeros(0, 1);
internalDegree = zeros(0, 1);
internalDegreeShare = zeros(0, 1);
totalWeightedDegree = zeros(0, 1);
eligibleColumn = false(0, 1);
embeddingRowId = zeros(0, 1);
scaleIndex = zeros(0, 1);
chunkSec = zeros(0, 1);
sessionIndex = zeros(0, 1);
sessionId = strings(0, 1);
rawIndex = zeros(0, 1);
anchorFrame = zeros(0, 1);
anchorTime = zeros(0, 1);

for c = 1:numel(candidateIds)
    idx = find(candidateIndex == c);
    if numel(idx) == 1
        percentile = 1;
    else
        percentile = (tiedrank(internalWeightedDegree(idx)) - 1) ./ ...
            (numel(idx) - 1);
    end
    score = params.exemplar_stability_weight .* stability(idx) + ...
        params.exemplar_centrality_weight .* percentile;
    Order = table(idx, score, stability(idx), ...
        internalWeightedDegree(idx), Adapter.node_ids(idx), ...
        'VariableNames', {'node_index','score','stability', ...
        'internal_weighted_degree','graph_node_id'});
    Order = sortrows(Order, ...
        {'score','stability','internal_weighted_degree','graph_node_id'}, ...
        {'descend','descend','descend','ascend'});
    take = min(params.exemplar_count_per_candidate, height(Order));
    chosen = Order.node_index(1:take);
    chosenPercentile = percentile( ...
        ismember(idx, chosen));
    [~, restore] = ismember(chosen, idx);
    chosenPercentile = percentile(restore);

    candidateId = [candidateId; repmat(candidateIds(c), take, 1)]; %#ok<AGROW>
    exemplarRank = [exemplarRank; (1:take)']; %#ok<AGROW>
    graphNodeId = [graphNodeId; Adapter.node_ids(chosen)]; %#ok<AGROW>
    exemplarScore = [exemplarScore; Order.score(1:take)]; %#ok<AGROW>
    nodeStability = [nodeStability; stability(chosen)]; %#ok<AGROW>
    centralityPercentile = [centralityPercentile; chosenPercentile]; %#ok<AGROW>
    internalDegree = [internalDegree; internalWeightedDegree(chosen)]; %#ok<AGROW>
    internalDegreeShare = [internalDegreeShare; ...
        internalWeightedDegreeShare(chosen)]; %#ok<AGROW>
    totalWeightedDegree = [totalWeightedDegree; ...
        Adapter.weighted_degree(chosen)]; %#ok<AGROW>
    eligibleColumn = [eligibleColumn; repmat(eligible(c), take, 1)]; %#ok<AGROW>
    embeddingRowId = [embeddingRowId; ...
        double(Session.embedding_row_id(chosen))]; %#ok<AGROW>
    scaleIndex = [scaleIndex; double(Session.scale_index(chosen))]; %#ok<AGROW>
    chunkSec = [chunkSec; double(Session.chunk_sec(chosen))]; %#ok<AGROW>
    sessionIndex = [sessionIndex; ...
        double(Session.session_index(chosen))]; %#ok<AGROW>
    sessionId = [sessionId; string(Session.session_id(chosen))]; %#ok<AGROW>
    rawIndex = [rawIndex; double(Session.raw_index(chosen))]; %#ok<AGROW>
    anchorFrame = [anchorFrame; ...
        double(Session.anchor_frame(chosen))]; %#ok<AGROW>
    anchorTime = [anchorTime; ...
        double(Session.anchor_time_s(chosen))]; %#ok<AGROW>
end

n = numel(graphNodeId);
Exemplars = table(candidateId, exemplarRank, graphNodeId, ...
    exemplarScore, nodeStability, centralityPercentile, ...
    internalDegree, internalDegreeShare, totalWeightedDegree, ...
    eligibleColumn, embeddingRowId, scaleIndex, chunkSec, ...
    sessionIndex, sessionId, rawIndex, anchorFrame, anchorTime, ...
    repmat(params.exemplar_selection_rule, n, 1), ...
    repmat("graph_node_id;frozen_candidate_id;coassignment_jaccard_mean;internal_weighted_degree", n, 1), ...
    repmat("scale;session;anchor_metadata_attached_after_selection", n, 1), ...
    repmat(false, n, 1), repmat(false, n, 1), ...
    repmat(string(membershipHash), n, 1), ...
    repmat("none", n, 1), ...
    'VariableNames', { ...
    'motif_candidate_id','exemplar_rank','graph_node_id', ...
    'exemplar_score','node_stability','centrality_percentile', ...
    'internal_weighted_degree','internal_weighted_degree_share', ...
    'total_weighted_degree','eligible_for_behavioral_interpretation', ...
    'embedding_row_id','scale_index','chunk_sec','session_index', ...
    'session_id','raw_index','anchor_frame','anchor_time_s', ...
    'exemplar_selection_rule','selection_fields_used', ...
    'postfit_metadata_not_used_for_selection','used_for_membership', ...
    'used_for_interpretation_eligibility','frozen_membership_sha256', ...
    'experimental_labels_used'});
assert(all(isfinite(Exemplars{:, vartype('numeric')}), 'all'), ...
    'build_run09_postfit_candidate_audits:NonfiniteExemplarMetric', ...
    'Exemplar ranks and graph scores must be finite.');
assert(numel(unique(Exemplars.graph_node_id)) == height(Exemplars), ...
    'build_run09_postfit_candidate_audits:DuplicateExemplar', ...
    'A graph node may be selected once because membership is exclusive.');
end

function units = i_event_units(names)
units = repmat("unitless", numel(names), 1);
for i = 1:numel(names)
    if endsWith(names(i), "_mm")
        units(i) = "mm";
    elseif endsWith(names(i), "_mm_s")
        units(i) = "mm_per_s";
    elseif contains(names(i), "latency") || contains(names(i), "duration")
        units(i) = "s";
    elseif contains(names(i), "deg")
        units(i) = "degrees";
    elseif contains(names(i), "count")
        units(i) = "count";
    elseif contains(names(i), "fraction")
        units(i) = "fraction";
    end
end
end

function T = i_read_selected(pathText, selectedNames)
opts = detectImportOptions(pathText, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
opts.DataLines = [2 Inf];
opts.VariableNamesLine = 1;
opts.VariableUnitsLine = 0;
missing = setdiff(selectedNames, string(opts.VariableNames));
assert(isempty(missing), ...
    'build_run09_postfit_candidate_audits:MissingSourceColumn', ...
    'Post-fit source %s is missing: %s', pathText, ...
    strjoin(missing, ', '));
opts.SelectedVariableNames = cellstr(selectedNames);
T = readtable(pathText, opts);
end

function values = i_logical(valuesIn)
if islogical(valuesIn)
    values = valuesIn;
elseif isnumeric(valuesIn)
    values = valuesIn ~= 0;
else
    text = lower(strip(string(valuesIn)));
    assert(all(ismember(text, ...
        ["0","1","false","true","no","yes"])), ...
        'build_run09_postfit_candidate_audits:BadLogical', ...
        'A post-fit provenance flag is not logical-like.');
    values = ismember(text, ["1","true","yes"]);
end
values = logical(values);
end
