function Audits = build_run09_candidate_topology_audits( ...
        Adapter, Analysis, Ensemble, params)
%BUILD_RUN09_CANDIDATE_TOPOLOGY_AUDITS Frozen-graph post-partition audits.
%
% This function reads only frozen endpoints, frozen weights, graph-derived
% memberships, and graph-derived stability values. Interpretation eligibility
% is an audit status: it cannot merge, split, delete, or reassign a candidate.
% The weighted modularity challenger remains audit-only and cannot replace the
% retained CPM partition.

nNodes = numel(Adapter.node_ids);
assert(size(Analysis.reference_memberships, 1) == nNodes && ...
    width(Analysis.reference_memberships) == ...
    numel(Analysis.resolution_ids), ...
    'build_run09_candidate_topology_audits:BadReferenceDimensions', ...
    'Frozen reference memberships must match the adapted graph.');
assert(size(Ensemble.memberships, 1) == nNodes && ...
    size(Ensemble.memberships, 2) == height(Ensemble.replicate_audit), ...
    'build_run09_candidate_topology_audits:BadEnsembleDimensions', ...
    'Ensemble memberships must match the replicate audit and graph.');

nLevels = numel(Analysis.resolution_ids);
candidateRows = cell(nLevels, 1);
objectiveRows = cell(nLevels, 1);
for level = 1:nLevels
    resolutionId = Analysis.resolution_ids(level);
    labels = uint32(Analysis.reference_memberships(:, level));
    Definition = Analysis.candidate_definition( ...
        Analysis.candidate_definition.resolution_id == resolutionId, :);
    Definition = sortrows(Definition, 'candidate_local_index');
    candidateCount = double(max(labels));
    assert(height(Definition) == candidateCount && ...
        isequal(double(Definition.candidate_local_index), ...
        (1:candidateCount)'), ...
        'build_run09_candidate_topology_audits:DefinitionMismatch', ...
        'Candidate definitions do not align with canonical memberships.');

    Topology = i_partition_topology( ...
        Adapter, labels, Definition.motif_candidate_id);
    Topology.resolution_id = repmat(resolutionId, candidateCount, 1);
    Topology.hierarchy_level = repmat(level, candidateCount, 1);
    Topology = movevars(Topology, ...
        {'resolution_id','hierarchy_level'}, 'After', 'motif_candidate_id');
    Topology.mean_node_stability = Definition.mean_node_stability;
    Topology.minimum_node_stability = Definition.minimum_node_stability;
    Topology.boundary_node_fraction = Definition.boundary_node_fraction;
    Topology.membership_status = Definition.membership_status;
    Topology = i_add_interpretation_eligibility(Topology, params);
    candidateRows{level} = Topology;

    objectiveRows{level} = i_objective_comparison( ...
        Adapter, labels, resolutionId, ...
        Analysis.resolution_sensitivity.resolution( ...
        Analysis.resolution_sensitivity.resolution_id == resolutionId), ...
        Analysis.reference_replicate_ids(level), ...
        Ensemble, Analysis.partition_stability, params);
end

if isempty(candidateRows)
    CandidateTopology = table();
    ObjectiveConcordance = table();
else
    CandidateTopology = vertcat(candidateRows{:});
    ObjectiveConcordance = vertcat(objectiveRows{:});
end

assert(all(CandidateTopology.candidate_id_retained) && ...
    ~any(CandidateTopology.postfreeze_merge_allowed) && ...
    ~any(CandidateTopology.postfreeze_split_allowed), ...
    'build_run09_candidate_topology_audits:MembershipPolicyViolation', ...
    'Topology audits may not delete merge or split frozen candidate IDs.');
numericTopology = CandidateTopology{:, vartype('numeric')};
assert(all(isfinite(numericTopology), 'all'), ...
    'build_run09_candidate_topology_audits:NonfiniteTopology', ...
    'Every candidate topology and eligibility metric must be finite.');
numericObjective = ObjectiveConcordance{:, vartype('numeric')};
assert(all(isfinite(numericObjective), 'all'), ...
    'build_run09_candidate_topology_audits:NonfiniteObjectiveAudit', ...
    'Every objective concordance and topology metric must be finite.');

Audits = struct();
Audits.candidate_topology = CandidateTopology;
Audits.objective_concordance = ObjectiveConcordance;
end

function T = i_partition_topology(Adapter, labels, candidateIds)
labels = double(canonicalize_run09_membership(labels));
n = numel(labels);
k = max(labels);
assert(numel(candidateIds) == k, ...
    'build_run09_candidate_topology_audits:CandidateIdMismatch', ...
    'Exactly one candidate ID is required per canonical label.');
s = double(Adapter.source_index);
t = double(Adapter.target_index);
w = double(Adapter.weights);
internal = labels(s) == labels(t);
internalS = s(internal);
internalT = t(internal);
internalW = w(internal);
cut = ~internal;
cutS = s(cut);
cutT = t(cut);
cutW = w(cut);

nodeCount = accumarray(labels, 1, [k 1]);
prevalence = nodeCount / n;
internalEdgeCount = accumarray(labels(internalS), 1, [k 1]);
internalWeight = accumarray(labels(internalS), internalW, [k 1]);
cutEdgeCount = accumarray( ...
    [labels(cutS); labels(cutT)], 1, [k 1]);
cutWeight = accumarray( ...
    [labels(cutS); labels(cutT)], [cutW; cutW], [k 1]);
unweightedVolume = accumarray(labels, double(Adapter.degree), [k 1]);
weightedVolume = accumarray( ...
    labels, double(Adapter.weighted_degree), [k 1]);
totalUnweightedVolume = sum(unweightedVolume);
totalWeightedVolume = sum(weightedVolume);
unweightedDenominator = min(unweightedVolume, ...
    totalUnweightedVolume - unweightedVolume);
weightedDenominator = min(weightedVolume, ...
    totalWeightedVolume - weightedVolume);
unweightedConductance = i_safe_ratio( ...
    cutEdgeCount, unweightedDenominator);
weightedConductance = i_safe_ratio(cutWeight, weightedDenominator);

possibleInternalEdges = nodeCount .* (nodeCount - 1) / 2;
internalEdgeDensity = i_safe_ratio( ...
    internalEdgeCount, possibleInternalEdges);
internalWeightDensity = i_safe_ratio( ...
    internalWeight, possibleInternalEdges);
meanInternalEdgeWeight = i_safe_ratio( ...
    internalWeight, internalEdgeCount);
internalDegree = accumarray( ...
    [internalS; internalT], 1, [n 1]);
internalWeightedDegree = accumarray( ...
    [internalS; internalT], [internalW; internalW], [n 1]);

meanTotalDegree = accumarray(labels, ...
    double(Adapter.degree), [k 1], @mean);
minimumTotalDegree = accumarray(labels, ...
    double(Adapter.degree), [k 1], @min);
maximumTotalDegree = accumarray(labels, ...
    double(Adapter.degree), [k 1], @max);
meanWeightedDegree = accumarray(labels, ...
    double(Adapter.weighted_degree), [k 1], @mean);
minimumWeightedDegree = accumarray(labels, ...
    double(Adapter.weighted_degree), [k 1], @min);
maximumWeightedDegree = accumarray(labels, ...
    double(Adapter.weighted_degree), [k 1], @max);
meanInternalDegree = accumarray(labels, internalDegree, [k 1], @mean);
minimumInternalDegree = accumarray(labels, internalDegree, [k 1], @min);
maximumInternalDegree = accumarray(labels, internalDegree, [k 1], @max);
meanInternalWeightedDegree = accumarray( ...
    labels, internalWeightedDegree, [k 1], @mean);

internalGraph = graph(internalS, internalT, [], n);
component = conncomp(internalGraph, 'OutputForm', 'vector')';
componentSize = accumarray(component, 1);
componentCandidate = accumarray(component, labels, [], @min);
inducedComponentCount = accumarray(componentCandidate, 1, [k 1]);
largestComponentNodeCount = accumarray( ...
    componentCandidate, componentSize, [k 1], @max);
singletonComponentCount = accumarray( ...
    componentCandidate, double(componentSize == 1), [k 1]);
largestComponentFraction = largestComponentNodeCount ./ nodeCount;
fragmentedNodeFraction = 1 - largestComponentFraction;

T = table(string(candidateIds), (1:k)', nodeCount, prevalence, ...
    internalEdgeCount, internalWeight, ...
    internalEdgeCount / max(numel(w), 1), ...
    internalWeight / max(sum(w), eps), ...
    cutEdgeCount, cutWeight, unweightedVolume, weightedVolume, ...
    unweightedConductance, weightedConductance, ...
    internalEdgeDensity, internalWeightDensity, ...
    meanInternalEdgeWeight, meanTotalDegree, minimumTotalDegree, ...
    maximumTotalDegree, meanWeightedDegree, minimumWeightedDegree, ...
    maximumWeightedDegree, meanInternalDegree, ...
    minimumInternalDegree, maximumInternalDegree, ...
    meanInternalWeightedDegree, inducedComponentCount, ...
    largestComponentNodeCount, largestComponentFraction, ...
    singletonComponentCount, fragmentedNodeFraction, ...
    'VariableNames', {'motif_candidate_id','candidate_local_index', ...
    'node_count','node_prevalence','internal_edge_count', ...
    'internal_edge_weight','global_internal_edge_fraction', ...
    'global_internal_weight_fraction','cut_edge_count', ...
    'weighted_cut','unweighted_volume','weighted_volume', ...
    'unweighted_conductance','weighted_conductance', ...
    'internal_edge_density','internal_weight_density', ...
    'mean_internal_edge_weight','mean_total_degree', ...
    'minimum_total_degree','maximum_total_degree', ...
    'mean_weighted_degree','minimum_weighted_degree', ...
    'maximum_weighted_degree','mean_internal_degree', ...
    'minimum_internal_degree','maximum_internal_degree', ...
    'mean_internal_weighted_degree','induced_component_count', ...
    'largest_component_node_count','largest_component_fraction', ...
    'singleton_component_count','fragmented_node_fraction'});
end

function T = i_add_interpretation_eligibility(T, params)
n = height(T);
small = T.node_count <= ...
    params.interpretation_small_candidate_max_nodes;
stabilityWeak = T.mean_node_stability < ...
    params.interpretation_min_mean_node_stability;
boundaryHeavy = T.boundary_node_fraction >= ...
    params.interpretation_max_boundary_node_fraction;
topologyWeak = T.weighted_conductance > ...
    params.interpretation_max_weighted_conductance | ...
    T.largest_component_fraction < ...
    params.interpretation_min_largest_component_fraction | ...
    T.internal_edge_count < params.interpretation_min_internal_edge_count;
eligible = ~(small | stabilityWeak | boundaryHeavy | topologyWeak);
if params.run_mode ~= "full"
    eligible(:) = false;
end

status = repmat("eligible_for_behavioral_interpretation", n, 1);
reasons = repmat("", n, 1);
for i = 1:n
    thisReasons = strings(0, 1);
    if params.run_mode ~= "full"
        thisReasons(end + 1) = "smoke_partition_not_frozen"; %#ok<AGROW>
    end
    if small(i)
        thisReasons(end + 1) = "residual_small_candidate"; %#ok<AGROW>
    end
    if stabilityWeak(i)
        thisReasons(end + 1) = "mean_node_stability_below_rule"; %#ok<AGROW>
    end
    if boundaryHeavy(i)
        thisReasons(end + 1) = "boundary_heavy_candidate"; %#ok<AGROW>
    end
    if topologyWeak(i)
        thisReasons(end + 1) = "topologically_weak_candidate"; %#ok<AGROW>
    end
    if ~isempty(thisReasons)
        reasons(i) = strjoin(thisReasons, ";");
        if isscalar(thisReasons)
            status(i) = thisReasons(1);
        else
            status(i) = "multiple_graph_only_exclusions";
        end
    end
end

T.is_residual_small_candidate = small;
T.is_stability_weak_candidate = stabilityWeak;
T.is_boundary_heavy_candidate = boundaryHeavy;
T.is_topologically_weak_candidate = topologyWeak;
T.candidate_id_retained = repmat( ...
    logical(params.interpretation_retain_all_candidate_ids), n, 1);
T.postfreeze_merge_allowed = false(n, 1);
T.postfreeze_split_allowed = false(n, 1);
T.eligible_for_behavioral_interpretation = eligible;
T.interpretation_status = status;
T.interpretation_exclusion_reasons = reasons;
T.interpretation_eligibility_rule_version = repmat( ...
    params.interpretation_eligibility_rule_version, n, 1);
end

function T = i_objective_comparison(Adapter, reference, resolutionId, ...
        referenceResolution, referenceId, Ensemble, Pairwise, params)
Audit = Ensemble.replicate_audit;
modularityIndices = find(Audit.objective == "modularity");
rowCount = 1 + numel(modularityIndices);
rows = cell(rowCount, 1);
reference = uint32(canonicalize_run09_membership(reference));
referenceIds = compose("REF_C%04d", (1:double(max(reference)))');
referenceTopology = i_partition_topology( ...
    Adapter, reference, referenceIds);
referenceSummary = i_topology_summary(referenceTopology, params);
rows{1} = i_objective_row(resolutionId, referenceId, ...
    "frozen_primary_reference", "cpm", 0, referenceResolution, ...
    params.consensus_refinement_seed, reference, 1, 0, 0, 1, 1, 1, ...
    true, referenceSummary);

medoid = i_modularity_medoid_flags(Audit, Pairwise);
for j = 1:numel(modularityIndices)
    idx = modularityIndices(j);
    membership = uint32(Ensemble.memberships(:, idx));
    comparison = compute_run09_partition_comparison( ...
        reference, membership);
    [challengerPurity, referencePurity] = ...
        i_bidirectional_overlap_purity(reference, membership);
    candidateIds = compose("MOD_C%04d", ...
        (1:double(max(membership)))');
    topology = i_partition_topology(Adapter, membership, candidateIds);
    summary = i_topology_summary(topology, params);
    rows{j + 1} = i_objective_row(resolutionId, ...
        Audit.replicate_id(idx), "audit_only_modularity_challenger", ...
        Audit.objective(idx), Audit.resolution_index(idx), ...
        Audit.resolution(idx), Audit.seed(idx), membership, ...
        comparison.adjusted_rand_index, ...
        comparison.variation_of_information, ...
        comparison.normalized_variation_of_information, ...
        challengerPurity, referencePurity, ...
        medoid.mean_ari(idx), medoid.is_medoid(idx), summary);
end
T = vertcat(rows{:});
end

function row = i_objective_row(referenceResolutionId, partitionId, ...
        role, objective, resolutionIndex, resolution, seed, membership, ...
        ari, vi, nvi, challengerPurity, referencePurity, meanWithinAri, ...
        isMedoid, S)
row = table(string(referenceResolutionId), string(partitionId), ...
    string(role), string(objective), double(resolutionIndex), ...
    double(resolution), double(seed), double(max(membership)), ...
    compute_run09_membership_sha256(membership), double(ari), ...
    double(vi), double(nvi), double(challengerPurity), ...
    double(referencePurity), ...
    mean([challengerPurity referencePurity]), ...
    double(meanWithinAri), logical(isMedoid), ...
    S.singleton_candidate_count, S.singleton_node_fraction, ...
    S.small_candidate_count, S.small_candidate_node_fraction, ...
    S.internal_edge_fraction, S.internal_weight_fraction, ...
    S.node_weighted_mean_conductance, ...
    S.median_candidate_conductance, S.maximum_candidate_conductance, ...
    S.node_weighted_mean_internal_density, ...
    S.fragmented_candidate_count, S.fragmented_node_fraction, ...
    S.topologically_weak_candidate_count, ...
    S.topologically_weak_node_fraction, ...
    'VariableNames', {'reference_cpm_resolution_id','partition_id', ...
    'analysis_role','objective','resolution_index','resolution','seed', ...
    'candidate_count','membership_sha256', ...
    'adjusted_rand_index_to_retained_cpm', ...
    'variation_of_information_to_retained_cpm', ...
    'normalized_variation_of_information_to_retained_cpm', ...
    'challenger_to_cpm_weighted_purity', ...
    'cpm_to_challenger_weighted_purity', ...
    'bidirectional_mean_weighted_purity', ...
    'mean_within_objective_ari','is_within_resolution_ari_medoid', ...
    'singleton_candidate_count','singleton_node_fraction', ...
    'small_candidate_count','small_candidate_node_fraction', ...
    'internal_edge_fraction','internal_weight_fraction', ...
    'node_weighted_mean_conductance', ...
    'median_candidate_conductance','maximum_candidate_conductance', ...
    'node_weighted_mean_internal_density', ...
    'fragmented_candidate_count','fragmented_node_fraction', ...
    'topologically_weak_candidate_count', ...
    'topologically_weak_node_fraction'});
end

function S = i_topology_summary(T, params)
n = sum(T.node_count);
small = T.node_count <= ...
    params.interpretation_small_candidate_max_nodes;
weak = T.weighted_conductance > ...
    params.interpretation_max_weighted_conductance | ...
    T.largest_component_fraction < ...
    params.interpretation_min_largest_component_fraction | ...
    T.internal_edge_count < params.interpretation_min_internal_edge_count;
fragmented = T.induced_component_count > 1;
S = struct();
S.singleton_candidate_count = nnz(T.node_count == 1);
S.singleton_node_fraction = sum(T.node_count(T.node_count == 1)) / n;
S.small_candidate_count = nnz(small);
S.small_candidate_node_fraction = sum(T.node_count(small)) / n;
S.internal_edge_fraction = sum(T.global_internal_edge_fraction);
S.internal_weight_fraction = sum(T.global_internal_weight_fraction);
S.node_weighted_mean_conductance = ...
    sum(T.node_count .* T.weighted_conductance) / n;
S.median_candidate_conductance = median(T.weighted_conductance);
S.maximum_candidate_conductance = max(T.weighted_conductance);
S.node_weighted_mean_internal_density = ...
    sum(T.node_count .* T.internal_edge_density) / n;
S.fragmented_candidate_count = nnz(fragmented);
S.fragmented_node_fraction = sum(T.node_count(fragmented)) / n;
S.topologically_weak_candidate_count = nnz(weak);
S.topologically_weak_node_fraction = sum(T.node_count(weak)) / n;
end

function M = i_modularity_medoid_flags(Audit, Pairwise)
n = height(Audit);
meanAri = nan(n, 1);
isMedoid = false(n, 1);
resolutionIndices = unique( ...
    Audit.resolution_index(Audit.objective == "modularity"), 'sorted');
for g = 1:numel(resolutionIndices)
    idx = find(Audit.objective == "modularity" & ...
        Audit.resolution_index == resolutionIndices(g));
    for j = 1:numel(idx)
        id = Audit.replicate_id(idx(j));
        rows = Pairwise.objective == "modularity" & ...
            Pairwise.resolution_index == resolutionIndices(g) & ...
            (Pairwise.replicate_id_a == id | ...
            Pairwise.replicate_id_b == id);
        if any(rows)
            meanAri(idx(j)) = mean( ...
                Pairwise.adjusted_rand_index(rows));
        else
            meanAri(idx(j)) = 1;
        end
    end
    tie = table(-meanAri(idx), -double(Audit.quality(idx)), ...
        double(Audit.seed(idx)), idx, ...
        'VariableNames', {'negative_mean_ari','negative_quality', ...
        'seed','global_index'});
    tie = sortrows(tie, ...
        {'negative_mean_ari','negative_quality','seed','global_index'});
    isMedoid(tie.global_index(1)) = true;
end
M = struct('mean_ari', meanAri, 'is_medoid', isMedoid);
end

function [challengerPurity, referencePurity] = ...
        i_bidirectional_overlap_purity(reference, challenger)
reference = double(canonicalize_run09_membership(reference));
challenger = double(canonicalize_run09_membership(challenger));
overlap = sparse(reference, challenger, 1, ...
    max(reference), max(challenger));
challengerPurity = sum(full(max(overlap, [], 1))) / numel(reference);
referencePurity = sum(full(max(overlap, [], 2))) / numel(reference);
end

function value = i_safe_ratio(numerator, denominator)
value = zeros(size(numerator));
valid = denominator > 0;
value(valid) = numerator(valid) ./ denominator(valid);
end
