function Consensus = build_run09_label_aligned_consensus( ...
        Adapter, Bridge, Ensemble, params, opts)
%BUILD_RUN09_LABEL_ALIGNED_CONSENSUS Build split-audited locked partitions.
%
% At each CPM resolution the stochastic partitions are aligned to their
% ARI-medoid labels, combined by deterministic node-wise plurality voting,
% and used only as an initialization for Leiden refinement on the unchanged
% frozen graph. Odd/even seed subsets are processed independently.

if nargin < 5 || isempty(opts)
    opts = struct();
end
if ~isfield(opts, 'checkpoint_dir') || ...
        strlength(string(opts.checkpoint_dir)) == 0
    opts.checkpoint_dir = fullfile(string(params.output_dir), ...
        string(params.consensus_checkpoint_dir));
end
opts.checkpoint_dir = string(opts.checkpoint_dir);
if ~isfolder(opts.checkpoint_dir)
    mkdir(opts.checkpoint_dir);
end

Audit = Ensemble.replicate_audit;
assert(all(Audit.status == "success") && all(Audit.converged), ...
    'build_run09_label_aligned_consensus:IncompleteEnsemble', ...
    'Consensus requires a complete converged raw CPM ensemble.');
primaryMask = Audit.objective == "cpm";
resolutionIndices = unique(Audit.resolution_index(primaryMask), 'sorted');
nLevels = numel(resolutionIndices);
nNodes = numel(Adapter.node_ids);
FullMemberships = zeros(nNodes, nLevels, 'uint32');
OddMemberships = zeros(nNodes, nLevels, 'uint32');
EvenMemberships = zeros(nNodes, nLevels, 'uint32');
VoteSupport = zeros(nNodes, nLevels);
SplitNodeMean = zeros(nNodes, nLevels);
SplitNodeMin = zeros(nNodes, nLevels);
SplitMappedRate = zeros(nNodes, nLevels);
AuditRows = cell(3 * nLevels, 1);
StabilityRows = cell(3 * nLevels, 1);
resolutionIds = strings(nLevels, 1);

auditCursor = 0;
stabilityCursor = 0;
for level = 1:nLevels
    resolutionIndex = resolutionIndices(level);
    idx = find(primaryMask & Audit.resolution_index == resolutionIndex);
    [~, order] = sort(Audit.seed(idx));
    idx = idx(order);
    assert(numel(idx) >= 2, ...
        'build_run09_label_aligned_consensus:TooFewReplicates', ...
        'At least two ordered seeds are required per resolution.');
    oddIdx = idx(1:2:end);
    evenIdx = idx(2:2:end);
    multiplier = Audit.density_multiplier(idx(1));
    resolution = Audit.resolution(idx(1));
    resolutionId = i_resolution_id(multiplier);
    resolutionIds(level) = resolutionId;

    [Full, fullAudit] = i_consensus_variant(Adapter, Bridge, ...
        Ensemble, params, idx, "full", resolutionId, level, ...
        multiplier, resolution, opts.checkpoint_dir);
    [Odd, oddAudit] = i_consensus_variant(Adapter, Bridge, ...
        Ensemble, params, oddIdx, "odd_seed_split", resolutionId, ...
        level, multiplier, resolution, opts.checkpoint_dir);
    [Even, evenAudit] = i_consensus_variant(Adapter, Bridge, ...
        Ensemble, params, evenIdx, "even_seed_split", resolutionId, ...
        level, multiplier, resolution, opts.checkpoint_dir);
    FullMemberships(:, level) = Full.membership;
    OddMemberships(:, level) = Odd.membership;
    EvenMemberships(:, level) = Even.membership;
    VoteSupport(:, level) = Full.vote_support;

    [jOdd, mappedOdd] = i_node_pair_stability( ...
        Full.membership, Odd.membership);
    [jEven, mappedEven] = i_node_pair_stability( ...
        Full.membership, Even.membership);
    SplitNodeMean(:, level) = (jOdd + jEven) / 2;
    SplitNodeMin(:, level) = min(jOdd, jEven);
    SplitMappedRate(:, level) = ...
        (double(mappedOdd) + double(mappedEven)) / 2;

    auditCursor = auditCursor + 1;
    AuditRows{auditCursor} = fullAudit;
    auditCursor = auditCursor + 1;
    AuditRows{auditCursor} = oddAudit;
    auditCursor = auditCursor + 1;
    AuditRows{auditCursor} = evenAudit;

    comparisons = {
        "full_vs_odd", Full, Odd
        "full_vs_even", Full, Even
        "odd_vs_even", Odd, Even
        };
    for c = 1:size(comparisons, 1)
        stabilityCursor = stabilityCursor + 1;
        A = comparisons{c, 2};
        B = comparisons{c, 3};
        metrics = compute_run09_partition_comparison( ...
            A.membership, B.membership);
        StabilityRows{stabilityCursor} = table( ...
            "cpm_consensus_split", level, multiplier, resolution, ...
            A.replicate_id, B.replicate_id, ...
            params.consensus_refinement_seed, ...
            params.consensus_refinement_seed, ...
            double(A.n_candidates), double(B.n_candidates), ...
            metrics.adjusted_rand_index, ...
            metrics.variation_of_information, ...
            metrics.normalized_variation_of_information, ...
            string(comparisons{c, 1}), ...
            'VariableNames', {'objective', 'resolution_index', ...
            'density_multiplier', 'resolution', 'replicate_id_a', ...
            'replicate_id_b', 'seed_a', 'seed_b', ...
            'candidate_count_a', 'candidate_count_b', ...
            'adjusted_rand_index', 'variation_of_information', ...
            'normalized_variation_of_information', 'comparison_type'});
    end
end

Consensus = struct();
Consensus.memberships = FullMemberships;
Consensus.odd_memberships = OddMemberships;
Consensus.even_memberships = EvenMemberships;
Consensus.vote_support = VoteSupport;
Consensus.split_node_stability_mean = SplitNodeMean;
Consensus.split_node_stability_min = SplitNodeMin;
Consensus.split_mapped_assignment_rate = SplitMappedRate;
Consensus.audit = vertcat(AuditRows{:});
Consensus.partition_stability = vertcat(StabilityRows{:});
Consensus.resolution_ids = resolutionIds;
Consensus.checkpoint_dir = opts.checkpoint_dir;
end

function [Output, AuditRow] = i_consensus_variant( ...
        Adapter, Bridge, Ensemble, params, indices, variant, ...
        resolutionId, level, multiplier, resolution, checkpointDir)
groupAudit = Ensemble.replicate_audit(indices, :);
groupMemberships = Ensemble.memberships(:, indices);
[initial, voteSupport, referenceIndex, meanAri] = ...
    i_label_aligned_vote(groupMemberships, groupAudit);
initialHash = compute_run09_membership_sha256(initial);
rawHashes = strjoin(groupAudit.membership_sha256, ";");
contract = i_contract(Adapter, Bridge, params, variant, ...
    resolutionId, resolution, rawHashes, initialHash);
replicateId = "run09_consensus_" + lower(resolutionId) + "_" + variant;
checkpointPath = fullfile(checkpointDir, replicateId + ".mat");
if isfile(checkpointPath)
    [Result, checkpointHash] = i_load_checkpoint( ...
        checkpointPath, contract, Adapter);
    executionSource = "resumed_checkpoint";
else
    Result = run_weighted_leiden_to_convergence(Adapter, Bridge, ...
        "cpm", resolution, params.consensus_refinement_seed, ...
        params, initial);
    checkpointHash = i_save_checkpoint( ...
        checkpointPath, contract, Result);
    executionSource = "computed";
end
assert(Result.converged && Result.status == "success", ...
    'build_run09_label_aligned_consensus:ConsensusDidNotConverge', ...
    'Consensus refinement failed at %s %s.', resolutionId, variant);

Output = struct();
Output.membership = Result.membership;
Output.vote_support = voteSupport;
Output.replicate_id = replicateId;
Output.n_candidates = Result.n_candidates;
Output.quality = Result.quality;
Output.membership_hash = Result.membership_hash;
Output.raw_reference_replicate_id = ...
    groupAudit.replicate_id(referenceIndex);

AuditRow = table(resolutionId, level, multiplier, resolution, variant, ...
    numel(indices), string(strjoin( ...
    compose('%.0f', groupAudit.seed), ";")), ...
    rawHashes, groupAudit.replicate_id(referenceIndex), ...
    meanAri(referenceIndex), initialHash, mean(voteSupport), ...
    i_quantile(voteSupport, 0.05), ...
    params.consensus_refinement_seed, Result.n_iterations, ...
    Result.converged, Result.quality, Result.quality_definition, ...
    Result.runtime_seconds, Result.n_candidates, Result.membership_hash, ...
    contract.contract_sha256, checkpointPath, checkpointHash, ...
    executionSource, Result.status, ...
    'VariableNames', {'resolution_id', 'hierarchy_level', ...
    'density_multiplier', 'resolution', 'consensus_variant', ...
    'input_replicate_count', 'input_seeds', ...
    'input_membership_hashes', 'raw_reference_replicate_id', ...
    'raw_reference_mean_ari', 'vote_initialization_sha256', ...
    'mean_vote_support', 'p05_vote_support', 'refinement_seed', ...
    'n_iterations', 'converged', 'quality', 'quality_definition', ...
    'runtime_seconds', 'candidate_count', 'membership_sha256', ...
    'checkpoint_contract_sha256', 'checkpoint_file', ...
    'checkpoint_sha256', 'execution_source', 'status'});
end

function [vote, support, referenceIndex, meanAri] = ...
        i_label_aligned_vote(Memberships, Audit)
nReplicates = width(Memberships);
ariMatrix = eye(nReplicates);
for a = 1:nReplicates-1
    for b = a+1:nReplicates
        metrics = compute_run09_partition_comparison( ...
            Memberships(:, a), Memberships(:, b));
        ariMatrix(a, b) = metrics.adjusted_rand_index;
        ariMatrix(b, a) = metrics.adjusted_rand_index;
    end
end
if nReplicates == 1
    meanAri = 1;
else
    meanAri = (sum(ariMatrix, 2) - 1) / (nReplicates - 1);
end
tieBreak = table(-meanAri(:), -double(Audit.quality), ...
    double(Audit.seed), (1:nReplicates)', ...
    'VariableNames', {'negative_mean_ari', 'negative_quality', ...
    'seed', 'local_index'});
tieBreak = sortrows(tieBreak, {'negative_mean_ari', ...
    'negative_quality', 'seed', 'local_index'});
referenceIndex = tieBreak.local_index(1);
reference = double(Memberships(:, referenceIndex));
n = numel(reference);
aligned = zeros(n, nReplicates, 'uint32');
for column = 1:nReplicates
    other = double(Memberships(:, column));
    overlap = sparse(reference, other, 1, max(reference), max(other));
    [~, mapToReference] = max(overlap, [], 1);
    mapToReference = mapToReference(:);
    aligned(:, column) = uint32(mapToReference(other));
end
[vote, frequency] = mode(double(aligned), 2);
vote = canonicalize_run09_membership(vote);
support = frequency / nReplicates;
end

function [jaccard, mapped] = i_node_pair_stability(reference, other)
reference = double(reference(:));
other = double(other(:));
referenceCount = accumarray(reference, 1);
otherCount = accumarray(other, 1);
overlap = sparse(reference, other, 1, ...
    numel(referenceCount), numel(otherCount));
linear = sub2ind(size(overlap), reference, other);
intersection = full(overlap(linear));
jaccard = intersection ./ ...
    (referenceCount(reference) + otherCount(other) - intersection);
[~, mapToReference] = max(overlap, [], 1);
mapToReference = mapToReference(:);
mapped = double(mapToReference(other)) == reference;
end

function contract = i_contract(Adapter, Bridge, params, variant, ...
        resolutionId, resolution, rawHashes, initialHash)
contract = struct();
contract.schema = string(params.consensus_checkpoint_schema);
contract.rule = string(params.consensus_partition_rule);
contract.split_rule = string(params.consensus_split_rule);
contract.freeze_id = string(Adapter.freeze_id);
contract.node_sha256 = string(params.expected_node_hash);
contract.edge_sha256 = string(params.expected_edge_hash);
contract.backend_id = string(Bridge.backend_id);
contract.dispatcher_sha256 = string(params.expected_dispatcher_sha256);
contract.variant = string(variant);
contract.resolution_id = string(resolutionId);
contract.resolution = double(resolution);
contract.raw_membership_hashes = string(rawHashes);
contract.initial_membership_sha256 = string(initialHash);
contract.refinement_seed = double(params.consensus_refinement_seed);
contract.randomness = double(params.leiden_randomness);
contract.maximum_iterations = double(params.maximum_iterations);
fields = string(fieldnames(contract));
parts = strings(numel(fields), 1);
for i = 1:numel(fields)
    value = contract.(fields(i));
    if isnumeric(value)
        value = compose('%.17g', value);
    end
    parts(i) = fields(i) + "=" + string(value);
end
contract.contract_sha256 = compute_run09_sha256_text(strjoin(parts, newline));
end

function checkpointHash = i_save_checkpoint(pathText, contract, Result)
checkpoint = struct('contract', contract, ...
    'membership', uint32(Result.membership), ...
    'native_resolution', double(Result.native_resolution), ...
    'n_iterations', double(Result.n_iterations), ...
    'converged', logical(Result.converged), ...
    'quality', double(Result.quality), ...
    'quality_definition', string(Result.quality_definition), ...
    'runtime_seconds', double(Result.runtime_seconds), ...
    'n_candidates', double(Result.n_candidates), ...
    'membership_sha256', string(Result.membership_hash), ...
    'status', string(Result.status));
save_run09_mat_atomic(pathText, struct('checkpoint', checkpoint), false);
checkpointHash = compute_file_sha256(pathText);
end

function [Result, checkpointHash] = ...
        i_load_checkpoint(pathText, expectedContract, Adapter)
loaded = load(pathText, 'checkpoint');
assert(isfield(loaded, 'checkpoint') && ...
    isfield(loaded.checkpoint, 'contract') && ...
    isequaln(orderfields(loaded.checkpoint.contract), ...
    orderfields(expectedContract)), ...
    'build_run09_label_aligned_consensus:CheckpointContractMismatch', ...
    'Consensus checkpoint contract mismatch: %s', pathText);
C = loaded.checkpoint;
membership = uint32(C.membership(:));
assert(numel(membership) == numel(Adapter.node_ids) && ...
    compute_run09_membership_sha256(membership) == ...
    string(C.membership_sha256), ...
    'build_run09_label_aligned_consensus:CheckpointMembershipMismatch', ...
    'Consensus checkpoint membership failed validation.');
[quality, definition] = compute_run09_partition_quality( ...
    Adapter, membership, "cpm", expectedContract.resolution);
tolerance = 1e-12 * max(1, abs(quality));
assert(abs(quality - C.quality) <= tolerance && ...
    string(C.quality_definition) == definition && ...
    isfinite(C.runtime_seconds) && C.runtime_seconds >= 0 && ...
    C.n_candidates == numel(unique(membership)), ...
    'build_run09_label_aligned_consensus:CheckpointMetricMismatch', ...
    'Consensus checkpoint metrics failed independent validation.');
Result = struct('membership', membership, ...
    'native_resolution', C.native_resolution, ...
    'n_iterations', C.n_iterations, 'converged', C.converged, ...
    'quality', quality, 'quality_definition', definition, ...
    'runtime_seconds', C.runtime_seconds, ...
    'n_candidates', C.n_candidates, ...
    'membership_hash', string(C.membership_sha256), ...
    'status', string(C.status));
checkpointHash = compute_file_sha256(pathText);
end

function value = i_quantile(x, probability)
x = sort(double(x(:)));
position = 1 + (numel(x) - 1) * probability;
lowerIndex = floor(position);
upperIndex = ceil(position);
if lowerIndex == upperIndex
    value = x(lowerIndex);
else
    value = x(lowerIndex) + (position - lowerIndex) * ...
        (x(upperIndex) - x(lowerIndex));
end
end

function value = i_resolution_id(multiplier)
value = compose("CPM_M%06d", round(1000 * multiplier));
end
