function [Annotation, Provenance] = ...
        build_run09_provisional_candidate_annotations( ...
        BehaviorProfile, EventProfile, Topology, Source, ...
        membershipHash, params)
%BUILD_RUN09_PROVISIONAL_CANDIDATE_ANNOTATIONS Post-freeze labels only.
%
% This function returns annotations and provenance, never membership.
% Graph-only interpretation eligibility is consumed as an immutable input.

Indicators = i_parse_indicators(params.annotation_indicator_spec);
candidateIds = string(Topology.motif_candidate_id);
nCandidate = numel(candidateIds);

nodeCount = double(Topology.node_count);
eligible = logical(Topology.eligible_for_behavioral_interpretation);
interpretationStatus = string(Topology.interpretation_status);
annotationLabel = strings(nCandidate, 1);
annotationStatus = strings(nCandidate, 1);
socialEvidenceScore = zeros(nCandidate, 1);
nIndicatorsConfigured = repmat(height(Indicators), nCandidate, 1);
nIndicatorsFinite = zeros(nCandidate, 1);
availableIndicatorWeight = zeros(nCandidate, 1);
indicatorEvidence = strings(nCandidate, 1);

for c = 1:nCandidate
    values = nan(height(Indicators), 1);
    evidence = strings(height(Indicators), 1);
    for j = 1:height(Indicators)
        if Indicators.profile_source(j) == "behavior"
            P = BehaviorProfile;
        else
            P = EventProfile;
        end
        row = string(P.motif_candidate_id) == candidateIds(c) & ...
            string(P.feature_name) == Indicators.feature_name(j);
        assert(nnz(row) == 1, ...
            'build_run09_provisional_candidate_annotations:MissingIndicator', ...
            'Configured indicator %s:%s must occur once for candidate %s.', ...
            Indicators.profile_source(j), ...
            Indicators.feature_name(j), candidateIds(c));
        rawValue = double(P.standardized_mean_difference(row));
        values(j) = Indicators.direction(j) * rawValue;
        evidence(j) = Indicators.profile_source(j) + ":" + ...
            Indicators.feature_name(j) + "=" + ...
            compose('%.6g', values(j));
    end
    finite = isfinite(values);
    nIndicatorsFinite(c) = nnz(finite);
    availableIndicatorWeight(c) = sum(Indicators.weight(finite));
    if availableIndicatorWeight(c) > 0
        socialEvidenceScore(c) = sum(values(finite) .* ...
            Indicators.weight(finite)) / availableIndicatorWeight(c);
    else
        socialEvidenceScore(c) = 0;
    end
    indicatorEvidence(c) = strjoin(evidence, ";");

    if ~eligible(c)
        annotationLabel(c) = ...
            "not_interpreted_residual_or_unstable";
        annotationStatus(c) = ...
            "withheld_by_frozen_graph_only_eligibility";
    elseif nIndicatorsFinite(c) < ...
            params.annotation_min_complete_indicators
        annotationLabel(c) = "provisional_indeterminate";
        annotationStatus(c) = ...
            "insufficient_condition_blind_indicators";
    elseif socialEvidenceScore(c) >= ...
            params.annotation_social_score_threshold
        annotationLabel(c) = "provisional_social";
        annotationStatus(c) = "assigned_by_predeclared_profile_rule";
    elseif socialEvidenceScore(c) <= ...
            params.annotation_non_social_score_threshold
        annotationLabel(c) = "provisional_non_social";
        annotationStatus(c) = "assigned_by_predeclared_profile_rule";
    else
        annotationLabel(c) = "provisional_indeterminate";
        annotationStatus(c) = ...
            "evidence_between_predeclared_thresholds";
    end
end

Annotation = table(candidateIds, nodeCount, eligible, ...
    interpretationStatus, annotationLabel, annotationStatus, ...
    socialEvidenceScore, nIndicatorsConfigured, nIndicatorsFinite, ...
    availableIndicatorWeight, indicatorEvidence, ...
    repmat(params.annotation_social_score_threshold, nCandidate, 1), ...
    repmat(params.annotation_non_social_score_threshold, nCandidate, 1), ...
    repmat(params.annotation_min_complete_indicators, nCandidate, 1), ...
    repmat(params.annotation_rule_version, nCandidate, 1), ...
    repmat(string(membershipHash), nCandidate, 1), ...
    repmat(true, nCandidate, 1), ...
    repmat(false, nCandidate, 1), ...
    repmat(false, nCandidate, 1), ...
    repmat("none", nCandidate, 1), ...
    'VariableNames', { ...
    'motif_candidate_id','node_count', ...
    'eligible_for_behavioral_interpretation', ...
    'graph_only_interpretation_status','provisional_annotation', ...
    'annotation_status','social_evidence_score', ...
    'n_indicators_configured','n_indicators_finite', ...
    'available_indicator_weight','indicator_evidence', ...
    'social_score_threshold','non_social_score_threshold', ...
    'minimum_complete_indicators','annotation_rule_version', ...
    'frozen_membership_sha256', ...
    'annotation_generated_after_candidate_freeze', ...
    'annotation_may_change_membership', ...
    'annotation_may_change_interpretation_eligibility', ...
    'experimental_labels_used'});
assert(all(isfinite(Annotation{:, vartype('numeric')}), 'all'), ...
    'build_run09_provisional_candidate_annotations:NonfiniteAnnotation', ...
    'All provisional annotation metrics must be finite.');

Provenance = i_provenance(Indicators, Source, ...
    membershipHash, params);
end

function Indicators = i_parse_indicators(specification)
parts = strip(string(split(specification, ';')));
parts = parts(parts ~= "");
n = numel(parts);
profileSource = strings(n, 1);
featureName = strings(n, 1);
direction = zeros(n, 1);
weight = zeros(n, 1);
for i = 1:n
    fields = string(split(parts(i), '|'));
    assert(numel(fields) == 4, ...
        'build_run09_provisional_candidate_annotations:BadIndicator', ...
        'Annotation indicator entries require four pipe-delimited fields.');
    profileSource(i) = fields(1);
    featureName(i) = fields(2);
    direction(i) = str2double(fields(3));
    weight(i) = str2double(fields(4));
end
assert(all(ismember(profileSource, ["behavior","event"])) && ...
    all(ismember(direction, [-1 1])) && ...
    all(isfinite(weight) & weight > 0) && ...
    abs(sum(weight) - 1) <= 1e-12, ...
    'build_run09_provisional_candidate_annotations:BadIndicatorContract', ...
    'Indicator directions and normalized positive weights are invalid.');
Indicators = table(profileSource, featureName, direction, weight, ...
    'VariableNames', {'profile_source','feature_name', ...
    'direction','weight'});
end

function P = i_provenance(Indicators, Source, ...
        membershipHash, params)
nRule = 7;
nIndicator = height(Indicators);
nSource = height(Source);
n = nRule + nIndicator + nSource;
recordType = strings(n, 1);
provenanceId = strings(n, 1);
value = strings(n, 1);
sourcePath = strings(n, 1);
sha256 = strings(n, 1);
profileSource = strings(n, 1);
featureName = strings(n, 1);
direction = zeros(n, 1);
weight = zeros(n, 1);

ruleIds = [ ...
    "annotation_rule_version"
    "postfit_rule_version"
    "social_score_threshold"
    "non_social_score_threshold"
    "minimum_complete_indicators"
    "eligible_candidates_only"
    "postfreeze_membership_policy"];
ruleValues = [ ...
    params.annotation_rule_version
    params.postfit_rule_version
    compose('%.17g', params.annotation_social_score_threshold)
    compose('%.17g', params.annotation_non_social_score_threshold)
    compose('%.0f', params.annotation_min_complete_indicators)
    string(params.annotation_eligible_candidates_only)
    "retain_all_ids;merge_prohibited;split_prohibited"];
recordType(1:nRule) = "annotation_rule";
provenanceId(1:nRule) = ruleIds;
value(1:nRule) = ruleValues;

for i = 1:nIndicator
    row = nRule + i;
    recordType(row) = "annotation_indicator";
    provenanceId(row) = compose("indicator_%02d", i);
    value(row) = Indicators.profile_source(i) + "|" + ...
        Indicators.feature_name(i) + "|" + ...
        compose('%.0f', Indicators.direction(i)) + "|" + ...
        compose('%.17g', Indicators.weight(i));
    profileSource(row) = Indicators.profile_source(i);
    featureName(row) = Indicators.feature_name(i);
    direction(row) = Indicators.direction(i);
    weight(row) = Indicators.weight(i);
end

for i = 1:nSource
    row = nRule + nIndicator + i;
    recordType(row) = "source_artifact";
    provenanceId(row) = Source.source_id(i);
    value(row) = "byte_exact_sha256_recorded";
    sourcePath(row) = Source.source_path(i);
    sha256(row) = Source.sha256(i);
end

if params.run_mode == "full"
    candidateFreezeId = params.locked_candidate_freeze_id;
else
    candidateFreezeId = "not_frozen_smoke";
end
P = table(recordType, provenanceId, value, sourcePath, sha256, ...
    profileSource, featureName, direction, weight, ...
    repmat(string(candidateFreezeId), n, 1), ...
    repmat(string(membershipHash), n, 1), ...
    repmat(true, n, 1), repmat(false, n, 1), ...
    repmat(false, n, 1), repmat(true, n, 1), ...
    repmat("none", n, 1), ...
    'VariableNames', { ...
    'record_type','provenance_id','value','source_path','sha256', ...
    'profile_source','feature_name','direction','weight', ...
    'candidate_freeze_id','frozen_membership_sha256', ...
    'recorded_after_candidate_freeze','used_for_membership', ...
    'used_for_interpretation_eligibility','annotation_only', ...
    'experimental_labels_used'});
end
