function params = load_motif_candidate_discovery_config(configPath)
%LOAD_MOTIF_CANDIDATE_DISCOVERY_CONFIG Load and validate run_09 parameters.

if nargin < 1 || strlength(string(configPath)) == 0
    repoRoot = fileparts(fileparts(mfilename('fullpath')));
    configPath = fullfile(repoRoot, 'config', ...
        'motif_candidate_discovery_config.csv');
end

opts = detectImportOptions(configPath, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
opts.DataLines = [2 Inf];
opts.VariableNamesLine = 1;
opts.VariableUnitsLine = 0;
opts = setvartype(opts, opts.VariableNames, 'string');
T = readtable(configPath, opts);

required = ["parameter", "value", "type", "env_override", "description"];
missing = setdiff(required, string(T.Properties.VariableNames));
assert(isempty(missing), ...
    'load_motif_candidate_discovery_config:MissingColumn', ...
    'Config %s is missing required columns: %s', ...
    configPath, strjoin(missing, ', '));
assert(numel(unique(T.parameter)) == height(T), ...
    'load_motif_candidate_discovery_config:DuplicateParameter', ...
    'Every run_09 config parameter must be unique.');

params = struct();
envOverrideUsed = false(height(T), 1);
for i = 1:height(T)
    name = matlab.lang.makeValidName(T.parameter(i));
    rawValue = string(T.value(i));
    envName = strtrim(string(T.env_override(i)));
    if ismissing(envName)
        envName = "";
    end
    if envName ~= ""
        envValue = strtrim(string(getenv(envName)));
        if envValue ~= ""
            rawValue = envValue;
            envOverrideUsed(i) = true;
        end
    end
    params.(name) = i_parse_value(rawValue, ...
        lower(strtrim(string(T.type(i)))), T.parameter(i));
end

T.env_override_used = envOverrideUsed;
[params, T] = i_apply_mode(params, T);
T.effective_value = strings(height(T), 1);
for i = 1:height(T)
    name = matlab.lang.makeValidName(T.parameter(i));
    T.effective_value(i) = i_value_to_string(params.(name));
end
T.config_path = repmat(string(configPath), height(T), 1);
params.config_path = string(configPath);
params.config_table = T;

i_validate(params);
end

function [params, T] = i_apply_mode(params, T)
smokeRoot = "derived/motif_candidate_discovery_smoke";
fullRoot = "derived/motif_candidate_discovery";
outputExplicit = any(T.parameter == "output_dir" & T.env_override_used);

if params.run_mode == "full"
    if ~outputExplicit && any(params.output_dir == [smokeRoot fullRoot])
        params.output_dir = fullRoot;
    end
    params.active_cpm_density_multipliers = ...
        params.cpm_density_multipliers_full;
    params.active_cpm_seeds = params.cpm_seeds_full;
    params.active_modularity_resolutions = ...
        params.modularity_resolutions_full;
    params.active_modularity_seeds = params.modularity_seeds_full;
    params.active_retention_min_successful_replicates = ...
        params.retention_min_successful_replicates_full;
    params.active_enable_consensus_partition = ...
        params.enable_consensus_partition_full;
else
    if ~outputExplicit && any(params.output_dir == [smokeRoot fullRoot])
        params.output_dir = smokeRoot;
    end
    params.active_cpm_density_multipliers = ...
        params.cpm_density_multipliers_smoke;
    params.active_cpm_seeds = params.cpm_seeds_smoke;
    params.active_modularity_resolutions = ...
        params.modularity_resolutions_smoke;
    params.active_modularity_seeds = params.modularity_seeds_smoke;
    params.active_retention_min_successful_replicates = ...
        params.retention_min_successful_replicates_smoke;
    params.active_enable_consensus_partition = ...
        params.enable_consensus_partition_smoke;
end
end

function i_validate(params)
assert(any(params.run_mode == ["smoke", "full"]), ...
    'load_motif_candidate_discovery_config:BadRunMode', ...
    'run_mode must be smoke or full.');
outputDir = lower(replace(string(params.output_dir), "\", "/"));
inputDir = lower(replace(string(params.input_dir), "\", "/"));
if params.run_mode == "full"
    assert(~contains(outputDir, "smoke"), ...
        'load_motif_candidate_discovery_config:BadFullOutputDir', ...
        'Full run_09 output_dir must not be a smoke directory.');
else
    assert(contains(outputDir, "smoke"), ...
        'load_motif_candidate_discovery_config:BadSmokeOutputDir', ...
        'Smoke run_09 output_dir must be a separate smoke directory.');
end
assert(~contains(inputDir, "smoke") && contains(inputDir, "rare_enriched"), ...
    'load_motif_candidate_discovery_config:BadFrozenInputDir', ...
    'Both modes must read the production rare-enriched frozen handoff.');
assert(params.expected_freeze_id == ...
    "run08_consensus_d48a1b618ae6_da79abad", ...
    'load_motif_candidate_discovery_config:BadFreezeId', ...
    'The pinned production freeze ID is immutable.');
assert(params.expected_manifest_schema == ...
    "run08_handoff_manifest_v2_byte_exact", ...
    'load_motif_candidate_discovery_config:BadManifestSchema', ...
    'Run_09 requires the byte-exact v2 handoff schema.');
hashes = [params.expected_node_hash, params.expected_edge_hash, ...
    params.expected_freeze_config_hash, params.expected_topology_hash, ...
    params.expected_dispatcher_sha256, ...
    params.locked_candidate_membership_sha256];
assert(all(strlength(hashes) == 64) && ...
    all(~cellfun(@isempty, regexp(cellstr(hashes), ...
    '^[0-9a-f]{64}$', 'once'))), ...
    'load_motif_candidate_discovery_config:BadHash', ...
    'Pinned hashes must be lowercase SHA-256 values.');
assert(params.locked_candidate_freeze_id == ...
    "run09_candidates_2e58d214683b_8817d942_0e956a2c" && ...
    startsWith(params.locked_candidate_membership_sha256, ...
    "2e58d214683b"), ...
    'load_motif_candidate_discovery_config:BadCandidateFreeze', ...
    'The issued run_09 candidate membership freeze may not be renamed.');
assert(params.expected_n_nodes == 50548 && ...
    params.expected_n_edges == 760383 && ...
    params.expected_n_components == 1 && ...
    params.expected_minimum_degree == 10, ...
    'load_motif_candidate_discovery_config:BadFrozenTopology', ...
    'Pinned frozen topology values may not drift.');
assert(params.primary_objective == "cpm" && ...
    params.cpm_resolution_rule == ...
    "weighted_graph_density_times_predeclared_multiplier", ...
    'load_motif_candidate_discovery_config:BadPrimaryObjective', ...
    'Primary run_09 must use density-scaled weighted Leiden-CPM.');
assert(all(params.active_cpm_density_multipliers > 0) && ...
    all(params.active_modularity_resolutions > 0), ...
    'load_motif_candidate_discovery_config:BadResolutionGrid', ...
    'All resolution values and multipliers must be positive.');
assert(all(params.active_cpm_seeds >= 0 & ...
    params.active_cpm_seeds == floor(params.active_cpm_seeds)) && ...
    numel(unique(params.active_cpm_seeds)) == ...
    numel(params.active_cpm_seeds), ...
    'load_motif_candidate_discovery_config:BadCpmSeeds', ...
    'CPM seeds must be unique nonnegative integers.');
assert(numel(params.cpm_seeds_full) == 20, ...
    'load_motif_candidate_discovery_config:BadFullSeedCount', ...
    'Exactly 20 deterministic seeds are required per full CPM resolution.');
assert(all(params.active_modularity_seeds >= 0 & ...
    params.active_modularity_seeds == ...
    floor(params.active_modularity_seeds)), ...
    'load_motif_candidate_discovery_config:BadModularitySeeds', ...
    'Modularity seeds must be nonnegative integers.');
assert(params.leiden_randomness > 0 && ...
    isfinite(params.leiden_randomness), ...
    'load_motif_candidate_discovery_config:BadRandomness', ...
    'Leiden randomness must be positive and finite.');
assert(params.iteration_mode == "until_membership_unchanged" && ...
    params.maximum_iterations >= 2 && ...
    params.maximum_iterations == floor(params.maximum_iterations), ...
    'load_motif_candidate_discovery_config:BadIterations', ...
    'Run_09 must iterate until unchanged with a finite safety cap.');
assert(params.checkpoint_schema == "run09_replicate_checkpoint_v1" && ...
    strlength(params.checkpoint_dir) > 0, ...
    'load_motif_candidate_discovery_config:BadCheckpointContract', ...
    'The atomic replicate checkpoint schema and directory are required.');
assert(params.reference_partition_rule == ...
    "max_mean_pairwise_ari_then_quality_then_lowest_seed", ...
    'load_motif_candidate_discovery_config:BadReferenceRule', ...
    'The topology-only representative partition rule may not drift.');
assert(params.retention_min_successful_replicates_smoke == 2 && ...
    params.retention_min_successful_replicates_full == 20 && ...
    params.active_retention_min_successful_replicates <= ...
    numel(params.active_cpm_seeds), ...
    'load_motif_candidate_discovery_config:BadRetentionReplicates', ...
    'Retention replicate requirements must match the pilot and full design.');
unitInterval = [params.retention_min_pairwise_ari, ...
    params.retention_max_normalized_vi, ...
    params.retention_max_candidate_count_relative_range, ...
    params.retention_max_singleton_node_fraction, ...
    params.retention_max_small_candidate_node_fraction, ...
    params.retention_min_mean_node_stability, ...
    params.ambiguity_min_node_stability, ...
    params.hierarchy_min_child_parent_fraction, ...
    params.hierarchy_min_pair_weighted_child_purity, ...
    params.hierarchy_min_linked_node_fraction, ...
    params.consensus_retention_min_split_ari, ...
    params.consensus_retention_max_normalized_vi, ...
    params.consensus_retention_min_mean_node_stability, ...
    params.consensus_retention_min_mean_vote_support, ...
    params.interpretation_min_mean_node_stability, ...
    params.interpretation_max_boundary_node_fraction, ...
    params.interpretation_max_weighted_conductance, ...
    params.interpretation_min_largest_component_fraction];
assert(all(isfinite(unitInterval)) && all(unitInterval >= 0) && ...
    all(unitInterval <= 1), ...
    'load_motif_candidate_discovery_config:BadUnitIntervalRule', ...
    'Stability retention and hierarchy fractions must lie in [0,1].');
assert(params.retention_min_candidate_count >= 2 && ...
    params.retention_max_candidate_count >= ...
    params.retention_min_candidate_count && ...
    params.small_candidate_max_nodes >= 1 && ...
    params.small_candidate_max_nodes == ...
    floor(params.small_candidate_max_nodes), ...
    'load_motif_candidate_discovery_config:BadCandidateRule', ...
    'Candidate count and small-candidate rules are invalid.');
assert(~params.enable_consensus_partition_smoke && ...
    params.enable_consensus_partition_full && ...
    params.consensus_partition_rule == ...
    "label_aligned_plurality_vote_then_frozen_graph_leiden_refinement" && ...
    params.consensus_split_rule == "ascending_seed_odd_even", ...
    'load_motif_candidate_discovery_config:BadConsensusRule', ...
    'The full-only label-aligned split consensus contract may not drift.');
assert(params.consensus_refinement_seed >= 0 && ...
    params.consensus_refinement_seed == ...
    floor(params.consensus_refinement_seed) && ...
    params.consensus_checkpoint_schema == ...
    "run09_consensus_checkpoint_v1" && ...
    strlength(params.consensus_checkpoint_dir) > 0, ...
    'load_motif_candidate_discovery_config:BadConsensusCheckpoint', ...
    'Consensus seed and checkpoint contract are invalid.');
assert(~params.require_all_full_resolutions_pass_retention && ...
    params.require_at_least_one_full_resolution_retained, ...
    'load_motif_candidate_discovery_config:BadFinalRetentionPolicy', ...
    ['The exploratory grid must be filtered by unchanged retention gates, ' ...
     'with at least one retained full resolution required for freezing.']);
assert(params.interpretation_eligibility_rule_version == ...
    "run09_graph_interpretation_v1" && ...
    params.interpretation_retain_all_candidate_ids && ...
    params.postfreeze_merge_policy == ...
    "prohibited_preserve_frozen_membership" && ...
    params.postfreeze_split_policy == ...
    "prohibited_preserve_frozen_membership", ...
    'load_motif_candidate_discovery_config:BadInterpretationFreezePolicy', ...
    ['Graph-only interpretation eligibility must retain every frozen ID ' ...
     'and prohibit all post-freeze candidate merges and splits.']);
assert(params.interpretation_small_candidate_max_nodes >= 1 && ...
    params.interpretation_small_candidate_max_nodes == ...
    floor(params.interpretation_small_candidate_max_nodes) && ...
    params.interpretation_min_internal_edge_count >= 1 && ...
    params.interpretation_min_internal_edge_count == ...
    floor(params.interpretation_min_internal_edge_count), ...
    'load_motif_candidate_discovery_config:BadInterpretationRule', ...
    'Graph-only size and internal-edge eligibility rules must be positive integers.');
assert(params.postfit_rule_version == ...
    "run09_postfit_interpretation_v1" && ...
    params.postfit_smoke_resolution_rule == ...
    "lowest_configured_cpm_resolution_schema_audit_only" && ...
    params.behavior_profile_summary_kind == "mean" && ...
    params.behavior_profile_source_tensor == ...
    "condition_blind_scaled" && ...
    params.profile_no_finite_fallback_rule == ...
    "global_median_and_zero_standardized_effect", ...
    'load_motif_candidate_discovery_config:BadPostfitProfileRule', ...
    ['The post-fit profile contract must use the predeclared ' ...
     'condition-blind mean behavioral channels.']);
assert(params.exemplar_selection_rule == ...
    "stability_plus_within_candidate_internal_weighted_degree_rank" && ...
    params.exemplar_count_per_candidate >= 1 && ...
    params.exemplar_count_per_candidate == ...
    floor(params.exemplar_count_per_candidate) && ...
    isfinite(params.exemplar_stability_weight) && ...
    isfinite(params.exemplar_centrality_weight) && ...
    params.exemplar_stability_weight >= 0 && ...
    params.exemplar_centrality_weight >= 0 && ...
    abs(params.exemplar_stability_weight + ...
        params.exemplar_centrality_weight - 1) <= 1e-12, ...
    'load_motif_candidate_discovery_config:BadExemplarRule', ...
    ['Exemplars must use only the predeclared normalized stability and ' ...
     'within-candidate graph-centrality score.']);
assert(params.annotation_rule_version == ...
    "run09_provisional_social_annotation_v1" && ...
    params.annotation_eligible_candidates_only && ...
    params.annotation_min_complete_indicators >= 1 && ...
    params.annotation_min_complete_indicators == ...
    floor(params.annotation_min_complete_indicators) && ...
    isfinite(params.annotation_social_score_threshold) && ...
    isfinite(params.annotation_non_social_score_threshold) && ...
    params.annotation_non_social_score_threshold < ...
    params.annotation_social_score_threshold && ...
    strlength(params.annotation_indicator_spec) > 0, ...
    'load_motif_candidate_discovery_config:BadAnnotationRule', ...
    ['Provisional annotations require the frozen rule version, finite ' ...
     'ordered thresholds, and predeclared condition-blind indicators.']);
eventNames = string(split(params.event_profile_feature_names, ';'));
eventNames = strip(eventNames(eventNames ~= ""));
assert(numel(eventNames) == 21 && ...
    numel(unique(eventNames)) == numel(eventNames), ...
    'load_motif_candidate_discovery_config:BadEventProfileFeatures', ...
    'The predeclared condition-blind event profile must contain 21 unique fields.');
indicatorParts = string(split(params.annotation_indicator_spec, ';'));
indicatorParts = strip(indicatorParts(indicatorParts ~= ""));
validIndicators = false(numel(indicatorParts), 1);
for i = 1:numel(indicatorParts)
    fields = string(split(indicatorParts(i), '|'));
    validIndicators(i) = numel(fields) == 4 && ...
        any(fields(1) == ["behavior", "event"]) && ...
        isfinite(str2double(fields(3))) && ...
        any(str2double(fields(3)) == [-1, 1]) && ...
        isfinite(str2double(fields(4))) && ...
        str2double(fields(4)) > 0;
end
assert(~isempty(indicatorParts) && all(validIndicators) && ...
    params.annotation_min_complete_indicators <= ...
    numel(indicatorParts), ...
    'load_motif_candidate_discovery_config:BadAnnotationIndicators', ...
    'Every annotation indicator must declare source feature direction and positive weight.');
assert(params.qc_top_profile_features >= 1 && ...
    params.qc_top_profile_features == ...
    floor(params.qc_top_profile_features) && ...
    params.qc_figure_format == "png" && ...
    strlength(params.qc_figure_directory) > 0, ...
    'load_motif_candidate_discovery_config:BadQcRule', ...
    'Run_09 QC figure settings are invalid.');
assert(params.paper_figure_raster_format == "png" && ...
    params.paper_figure_vector_format == "pdf" && ...
    params.paper_figure_raster_dpi >= 150 && ...
    params.paper_figure_raster_dpi == ...
    floor(params.paper_figure_raster_dpi) && ...
    strlength(params.paper_figure_directory) > 0, ...
    'load_motif_candidate_discovery_config:BadPaperFigureRule', ...
    'Run_09 paper-figure settings are invalid.');
end

function value = i_parse_value(rawValue, valueType, parameterName)
rawValue = string(rawValue);
switch valueType
    case "number"
        value = str2double(rawValue);
        assert(isfinite(value), ...
            'load_motif_candidate_discovery_config:BadNumber', ...
            '%s must be finite numeric.', parameterName);
    case "number_list"
        parts = strtrim(string(split(rawValue, {';', '|', ','})))';
        parts = parts(parts ~= "");
        value = str2double(parts);
        assert(~isempty(value) && all(isfinite(value)), ...
            'load_motif_candidate_discovery_config:BadNumberList', ...
            '%s must be a finite numeric list.', parameterName);
    case "logical"
        text = lower(strtrim(rawValue));
        assert(any(text == ["true", "false", "1", "0", "yes", "no"]), ...
            'load_motif_candidate_discovery_config:BadLogical', ...
            '%s must be logical-like.', parameterName);
        value = any(text == ["true", "1", "yes"]);
    case {"string", "path"}
        value = strtrim(rawValue);
    otherwise
        error('load_motif_candidate_discovery_config:BadType', ...
            'Unsupported config type %s for %s.', valueType, parameterName);
end
end

function value = i_value_to_string(x)
if islogical(x)
    if x
        value = "true";
    else
        value = "false";
    end
elseif isnumeric(x)
    value = strjoin(compose('%.17g', x(:)'), ';');
else
    value = string(x);
end
end
