function Bridge = prepare_run09_matlab_igraph_bridge(outRoot, params)
%PREPARE_RUN09_MATLAB_IGRAPH_BRIDGE Pin and expose the weighted native MEX.
%
% matlab-igraph 0.2.4's public cluster wrapper omits graph weight conversion.
% The tagged native dispatcher does support weights. This function verifies
% the installed versions and binary hash, copies that exact MEX to an ordinary
% run-local path, exposes its dependent DLL directory through PATH, and runs a
% discriminating weighted CPM probe.

outRoot = string(outRoot);
clusterPath = string(which('igraph.cluster'));
assert(clusterPath ~= "", ...
    'prepare_run09_matlab_igraph_bridge:MissingToolbox', ...
    'matlab-igraph is not installed on the MATLAB path.');
toolboxRoot = string(fileparts(fileparts(clusterPath)));
privateRoot = fullfile(toolboxRoot, '+igraph', 'private');
sourceMex = fullfile(privateRoot, "mexIgraphDispatcher." + string(mexext));
assert(isfile(sourceMex), ...
    'prepare_run09_matlab_igraph_bridge:MissingDispatcher', ...
    'Missing installed matlab-igraph dispatcher: %s', sourceMex);

versions = igraph.version();
toolboxVersion = string(versions.toolbox);
coreVersion = string(versions.library);
sourceHash = compute_file_sha256(sourceMex);
assert(toolboxVersion == params.expected_matlab_igraph_version, ...
    'prepare_run09_matlab_igraph_bridge:ToolboxVersionMismatch', ...
    'Expected matlab-igraph %s but found %s.', ...
    params.expected_matlab_igraph_version, toolboxVersion);
assert(coreVersion == params.expected_igraph_core_version, ...
    'prepare_run09_matlab_igraph_bridge:CoreVersionMismatch', ...
    'Expected igraph core %s but found %s.', ...
    params.expected_igraph_core_version, coreVersion);
assert(sourceHash == params.expected_dispatcher_sha256, ...
    'prepare_run09_matlab_igraph_bridge:DispatcherHashMismatch', ...
    'Installed dispatcher SHA-256 differs from the pinned run_09 backend.');

bridgeRoot = fullfile(outRoot, '_matlab_igraph_native_bridge', ...
    extractBefore(sourceHash, 17));
if ~isfolder(bridgeRoot)
    mkdir(bridgeRoot);
end
bridgeMex = fullfile(bridgeRoot, "mexIgraphDispatcher." + string(mexext));
if ~isfile(bridgeMex)
    copyfile(sourceMex, bridgeMex);
end
bridgeHash = compute_file_sha256(bridgeMex);
assert(bridgeHash == sourceHash, ...
    'prepare_run09_matlab_igraph_bridge:BridgeCopyMismatch', ...
    'Run-local dispatcher copy does not match the installed pinned binary.');

clear mexIgraphDispatcher
oldSystemPath = string(getenv('PATH'));
setenv('PATH', privateRoot + pathsep + oldSystemPath);
addpath(bridgeRoot, '-begin');
rehash;
resolvedDispatcher = string(which('mexIgraphDispatcher'));
assert(resolvedDispatcher == bridgeMex, ...
    'prepare_run09_matlab_igraph_bridge:DispatcherResolutionMismatch', ...
    'The run-local pinned dispatcher was not selected.');

[probeMembership, probeQuality] = i_weighted_probe();
expectedProbe = [ones(4, 1); 2 * ones(4, 1)];
probePass = isequal(probeMembership, expectedProbe) && ...
    abs(probeQuality - 11.4) <= 1e-12;

Audit = table( ...
    ["backend_id"; "matlab_igraph_version"; "igraph_core_version"; ...
     "installed_dispatcher_path"; "installed_dispatcher_sha256"; ...
     "bridge_dispatcher_path"; "bridge_dispatcher_sha256"; ...
     "public_cluster_wrapper_used"; "weighted_probe_membership"; ...
     "weighted_probe_independent_cpm_quality"; ...
     "weighted_probe_pass"; "backend_ready"], ...
    [params.backend_id; toolboxVersion; coreVersion; sourceMex; sourceHash; ...
     bridgeMex; bridgeHash; "false"; ...
     strjoin(string(probeMembership'), ";"); ...
     compose('%.17g', probeQuality); string(probePass); ...
     string(probePass)], ...
    [true; toolboxVersion == params.expected_matlab_igraph_version; ...
     coreVersion == params.expected_igraph_core_version; true; ...
     sourceHash == params.expected_dispatcher_sha256; true; ...
     bridgeHash == sourceHash; true; probePass; probePass; ...
     probePass; probePass], ...
    [ ...
     "Configured native weighted bridge identity."
     "Pinned public toolbox version."
     "Pinned compiled igraph core version."
     "Installed private dispatcher used only after freeze validation."
     "Exact installed dispatcher byte identity."
     "Run-local ordinary-path copy avoids modifying the installed toolbox."
     "Run-local copy preserves exact dispatcher bytes."
     "The defective public igraph.cluster wrapper is bypassed."
     "A 0.01 bridge at CPM gamma 0.05 must split two K4 cliques."
     "Independent pairwise weighted CPM quality for the expected optimum."
     "Discriminating runtime proof that edge weights reach Leiden."
     "All backend identity and weighted capability gates passed."
     ], ...
    'VariableNames', {'audit_item', 'observed_value', 'pass', 'details'});
assert(all(Audit.pass), ...
    'prepare_run09_matlab_igraph_bridge:WeightedProbeFailed', ...
    'The pinned native bridge failed its weighted Leiden-CPM probe.');

Bridge = struct();
Bridge.backend_id = params.backend_id;
Bridge.toolbox_root = toolboxRoot;
Bridge.private_root = privateRoot;
Bridge.source_mex = sourceMex;
Bridge.source_hash = sourceHash;
Bridge.bridge_root = bridgeRoot;
Bridge.bridge_mex = bridgeMex;
Bridge.bridge_hash = bridgeHash;
Bridge.old_system_path = oldSystemPath;
Bridge.audit = Audit;
Bridge.ready = true;
end

function [membership, quality] = i_weighted_probe()
s = [1 1 1 2 2 3 5 5 5 6 6 7 4]';
t = [2 3 4 3 4 4 6 7 8 7 8 8 5]';
w = [ones(12, 1); 0.01];
G = graph(s, t, w, 8);
graphOpts = struct('isdirected', false, 'isweighted', true, ...
    'weight', 'Weight');
methodOpts = struct('resolution', 0.05, 'randomness', 0.01, ...
    'nIterations', 2, 'metric', 'cpm', 'initial', 1:8);
igraph.rng(240724, 'mt19937');
membership = mexIgraphDispatcher('cluster', G, 'leiden', ...
    graphOpts, methodOpts);
membership = canonicalize_run09_membership(membership(:));
internal = sum(w(membership(s) == membership(t)));
sizes = accumarray(membership, 1);
quality = internal - 0.05 * sum(sizes .* (sizes - 1) / 2);
end
