function outputs = run_condition_blind_motif_candidate_discovery(repoRoot, opts)
%RUN_CONDITION_BLIND_MOTIF_CANDIDATE_DISCOVERY Run registered run_09 ensemble.
%
% Partition inputs are restricted to frozen node identity, numeric edge
% endpoints, consensus weights, and graph topology. Scale, session, arena,
% anchor-stage, rare-stratum, event, annotation, UMAP, and experimental-label
% values cannot reach the graph backend.

if nargin < 1 || strlength(string(repoRoot)) == 0
    repoRoot = fileparts(fileparts(mfilename('fullpath')));
end
if nargin < 2 || isempty(opts)
    opts = struct();
end
if ~isfield(opts, 'configPath') || strlength(string(opts.configPath)) == 0
    opts.configPath = fullfile(repoRoot, 'config', ...
        'motif_candidate_discovery_config.csv');
end

repoRoot = string(repoRoot);
cd(repoRoot);
addpath(genpath(repoRoot));
params = load_motif_candidate_discovery_config(opts.configPath);
outRoot = string(resolve_repo_path(repoRoot, params.output_dir));
logRoot = fullfile(outRoot, 'logs');
if ~isfolder(outRoot)
    mkdir(outRoot);
end
if ~isfolder(logRoot)
    mkdir(logRoot);
end

diary(fullfile(logRoot, ...
    'run_09_discover_condition_blind_motif_candidates_latest.log'));
diaryCleanup = onCleanup(@() diary('off'));
fprintf('run_09_discover_condition_blind_motif_candidates\n');
fprintf('Run mode: %s\n', params.run_mode);
fprintf('Frozen input root: %s\n', ...
    resolve_repo_path(repoRoot, params.input_dir));
fprintf('Output root: %s\n', outRoot);

paths = i_output_paths(outRoot, params);
write_run09_table_atomic(i_parameter_audit(params, NaN, [], []), ...
    paths.parameterAudit);

% This is the mandatory first executable gate. No matlab-igraph call occurs
% above or inside validate_run09_frozen_handoff.
Validation = validate_run09_frozen_handoff( ...
    repoRoot, params, paths.freezeValidation);
Adapter = build_run09_frozen_graph_adapter(Validation);
writetable(Adapter.audit, paths.adapterAudit);
writetable(Adapter.node_index, paths.nodeIndex);

Bridge = prepare_run09_matlab_igraph_bridge(outRoot, params);
bridgeCleanup = onCleanup(@() ...
    release_run09_matlab_igraph_bridge(Bridge));
writetable(Bridge.audit, paths.backendAudit);

ensembleOptions = struct('checkpoint_dir', paths.checkpointDir, ...
    'replicate_audit_path', paths.replicateAudit);
Ensemble = execute_run09_partition_ensemble( ...
    Adapter, Bridge, params, ensembleOptions);
write_run09_table_atomic(Ensemble.replicate_audit, paths.replicateAudit);
write_run09_table_atomic(i_parameter_audit(params, Adapter.weighted_density, ...
    Ensemble.cpm_resolution_grid, Ensemble.modularity_resolution_grid), ...
    paths.parameterAudit);

memberships = Ensemble.memberships;
node_ids = Ensemble.node_ids;
replicate_audit = Ensemble.replicate_audit;
freeze_id = Validation.freeze_id;
weighted_graph_density = Ensemble.weighted_graph_density;
save_run09_mat_atomic(paths.membershipMat, struct( ...
    'memberships', memberships, 'node_ids', node_ids, ...
    'replicate_audit', replicate_audit, 'freeze_id', freeze_id, ...
    'weighted_graph_density', weighted_graph_density), true);

if logical(params.require_all_replicates_converged)
    assert(Ensemble.all_replicates_converged && ...
        all(Ensemble.replicate_audit.status == "success"), ...
        'run_condition_blind_motif_candidate_discovery:ReplicateFailure', ...
        ['At least one configured Leiden replicate failed to converge or ' ...
         'errored. The replicate audit and completed memberships were saved.']);
end

if logical(params.active_enable_consensus_partition)
    consensusOptions = struct('checkpoint_dir', ...
        paths.consensusCheckpointDir);
    Consensus = build_run09_label_aligned_consensus( ...
        Adapter, Bridge, Ensemble, params, consensusOptions);
    write_run09_table_atomic(Consensus.audit, paths.consensusAudit);
    save_run09_mat_atomic(paths.consensusMat, struct( ...
        'memberships', Consensus.memberships, ...
        'odd_memberships', Consensus.odd_memberships, ...
        'even_memberships', Consensus.even_memberships, ...
        'vote_support', Consensus.vote_support, ...
        'split_node_stability_mean', ...
        Consensus.split_node_stability_mean, ...
        'split_node_stability_min', ...
        Consensus.split_node_stability_min, ...
        'split_mapped_assignment_rate', ...
        Consensus.split_mapped_assignment_rate, ...
        'consensus_audit', Consensus.audit, ...
        'resolution_ids', Consensus.resolution_ids), true);
    Analysis = analyze_run09_partition_ensemble( ...
        Adapter, Ensemble, params, Consensus);
else
    Analysis = analyze_run09_partition_ensemble( ...
        Adapter, Ensemble, params);
end
write_run09_table_atomic(Analysis.partition_stability, ...
    paths.partitionStability);
write_run09_table_atomic(Analysis.resolution_sensitivity, ...
    paths.resolutionSensitivity);
write_run09_table_atomic(Analysis.node_ambiguity, paths.nodeAmbiguity);
write_run09_table_atomic(Analysis.hierarchy, paths.hierarchy);
write_run09_table_atomic(Analysis.hierarchy_resolution_audit, ...
    paths.hierarchyResolutionAudit);
write_run09_table_atomic(Analysis.candidate_definition, ...
    paths.candidateDefinition);
write_run09_table_atomic(Analysis.node_membership, paths.nodeMembership);

if params.run_mode == "full" && ...
        logical(params.require_all_full_resolutions_pass_retention)
    assert(Analysis.all_active_resolutions_retained, ...
        'run_condition_blind_motif_candidate_discovery:RetentionGateFailure', ...
        ['At least one full resolution failed a predeclared topology-only ' ...
         'retention gate. Artifacts were written, but candidate IDs may ' ...
         'not be treated as frozen.']);
end
if params.run_mode == "full" && ...
        logical(params.require_at_least_one_full_resolution_retained)
    assert(Analysis.has_retained_resolution, ...
        'run_condition_blind_motif_candidate_discovery:NoRetainedResolution', ...
        ['No full resolution passed every predeclared topology-only ' ...
         'retention gate. Audit artifacts were written but candidate IDs ' ...
         'may not be treated as frozen.']);
end
TopologyAudits = build_run09_candidate_topology_audits( ...
    Adapter, Analysis, Ensemble, params);
write_run09_table_atomic(TopologyAudits.candidate_topology, ...
    paths.candidateTopologyAudit);
write_run09_table_atomic(TopologyAudits.objective_concordance, ...
    paths.objectiveConcordanceAudit);
Postfit = build_run09_postfit_candidate_audits( ...
    repoRoot, outRoot, Validation, Adapter, Analysis, ...
    TopologyAudits, params);
write_run09_table_atomic(Postfit.scale_composition, ...
    paths.scaleCompositionAudit);
write_run09_table_atomic(Postfit.session_composition, ...
    paths.sessionCompositionAudit);
write_run09_table_atomic(Postfit.behavioral_profile, ...
    paths.behavioralProfile);
write_run09_table_atomic(Postfit.event_profile, ...
    paths.eventProfile);
write_run09_table_atomic(Postfit.exemplar_manifest, ...
    paths.exemplarManifest);
write_run09_table_atomic(Postfit.annotation, paths.annotation);
write_run09_table_atomic(Postfit.annotation_provenance, ...
    paths.annotationProvenance);
FigureManifest = make_run09_candidate_qc_figures( ...
    outRoot, Postfit, TopologyAudits, params);
write_run09_table_atomic(FigureManifest, paths.qcFigureManifest);
PaperFigureManifest = make_run09_candidate_paper_figures( ...
    outRoot, Postfit, TopologyAudits, params);
write_run09_table_atomic(PaperFigureManifest, ...
    paths.paperFigureManifest);
[OutputManifest, candidateFreezeId] = build_run09_output_manifest( ...
    repoRoot, outRoot, params, Validation);
write_run09_table_atomic(OutputManifest, paths.outputManifest);

fprintf('Frozen nodes: %d | edges: %d | weighted density: %.12g\n', ...
    numel(Adapter.node_ids), numel(Adapter.weights), ...
    Adapter.weighted_density);
fprintf('Completed replicates: %d | all converged: %d\n', ...
    height(Ensemble.replicate_audit), ...
    Ensemble.all_replicates_converged);
fprintf('Replicate audit: %s\n', paths.replicateAudit);
fprintf('Membership ensemble: %s\n', paths.membershipMat);
fprintf('Resolution sensitivity: %s\n', paths.resolutionSensitivity);
fprintf('Retained resolutions: %d | multilevel hierarchy supported: %d\n', ...
    Analysis.n_retained_resolutions, ...
    Analysis.multilevel_hierarchy_supported);
fprintf('Candidate freeze ID: %s\n', candidateFreezeId);

outputs = struct();
outputs.output_root = outRoot;
outputs.freeze_id = Validation.freeze_id;
outputs.freeze_validation_path = paths.freezeValidation;
outputs.adapter_audit_path = paths.adapterAudit;
outputs.backend_audit_path = paths.backendAudit;
outputs.replicate_audit_path = paths.replicateAudit;
outputs.membership_mat_path = paths.membershipMat;
outputs.n_nodes = numel(Adapter.node_ids);
outputs.n_edges = numel(Adapter.weights);
outputs.n_replicates = height(Ensemble.replicate_audit);
outputs.all_replicates_converged = Ensemble.all_replicates_converged;
outputs.all_active_resolutions_retained = ...
    Analysis.all_active_resolutions_retained;
outputs.n_retained_resolutions = Analysis.n_retained_resolutions;
outputs.has_retained_resolution = Analysis.has_retained_resolution;
outputs.multilevel_hierarchy_supported = ...
    Analysis.multilevel_hierarchy_supported;
outputs.resolution_sensitivity_path = paths.resolutionSensitivity;
outputs.partition_stability_path = paths.partitionStability;
outputs.node_ambiguity_path = paths.nodeAmbiguity;
outputs.hierarchy_path = paths.hierarchy;
outputs.hierarchy_resolution_audit_path = ...
    paths.hierarchyResolutionAudit;
outputs.candidate_topology_audit_path = paths.candidateTopologyAudit;
outputs.objective_concordance_audit_path = ...
    paths.objectiveConcordanceAudit;
outputs.scale_composition_audit_path = paths.scaleCompositionAudit;
outputs.session_composition_audit_path = paths.sessionCompositionAudit;
outputs.behavioral_profile_path = paths.behavioralProfile;
outputs.event_profile_path = paths.eventProfile;
outputs.exemplar_manifest_path = paths.exemplarManifest;
outputs.annotation_path = paths.annotation;
outputs.annotation_provenance_path = paths.annotationProvenance;
outputs.qc_figure_manifest_path = paths.qcFigureManifest;
outputs.paper_figure_manifest_path = paths.paperFigureManifest;
outputs.output_manifest_path = paths.outputManifest;
outputs.candidate_freeze_id = candidateFreezeId;
end

function paths = i_output_paths(outRoot, params)
paths = struct();
paths.parameterAudit = fullfile(outRoot, params.parameter_audit_file);
paths.freezeValidation = fullfile(outRoot, params.freeze_validation_file);
paths.adapterAudit = fullfile(outRoot, params.adapter_audit_file);
paths.nodeIndex = fullfile(outRoot, params.node_index_file);
paths.backendAudit = fullfile(outRoot, params.backend_audit_file);
paths.replicateAudit = fullfile(outRoot, params.replicate_audit_file);
paths.membershipMat = fullfile(outRoot, params.membership_mat_file);
paths.checkpointDir = fullfile(outRoot, params.checkpoint_dir);
paths.partitionStability = fullfile(outRoot, ...
    params.partition_stability_file);
paths.resolutionSensitivity = fullfile(outRoot, ...
    params.resolution_sensitivity_file);
paths.nodeAmbiguity = fullfile(outRoot, params.node_ambiguity_file);
paths.hierarchy = fullfile(outRoot, params.hierarchy_file);
paths.hierarchyResolutionAudit = fullfile(outRoot, ...
    params.hierarchy_resolution_audit_file);
paths.candidateDefinition = fullfile(outRoot, ...
    params.candidate_definition_file);
paths.nodeMembership = fullfile(outRoot, params.node_membership_file);
paths.candidateTopologyAudit = fullfile(outRoot, ...
    params.candidate_topology_audit_file);
paths.objectiveConcordanceAudit = fullfile(outRoot, ...
    params.objective_concordance_audit_file);
paths.scaleCompositionAudit = fullfile(outRoot, ...
    params.scale_composition_audit_file);
paths.sessionCompositionAudit = fullfile(outRoot, ...
    params.session_composition_audit_file);
paths.behavioralProfile = fullfile(outRoot, ...
    params.behavioral_profile_file);
paths.eventProfile = fullfile(outRoot, params.event_profile_file);
paths.exemplarManifest = fullfile(outRoot, ...
    params.exemplar_manifest_file);
paths.annotation = fullfile(outRoot, params.annotation_file);
paths.annotationProvenance = fullfile(outRoot, ...
    params.annotation_provenance_file);
paths.qcFigureManifest = fullfile(outRoot, ...
    params.qc_figure_manifest_file);
paths.paperFigureManifest = fullfile(outRoot, ...
    params.paper_figure_manifest_file);
paths.consensusCheckpointDir = fullfile(outRoot, ...
    params.consensus_checkpoint_dir);
paths.consensusAudit = fullfile(outRoot, params.consensus_audit_file);
paths.consensusMat = fullfile(outRoot, params.consensus_mat_file);
paths.outputManifest = fullfile(outRoot, params.output_manifest_file);
end

function T = i_parameter_audit(params, density, cpmGrid, modularityGrid)
C = params.config_table;
T = table(string(C.parameter), string(C.effective_value), ...
    repmat("config", height(C), 1), false(height(C), 1), ...
    string(C.description), ...
    'VariableNames', {'parameter', 'effective_value', 'source', ...
    'used_for_partitioning', 'description'});
partitionParameters = ["backend_id", "primary_objective", ...
    "cpm_resolution_rule", "cpm_density_multipliers_full", ...
    "cpm_density_multipliers_smoke", "cpm_seeds_full", ...
    "cpm_seeds_smoke", "enable_modularity_challenger", ...
    "modularity_resolutions_full", "modularity_resolutions_smoke", ...
    "modularity_seeds_full", "modularity_seeds_smoke", ...
    "leiden_randomness", "iteration_mode", "maximum_iterations", ...
    "reference_partition_rule", "retention_min_pairwise_ari", ...
    "retention_max_normalized_vi", ...
    "retention_min_candidate_count", ...
    "retention_max_candidate_count", ...
    "retention_max_candidate_count_relative_range", ...
    "retention_max_singleton_node_fraction", ...
    "small_candidate_max_nodes", ...
    "retention_max_small_candidate_node_fraction", ...
    "retention_min_mean_node_stability", ...
    "ambiguity_min_node_stability", ...
    "hierarchy_min_child_parent_fraction", ...
    "hierarchy_min_pair_weighted_child_purity", ...
    "hierarchy_min_linked_node_fraction", ...
    "consensus_partition_rule", "consensus_split_rule", ...
    "consensus_refinement_seed", ...
    "consensus_retention_min_split_ari", ...
    "consensus_retention_max_normalized_vi", ...
    "consensus_retention_min_mean_node_stability", ...
    "consensus_retention_min_mean_vote_support"];
T.used_for_partitioning = ismember(T.parameter, partitionParameters);
if isfinite(density)
    derived = table( ...
        ["weighted_graph_density"; "active_cpm_resolution_grid"; ...
         "active_modularity_resolution_grid"; "active_cpm_seeds"; ...
         "active_modularity_seeds"; "partition_input_columns"; ...
         "experimental_labels_used_for_partitioning"], ...
        [compose('%.17g', density); i_join_numeric(cpmGrid); ...
         i_join_numeric(modularityGrid); ...
         i_join_numeric(params.active_cpm_seeds); ...
         i_join_numeric(params.active_modularity_seeds); ...
         "source_index;target_index;consensus_edge_weight"; "none"], ...
        repmat("derived_after_frozen_adapter", 7, 1), ...
        [true; true; true; true; true; true; false], ...
        [ ...
         "Total consensus weight divided by the number of possible undirected pairs."
         "Density-scaled primary weighted CPM resolutions."
         "Canonical weighted modularity challenger resolutions."
         "Deterministic CPM seeds active in this run mode."
         "Deterministic modularity challenger seeds active in this run mode."
         "Exact numeric fields reaching the weighted native graph."
         "Explicit scientific exclusion contract."
         ], ...
        'VariableNames', T.Properties.VariableNames);
    T = [T; derived];
end
end

function value = i_join_numeric(x)
if isempty(x)
    value = "";
else
    value = strjoin(compose('%.17g', x(:)'), ';');
end
end
