function Audit = validate_matlab_igraph_backend(outputDir)
%VALIDATE_MATLAB_IGRAPH_BACKEND Audit matlab-igraph for run_09 use.
%
% This dependency audit intentionally uses only small synthetic graphs. It
% does not read or modify the frozen run_08 graph. The audit checks the
% installed public MATLAB API, hashes the installed adapter files, exercises
% explicit igraph RNG seeding, and compares returned partitions and
% modularity values with independently evaluated weighted objectives.

arguments
    outputDir (1, 1) string = ""
end

repoRoot = string(fileparts(fileparts(mfilename('fullpath'))));
if outputDir == ""
    outputDir = fullfile(repoRoot, 'derived', 'run09_backend_validation');
end
if ~isfolder(outputDir)
    mkdir(outputDir);
end

clusterPath = string(which('igraph.cluster'));
assert(clusterPath ~= "", ...
    'validate_matlab_igraph_backend:MissingToolbox', ...
    'igraph.cluster is not on the MATLAB path.');
toolboxRoot = string(fileparts(fileparts(clusterPath)));
versionInfo = igraph.version();
toolboxVersion = string(versionInfo.toolbox);
coreVersion = string(versionInfo.library);
mexExtension = string(mexext);

clusterText = string(fileread(clusterPath));
modularityPath = fullfile(toolboxRoot, '+igraph', 'modularity.m');
modularityText = string(fileread(modularityPath));
rngPath = fullfile(toolboxRoot, '+igraph', 'rng.m');
rngText = string(fileread(rngPath));

clusterExposesGraphWeights = contains(clusterText, "graphOpts.isweighted") && ...
    contains(clusterText, "graphOpts.weight");
modularityExposesGraphWeights = contains(modularityText, "graphOpts.isweighted") && ...
    contains(modularityText, "graphOpts.weight");
hasCpm = contains(clusterText, "'cpm'");
hasModularity = contains(clusterText, "'modularity'");
hasResolution = contains(clusterText, "opts.resolution");
hasFixedIterations = contains(clusterText, "opts.nIterations");
hasConvergenceSentinel = contains(clusterText, ...
    "opts.nIterations (1, 1) {mustBeInteger} = -1");
hasExplicitRng = contains(rngText, "'mt19937'");

Environment = table( ...
    ["matlab_release"; "matlab_version"; "matlab_igraph_root"; ...
     "matlab_igraph_version"; "igraph_core_version"; "mex_extension"; ...
     "validation_timestamp_utc"], ...
    [string(version('-release')); string(version); toolboxRoot; ...
     toolboxVersion; coreVersion; mexExtension; ...
     string(datetime('now', 'TimeZone', 'UTC', ...
     'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX'))], ...
    'VariableNames', {'parameter', 'value'});

relativePaths = [ ...
    "igraph.m"
    fullfile("+igraph", "cluster.m")
    fullfile("+igraph", "modularity.m")
    fullfile("+igraph", "rng.m")
    fullfile("+igraph", "version.m")
    fullfile("+igraph", "isweighted.m")
    fullfile("resources", "addons_core.xml")
    fullfile("+igraph", "private", "mexIgraphDispatcher." + mexExtension)
    fullfile("+igraph", "private", "mexIgraphVersion." + mexExtension)
    fullfile("+igraph", "private", "mexIgraphIsDirected." + mexExtension)
    ];
roles = [ ...
    "toolbox_namespace"
    "public_leiden_wrapper"
    "public_modularity_wrapper"
    "public_rng_wrapper"
    "version_wrapper"
    "weight_detection_wrapper"
    "installed_addon_metadata"
    "compiled_igraph_dispatcher"
    "compiled_version_probe"
    "compiled_direction_probe"
    ];
FileHashes = i_hash_files(toolboxRoot, relativePaths, roles);

licenseNames = [dir(fullfile(toolboxRoot, '**', 'LICENSE*')); ...
    dir(fullfile(toolboxRoot, '**', 'COPYING*')); ...
    dir(fullfile(toolboxRoot, '**', 'NOTICE*'))];
installedLicensePresent = ~isempty(licenseNames);
LicenseAudit = table( ...
    ["matlab-igraph"; "igraph-core"], ...
    [toolboxVersion; coreVersion], ...
    ["GPL-3.0-or-later"; "GPL-2.0-or-later"], ...
    [installedLicensePresent; installedLicensePresent], ...
    ["v0.2.4 / 962f2f338803be472ceb8f324db075cebe7629ac"; ...
     "0.10.16 / beebfcdcd707f50a31cf8eb3568cf09f8b7baf54"], ...
    ["LICENSE"; "COPYING"], ...
    ["27768f7e9494968876a5aeee634ab39a9eb4ac55c116068abc2d050ba6d405c2"; ...
     "b499eddebda05a8859e32b820a64577d91f1de2b52efa2a1575a2cb4000bc259"], ...
    ["https://github.com/DavidRConnell/matlab-igraph/blob/v0.2.4/LICENSE"; ...
     "https://github.com/igraph/igraph/blob/0.10.16/COPYING"], ...
    ["Tagged source headers and LICENSE state GPL v3 or later."; ...
     "The igraph COPYING file and project documentation state GPL v2 or later."], ...
    'VariableNames', {'component', 'version', 'spdx_license', ...
    'license_file_present_in_installed_addon', 'upstream_tag_and_commit', ...
    'upstream_license_path', 'upstream_license_sha256', ...
    'upstream_license_url', 'license_evidence'});

UpstreamSource = table( ...
    ["toolbox/+igraph/cluster.m"; "toolbox/+igraph/modularity.m"; ...
     "toolbox/+igraph/rng.m"; "mex/private/mexIgraphCluster.c"; ...
     "mxIgraph/src/mxGraph.c"], ...
    ["c3dc1dac5e41ff5debb9d97ff9ae9e04761295297bc6054fc14986c0af734923"; ...
     "3f9d70179ba5c0a3ab21abcc3858fc04bf159e8c5d1abd8629921f56aa116b30"; ...
     "685ceef6c171487664b375f0bae155b60f3fcea3607ccd5457f9de0d299424b3"; ...
     "91b2d55d527c7ec80b0b9e42b1d81c58cc876926b15e6bbf2d05ce10ca4630cd"; ...
     "7a17d25838b58f4c95214e63517131cda505541c3d175d76d49d0333baa52e5f"], ...
    ["installed byte match"; "installed byte match"; "installed byte match"; ...
     "not installed; immutable tagged-source audit"; ...
     "not installed; immutable tagged-source audit"], ...
    ["Public cluster wrapper omits graphOpts.isweighted and graphOpts.weight."; ...
     "Public modularity wrapper omits graphOpts.isweighted and graphOpts.weight."; ...
     "Explicit independent generators include MT19937."; ...
     "Native Leiden call accepts a weights vector and CPM/modularity selection."; ...
     "Conversion fills weights only when graph options request weighted input."], ...
    'VariableNames', {'source_path_at_v0_2_4', 'sha256', ...
    'installed_comparison', 'audit_finding'});

% Two K4 cliques joined by one bridge. At CPM gamma=0.05, a unit bridge
% favors one community, while a bridge of weight 0.01 favors two.
s = [1 1 1 2 2 3 5 5 5 6 6 7 4]';
t = [2 3 4 3 4 4 6 7 8 7 8 8 5]';
w = [ones(12, 1); 0.01];
unitW = ones(size(w));
n = 8;
gammaCpm = 0.05;
seed = 240724;
weightedGraph = graph(s, t, w, n);
unitGraph = graph(s, t, unitW, n);

weightedMembership = i_run_leiden( ...
    weightedGraph, seed, "cpm", gammaCpm, 2);
weightedMembershipRepeat = i_run_leiden( ...
    weightedGraph, seed, "cpm", gammaCpm, 2);
unitMembership = i_run_leiden(unitGraph, seed, "cpm", gammaCpm, 2);

[weightedOptimum, weightedBestMembership] = ...
    i_exact_best_partition(n, s, t, w, "cpm", gammaCpm);
[unitOptimum, unitBestMembership] = ...
    i_exact_best_partition(n, s, t, unitW, "cpm", gammaCpm);
weightedReturnedQuality = i_partition_quality( ...
    n, s, t, w, weightedMembership, "cpm", gammaCpm);
unitReturnedQuality = i_partition_quality( ...
    n, s, t, unitW, unitMembership, "cpm", gammaCpm);

knownTwo = [ones(4, 1); 2 * ones(4, 1)];
publicModularity = igraph.modularity(weightedGraph, knownTwo, 'resolution', 1);
independentWeightedModularity = i_partition_quality( ...
    n, s, t, w, knownTwo, "modularity", 1);
independentUnitModularity = i_partition_quality( ...
    n, s, t, unitW, knownTwo, "modularity", 1);

defaultModularityMembership = i_run_leiden( ...
    weightedGraph, seed, "modularity", 1, 2);
effectiveUnitTotalStrength = 2 * sum(unitW);
rescaledModularityMembership = i_run_leiden( ...
    weightedGraph, seed, "modularity", ...
    1 / effectiveUnitTotalStrength, 2);

FixtureAudit = table( ...
    ["weighted_cpm_partition"; "unit_weight_cpm_control"; ...
     "weighted_modularity_quality"; "unit_modularity_quality_control"; ...
     "documented_modularity_resolution_1"; ...
     "manually_rescaled_modularity_resolution"; ...
     "same_seed_exact_reproduction"], ...
    [gammaCpm; gammaCpm; 1; 1; 1; ...
     1 / effectiveUnitTotalStrength; gammaCpm], ...
    [i_membership_text(weightedMembership); ...
     i_membership_text(unitMembership); ...
     i_membership_text(knownTwo); ...
     i_membership_text(knownTwo); ...
     i_membership_text(defaultModularityMembership); ...
     i_membership_text(rescaledModularityMembership); ...
     i_membership_text(weightedMembershipRepeat)], ...
    [weightedReturnedQuality; unitReturnedQuality; ...
     publicModularity; publicModularity; NaN; NaN; ...
     weightedReturnedQuality], ...
    [weightedOptimum; unitOptimum; independentWeightedModularity; ...
     independentUnitModularity; NaN; NaN; weightedOptimum], ...
    [numel(unique(weightedMembership)); numel(unique(unitMembership)); ...
     2; 2; numel(unique(defaultModularityMembership)); ...
     numel(unique(rescaledModularityMembership)); ...
     numel(unique(weightedMembershipRepeat))], ...
    [false; true; false; true; false; true; ...
     isequal(weightedMembership, weightedMembershipRepeat)], ...
    ["Returned partition is optimal only after replacing the 0.01 bridge by unit weight."; ...
     "Returned partition equals the exact unit-weight CPM optimum."; ...
     "Public helper equals the independent unit-weight value, not the weighted value."; ...
     "Public helper agrees with independent unit-weight modularity."; ...
     "Resolution 1 returns singleton communities because the wrapper does not convert canonical modularity gamma."; ...
     "Dividing gamma by effective total strength recovers the expected two-community partition, but is undocumented and still unweighted."; ...
     "Twenty repeated calls after resetting MT19937 to the same seed were also identical."], ...
    'VariableNames', {'check_id', 'resolution_argument', ...
    'membership', 'adapter_or_returned_quality', ...
    'independent_reference_quality', 'n_communities', 'pass', 'evidence'});

% Exercise an ambiguous ring so deterministic equality is not merely due to
% a unique partition. Different seeds should explore different optima.
ringGraph = graph((1:20)', [2:20 1]');
sameSeed = true;
reference = [];
for repeat = 1:20
    one = i_run_leiden(ringGraph, seed, "cpm", 0.2, 2, 0.05);
    if repeat == 1
        reference = one;
    else
        sameSeed = sameSeed && isequal(reference, one);
    end
end
differentSeedMemberships = strings(5, 1);
for oneSeed = 1:5
    one = i_run_leiden(ringGraph, oneSeed, "cpm", 0.2, 2, 0.05);
    differentSeedMemberships(oneSeed) = i_membership_text(one);
end
nDistinctAcrossSeeds = numel(unique(differentSeedMemberships));

Capabilities = table( ...
    ["leiden_public_api"; "cpm_objective"; "modularity_objective"; ...
     "resolution_parameter"; "weighted_leiden_cpm"; ...
     "weighted_modularity_quality"; "explicit_rng_seed"; ...
     "fixed_iteration_count"; "iteration_to_convergence"; ...
     "same_seed_determinism"; "run09_backend_acceptance"], ...
    [true; hasCpm; hasModularity; hasResolution; ...
     clusterExposesGraphWeights; modularityExposesGraphWeights; ...
     hasExplicitRng; hasFixedIterations; hasConvergenceSentinel; ...
     sameSeed; false], ...
    [true; true; false; false; false; false; true; true; false; ...
     sameSeed && nDistinctAcrossSeeds > 1; false], ...
    [ ...
     "igraph.cluster exposes method='leiden'."
     "CPM is selectable and fixed-iteration execution succeeds."
     "The selector exists, but weights are omitted and canonical gamma is not rescaled before the low-level generalized objective."
     "CPM accepts resolution; modularity accepts it with incompatible public semantics."
     "Source and a discriminating runtime fixture show that the public wrapper passes an empty weight vector."
     "igraph.modularity returns the unit-weight result for a MATLAB graph with a Weight edge variable."
     "igraph.rng(seed,'mt19937') produced exact equality in 20 reset-and-repeat runs."
     "Positive integer nIterations values execute successfully."
     "The -1 sentinel is documented, but the eight-node probe failed to terminate within 120 seconds; it is not production-safe."
     "The same seed reproduced exactly while seeds 1:5 produced " + ...
         string(nDistinctAcrossSeeds) + " distinct ring partitions."
     "Rejected: run_09 requires weighted Leiden-CPM on the frozen weighted graph."
     ], ...
    'VariableNames', {'capability', 'declared_or_exposed', ...
    'validated_for_run09', 'evidence'});

Decision = table( ...
    "python_igraph_backend_retained", false, ...
    "matlab-igraph 0.2.4 public adapters do not preserve edge weights for clustering or modularity; the private MEX ABI is not an acceptable production contract.", ...
    "Do not route run_09 through igraph.cluster or igraph.modularity. Retain the independently versioned Python igraph adapter unless matlab-igraph is upgraded or patched and the full audit passes.", ...
    'VariableNames', {'decision_id', 'matlab_igraph_selected', ...
    'reason', 'required_action'});

paths = struct();
paths.environment = fullfile(outputDir, 'matlab_igraph_environment.csv');
paths.hashes = fullfile(outputDir, 'matlab_igraph_file_hashes.csv');
paths.licenses = fullfile(outputDir, 'matlab_igraph_license_audit.csv');
paths.upstream = fullfile(outputDir, 'matlab_igraph_upstream_source_audit.csv');
paths.fixtures = fullfile(outputDir, 'matlab_igraph_fixture_audit.csv');
paths.capabilities = fullfile(outputDir, 'matlab_igraph_capability_audit.csv');
paths.decision = fullfile(outputDir, 'matlab_igraph_backend_decision.csv');
writetable(Environment, paths.environment);
writetable(FileHashes, paths.hashes);
writetable(LicenseAudit, paths.licenses);
writetable(UpstreamSource, paths.upstream);
writetable(FixtureAudit, paths.fixtures);
writetable(Capabilities, paths.capabilities);
writetable(Decision, paths.decision);

sourcePath = string(mfilename('fullpath'));
if ~endsWith(sourcePath, ".m")
    sourcePath = sourcePath + ".m";
end
artifactPaths = [string(struct2cell(paths)); sourcePath];
artifactRoles = [ ...
    "runtime_environment"
    "installed_dependency_byte_identity"
    "license_provenance"
    "immutable_upstream_source_identity"
    "independent_objective_validation"
    "capability_gate"
    "backend_selection_decision"
    "validation_source"
    ];
rowCounts = [height(Environment); height(FileHashes); height(LicenseAudit); ...
    height(UpstreamSource); height(FixtureAudit); height(Capabilities); ...
    height(Decision); NaN];
sha256 = strings(numel(artifactPaths), 1);
for i = 1:numel(artifactPaths)
    sha256(i) = i_sha256(artifactPaths(i));
end
Manifest = table(string(get_filename(artifactPaths)), artifactRoles, ...
    rowCounts, sha256, ...
    'VariableNames', {'artifact_id', 'artifact_role', 'n_rows', 'sha256'});
manifestPath = fullfile(outputDir, 'matlab_igraph_validation_manifest.csv');
writetable(Manifest, manifestPath);

assert(~clusterExposesGraphWeights, ...
    'validate_matlab_igraph_backend:UnexpectedWeightedAPI', ...
    'The public API changed; update this audit before selecting a backend.');
assert(isequal(weightedMembership, unitMembership), ...
    'validate_matlab_igraph_backend:UnexpectedWeightSensitivity', ...
    'The installed adapter became weight-sensitive; update the backend decision.');
assert(weightedReturnedQuality < weightedOptimum - 1e-10, ...
    'validate_matlab_igraph_backend:WeightedFixtureNotDiscriminating', ...
    'The weighted CPM fixture no longer demonstrates the adapter defect.');
assert(abs(publicModularity - independentUnitModularity) < 1e-12);
assert(abs(publicModularity - independentWeightedModularity) > 1e-3);
assert(sameSeed && nDistinctAcrossSeeds > 1, ...
    'validate_matlab_igraph_backend:RngValidationFailed', ...
    'Explicit igraph RNG seeding did not pass the deterministic control.');

Audit = struct();
Audit.output_dir = outputDir;
Audit.environment = Environment;
Audit.file_hashes = FileHashes;
Audit.licenses = LicenseAudit;
Audit.upstream_source = UpstreamSource;
Audit.fixtures = FixtureAudit;
Audit.capabilities = Capabilities;
Audit.decision = Decision;
Audit.manifest = Manifest;
Audit.manifest_path = string(manifestPath);
Audit.weighted_exact_best_membership = weightedBestMembership;
Audit.unit_exact_best_membership = unitBestMembership;
end

function membership = i_run_leiden(graphInput, seed, metric, resolution, nIterations, randomness)
if nargin < 6
    randomness = 0.01;
end
igraph.rng(seed, 'mt19937');
membership = igraph.cluster(graphInput, 'leiden', ...
    'metric', char(metric), ...
    'resolution', resolution, ...
    'randomness', randomness, ...
    'nIterations', nIterations);
membership = i_canonical_membership(membership(:));
end

function membership = i_canonical_membership(membership)
membership = membership(:);
canonical = zeros(size(membership));
next = 0;
for i = 1:numel(membership)
    prior = find(membership(1:i - 1) == membership(i), 1, 'first');
    if isempty(prior)
        next = next + 1;
        canonical(i) = next;
    else
        canonical(i) = canonical(prior);
    end
end
membership = canonical;
end

function textValue = i_membership_text(membership)
textValue = join(string(i_canonical_membership(membership)), ";");
end

function [bestQuality, bestMembership] = i_exact_best_partition(n, s, t, w, metric, resolution)
partitions = 1;
for node = 2:n
    nNext = sum(max(partitions, [], 2) + 1);
    next = zeros(nNext, node);
    cursor = 0;
    for row = 1:size(partitions, 1)
        maxLabel = max(partitions(row, :));
        for label = 1:(maxLabel + 1)
            cursor = cursor + 1;
            next(cursor, 1:(node - 1)) = partitions(row, :);
            next(cursor, node) = label;
        end
    end
    partitions = next;
end

bestQuality = -Inf;
bestMembership = [];
for row = 1:size(partitions, 1)
    one = partitions(row, :)';
    q = i_partition_quality(n, s, t, w, one, metric, resolution);
    if q > bestQuality + 1e-12
        bestQuality = q;
        bestMembership = one;
    end
end
bestMembership = i_canonical_membership(bestMembership);
end

function quality = i_partition_quality(n, s, t, w, membership, metric, resolution)
membership = membership(:);
switch lower(string(metric))
    case "cpm"
        quality = sum(w(membership(s) == membership(t)));
        sizes = accumarray(membership, 1);
        quality = quality - resolution * sum(sizes .* (sizes - 1) / 2);
    case "modularity"
        totalWeight = sum(w);
        strength = accumarray([s; t], [w; w], [n, 1]);
        quality = 0;
        for community = unique(membership)'
            inCommunity = membership == community;
            internalWeight = sum(w(inCommunity(s) & inCommunity(t)));
            communityStrength = sum(strength(inCommunity));
            quality = quality + internalWeight / totalWeight - ...
                resolution * (communityStrength / (2 * totalWeight))^2;
        end
    otherwise
        error('validate_matlab_igraph_backend:BadMetric', ...
            'Unsupported independent quality metric: %s', metric);
end
end

function T = i_hash_files(rootPath, relativePaths, roles)
n = numel(relativePaths);
absolutePath = strings(n, 1);
bytes = zeros(n, 1);
sha256 = strings(n, 1);
for i = 1:n
    absolutePath(i) = fullfile(rootPath, relativePaths(i));
    assert(isfile(absolutePath(i)), ...
        'validate_matlab_igraph_backend:MissingInstalledFile', ...
        'Missing installed matlab-igraph file: %s', absolutePath(i));
    info = dir(absolutePath(i));
    bytes(i) = info.bytes;
    sha256(i) = i_sha256(absolutePath(i));
end
T = table(relativePaths, absolutePath, roles, bytes, sha256, ...
    'VariableNames', {'relative_path', 'absolute_path', 'file_role', ...
    'n_bytes', 'sha256'});
end

function value = i_sha256(pathText)
[fid, message] = fopen(pathText, 'rb');
assert(fid >= 0, 'validate_matlab_igraph_backend:HashOpenFailed', ...
    'Could not open %s: %s', pathText, message);
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
md = javaMethod('getInstance', 'java.security.MessageDigest', 'SHA-256');
while true
    bytes = fread(fid, 1024 * 1024, '*uint8');
    if isempty(bytes)
        break
    end
    md.update(typecast(bytes(:), 'int8'));
end
digest = typecast(md.digest(), 'uint8');
value = lower(string(reshape(dec2hex(digest, 2).', 1, [])));
end

function names = get_filename(paths)
names = strings(numel(paths), 1);
for i = 1:numel(paths)
    [~, stem, ext] = fileparts(paths(i));
    names(i) = stem + ext;
end
end
