function Validation = validate_run09_frozen_handoff(repoRoot, params, auditPath)
%VALIDATE_RUN09_FROZEN_HANDOFF Fail-closed validation of frozen run_08 inputs.
%
% This function must complete successfully before any matlab-igraph function
% or MEX dispatcher is called. It first validates byte identity and the
% handoff contract, then reads only the structural columns needed to validate
% and adapt the graph.

repoRoot = string(repoRoot);
auditPath = string(auditPath);
auditDir = string(fileparts(auditPath));
if ~isfolder(auditDir)
    mkdir(auditDir);
end

inputRoot = string(resolve_repo_path(repoRoot, params.input_dir));
paths = struct();
paths.manifest = fullfile(inputRoot, params.handoff_manifest_file);
paths.nodes = fullfile(inputRoot, params.node_input_file);
paths.edges = fullfile(inputRoot, params.edge_input_file);
paths.freeze = fullfile(inputRoot, params.freeze_config_file);
paths.topology = fullfile(inputRoot, params.topology_summary_file);

Audit = i_empty_audit();
pathNames = ["manifest"; "nodes"; "edges"; "freeze_config"; "topology"];
pathValues = [paths.manifest; paths.nodes; paths.edges; ...
    paths.freeze; paths.topology];
for i = 1:numel(pathNames)
    Audit = i_add(Audit, "file_exists_" + pathNames(i), ...
        "identity", "true", string(isfile(pathValues(i))), ...
        isfile(pathValues(i)), pathValues(i));
end
i_write(Audit, auditPath);
i_require(all(Audit.pass), ...
    'validate_run09_frozen_handoff:MissingRequiredFile', ...
    'One or more required frozen handoff files are missing.');

Manifest = i_read_all_text(paths.manifest);
requiredManifestColumns = ["artifact_id", "sha256", "file_bytes", ...
    "n_rows", "required_for_run09", "artifact_status", ...
    "consensus_freeze_id", "handoff_ready", "handoff_status", ...
    "run09_may_modify_edges", "hash_algorithm", "hash_scope", ...
    "manifest_schema_version"];
hasManifestColumns = all(ismember(requiredManifestColumns, ...
    string(Manifest.Properties.VariableNames)));
Audit = i_add(Audit, "manifest_required_columns", "identity", ...
    strjoin(requiredManifestColumns, ";"), ...
    strjoin(string(Manifest.Properties.VariableNames), ";"), ...
    hasManifestColumns, "Required manifest fields must all be present.");
i_write(Audit, auditPath);
i_require(hasManifestColumns, ...
    'validate_run09_frozen_handoff:BadManifestColumns', ...
    'The frozen handoff manifest is missing required fields.');

requiredMask = i_as_logical(Manifest.required_for_run09);
requiredRows = Manifest(requiredMask, :);
requiredIds = [params.edge_input_file; params.node_input_file; ...
    params.freeze_config_file; params.topology_summary_file];
requiredSetPass = height(requiredRows) == 4 && ...
    numel(unique(requiredRows.artifact_id)) == 4 && ...
    isempty(setxor(requiredRows.artifact_id, requiredIds));
Audit = i_add(Audit, "manifest_required_artifact_set", "identity", ...
    strjoin(sort(requiredIds), ";"), ...
    strjoin(sort(requiredRows.artifact_id), ";"), ...
    requiredSetPass, "Exactly four artifacts must be required for run_09.");

schemaPass = all(Manifest.manifest_schema_version == ...
    params.expected_manifest_schema);
Audit = i_add(Audit, "manifest_schema_version", "identity", ...
    params.expected_manifest_schema, ...
    strjoin(unique(Manifest.manifest_schema_version), ";"), schemaPass, ...
    "All manifest rows must use the byte-exact v2 schema.");
freezeIdPass = all(Manifest.consensus_freeze_id == ...
    params.expected_freeze_id);
Audit = i_add(Audit, "manifest_freeze_id", "identity", ...
    params.expected_freeze_id, ...
    strjoin(unique(Manifest.consensus_freeze_id), ";"), freezeIdPass, ...
    "The retired size-dependent freeze identifier is not accepted.");
readyPass = all(i_as_logical(requiredRows.handoff_ready)) && ...
    all(requiredRows.handoff_status == "ready_frozen_consensus_graph");
Audit = i_add(Audit, "manifest_readiness_flags", "identity", ...
    "handoff_ready=true;status=ready_frozen_consensus_graph", ...
    "handoff_ready=" + string(all(i_as_logical(requiredRows.handoff_ready))) + ...
    ";status=" + strjoin(unique(requiredRows.handoff_status), "|"), ...
    readyPass, "Every required artifact must declare a ready frozen graph.");
artifactStatusPass = all(requiredRows.artifact_status == ...
    "present_hashed_byte_exact");
Audit = i_add(Audit, "manifest_artifact_status", "identity", ...
    "present_hashed_byte_exact", ...
    strjoin(unique(requiredRows.artifact_status), ";"), ...
    artifactStatusPass, "Required artifacts must be byte-exact and present.");
immutablePass = all(~i_as_logical(requiredRows.run09_may_modify_edges));
Audit = i_add(Audit, "manifest_immutable_edge_flag", "identity", ...
    "false", string(any(i_as_logical(requiredRows.run09_may_modify_edges))), ...
    immutablePass, "No required artifact may authorize edge modification.");
hashContractPass = all(requiredRows.hash_algorithm == "SHA-256") && ...
    all(requiredRows.hash_scope == "exact_file_bytes");
Audit = i_add(Audit, "manifest_hash_contract", "identity", ...
    "SHA-256;exact_file_bytes", ...
    strjoin(unique(requiredRows.hash_algorithm + ";" + ...
    requiredRows.hash_scope), "|"), hashContractPass, ...
    "Hash identity must cover exact stored bytes.");

artifactIds = requiredIds;
artifactPaths = [paths.edges; paths.nodes; paths.freeze; paths.topology];
expectedHashes = [params.expected_edge_hash; params.expected_node_hash; ...
    params.expected_freeze_config_hash; params.expected_topology_hash];
actualHashes = strings(4, 1);
for i = 1:4
    rowMask = requiredRows.artifact_id == artifactIds(i);
    rowUnique = nnz(rowMask) == 1;
    if rowUnique
        manifestHash = lower(requiredRows.sha256(rowMask));
    else
        manifestHash = "";
    end
    actualHashes(i) = compute_file_sha256(artifactPaths(i));
    manifestPinnedPass = rowUnique && manifestHash == expectedHashes(i);
    Audit = i_add(Audit, "manifest_hash_" + ...
        erase(artifactIds(i), ".csv"), "identity", ...
        expectedHashes(i), manifestHash, manifestPinnedPass, ...
        "The manifest hash must equal the independently pinned config hash.");
    actualPass = actualHashes(i) == expectedHashes(i);
    Audit = i_add(Audit, "actual_hash_" + ...
        erase(artifactIds(i), ".csv"), "identity", ...
        expectedHashes(i), actualHashes(i), actualPass, ...
        "SHA-256 was recomputed from exact file bytes.");
    info = dir(artifactPaths(i));
    if rowUnique
        expectedBytes = double(requiredRows.file_bytes(rowMask));
    else
        expectedBytes = NaN;
    end
    Audit = i_add(Audit, "file_bytes_" + ...
        erase(artifactIds(i), ".csv"), "identity", ...
        string(expectedBytes), string(info.bytes), ...
        rowUnique && info.bytes == expectedBytes, ...
        "Stored byte count must agree with the frozen manifest.");
end

derivedFreezeId = "run08_consensus_" + ...
    extractBefore(actualHashes(1), 13) + "_" + ...
    extractBefore(actualHashes(3), 9);
Audit = i_add(Audit, "independently_derived_freeze_id", "identity", ...
    params.expected_freeze_id, derivedFreezeId, ...
    derivedFreezeId == params.expected_freeze_id, ...
    "Freeze ID is derived from edge and freeze-config byte hashes.");

identityPass = all(Audit.pass(Audit.stage == "identity"));
if ~identityPass
    Audit = i_add(Audit, "structural_validation_executed", ...
        "structural", "true", "false", false, ...
        "Structural reads were blocked by the byte-identity gate.");
    i_write(Audit, auditPath);
    error('validate_run09_frozen_handoff:IdentityMismatch', ...
        ['Frozen run_08 byte identity or readiness differs from the pinned ' ...
         'run_09 contract. No graph backend was called.']);
end

Freeze = i_read_all_text(paths.freeze);
Topology = i_read_all_text(paths.topology);
nodeColumns = ["graph_node_id", "scale_index", "chunk_sec", ...
    "consensus_stable_induced_degree", "consensus_weighted_degree"];
edgeColumns = ["source_node_id", "target_node_id", ...
    "consensus_edge_weight"];
[Nodes, allNodeColumns] = i_read_selected(paths.nodes, nodeColumns);
[Edges, allEdgeColumns] = i_read_selected(paths.edges, edgeColumns);

forbiddenColumns = ["condition_id", "cohort_id", "group_id", "drug", ...
    "genotype", "perturbation", "treatment", "outcome", "response", ...
    "arena_id", "arena_label", "session_id", "session_index", ...
    "rare_stratum", "annotation", "umap_1", "umap_2", "umap_3"];
nodeForbidden = intersect(lower(allNodeColumns), forbiddenColumns);
edgeForbidden = intersect(lower(allEdgeColumns), forbiddenColumns);
Audit = i_add(Audit, "forbidden_partition_columns_absent", ...
    "structural", "none", ...
    strjoin([nodeForbidden edgeForbidden], ";"), ...
    isempty(nodeForbidden) && isempty(edgeForbidden), ...
    "Only identity scale provenance and graph topology fields are permitted.");

nodeCountPass = height(Nodes) == params.expected_n_nodes;
edgeCountPass = height(Edges) == params.expected_n_edges;
Audit = i_add(Audit, "node_count", "structural", ...
    string(params.expected_n_nodes), string(height(Nodes)), ...
    nodeCountPass, "Frozen stable-node row count.");
Audit = i_add(Audit, "edge_count", "structural", ...
    string(params.expected_n_edges), string(height(Edges)), ...
    edgeCountPass, "Frozen unique undirected-edge row count.");

manifestRowCountsPass = true;
rowCounts = [height(Edges); height(Nodes); height(Freeze); height(Topology)];
for i = 1:4
    rowMask = requiredRows.artifact_id == artifactIds(i);
    expectedRows = double(requiredRows.n_rows(rowMask));
    onePass = isscalar(expectedRows) && rowCounts(i) == expectedRows;
    manifestRowCountsPass = manifestRowCountsPass && onePass;
    Audit = i_add(Audit, "manifest_rows_" + ...
        erase(artifactIds(i), ".csv"), "structural", ...
        string(expectedRows), string(rowCounts(i)), onePass, ...
        "Parsed row count must equal the frozen manifest.");
end

nodeIds = double(Nodes.graph_node_id);
nodeIdentityPass = all(isfinite(nodeIds)) && all(nodeIds > 0) && ...
    all(nodeIds == floor(nodeIds)) && numel(unique(nodeIds)) == numel(nodeIds);
Audit = i_add(Audit, "node_identity_unique_positive_integer", ...
    "structural", "true", string(nodeIdentityPass), ...
    nodeIdentityPass, "Every frozen graph_node_id must occur exactly once.");

sourceIds = double(Edges.source_node_id);
targetIds = double(Edges.target_node_id);
weights = double(Edges.consensus_edge_weight);
[sourceMember, sourceIndex] = ismember(sourceIds, nodeIds);
[targetMember, targetIndex] = ismember(targetIds, nodeIds);
endpointPass = all(sourceMember) && all(targetMember);
Audit = i_add(Audit, "edge_endpoint_membership", "structural", ...
    "all endpoints in frozen node set", ...
    "missing_source=" + string(nnz(~sourceMember)) + ...
    ";missing_target=" + string(nnz(~targetMember)), endpointPass, ...
    "Every edge endpoint must map to one stable frozen node.");

orientationPass = all(sourceIds < targetIds);
uniqueEdgePass = height(unique([sourceIds targetIds], 'rows')) == ...
    height(Edges);
Audit = i_add(Audit, "edge_orientation_source_less_than_target", ...
    "structural", "true", string(orientationPass), ...
    orientationPass, "Frozen edges must be canonical undirected pairs.");
Audit = i_add(Audit, "edge_pair_uniqueness", "structural", ...
    string(height(Edges)), ...
    string(height(unique([sourceIds targetIds], 'rows'))), ...
    uniqueEdgePass, "No undirected edge may occur more than once.");

weightPass = all(isfinite(weights)) && all(weights > 0);
Audit = i_add(Audit, "finite_positive_edge_weights", "structural", ...
    "all finite and >0", ...
    "nonfinite=" + string(nnz(~isfinite(weights))) + ...
    ";nonpositive=" + string(nnz(weights <= 0)), ...
    weightPass, "Consensus weights must be finite positive numeric values.");

safeForTopology = nodeCountPass && edgeCountPass && nodeIdentityPass && ...
    endpointPass && orientationPass && uniqueEdgePass && weightPass;
if safeForTopology
    n = height(Nodes);
    degree = accumarray([sourceIndex; targetIndex], 1, [n 1]);
    weightedDegree = accumarray([sourceIndex; targetIndex], ...
        [weights; weights], [n 1]);
    G = graph(sourceIndex, targetIndex, [], n);
    componentId = conncomp(G);
    nComponents = numel(unique(componentId));
    minimumDegree = min(degree);
    degreeStoredPass = isequal(degree, ...
        double(Nodes.consensus_stable_induced_degree));
    weightedStored = double(Nodes.consensus_weighted_degree);
    weightedDegreeStoredPass = all(isfinite(weightedDegree));
    weightedDegreeMaximumDelta = max(abs(weightedDegree - weightedStored));
else
    degree = [];
    weightedDegree = [];
    nComponents = NaN;
    minimumDegree = NaN;
    degreeStoredPass = false;
    weightedDegreeStoredPass = false;
    weightedDegreeMaximumDelta = NaN;
end
Audit = i_add(Audit, "connected_components", "structural", ...
    string(params.expected_n_components), string(nComponents), ...
    nComponents == params.expected_n_components, ...
    "Connectivity is recomputed from the frozen induced edge list.");
Audit = i_add(Audit, "minimum_induced_degree", "structural", ...
    string(params.expected_minimum_degree), string(minimumDegree), ...
    minimumDegree == params.expected_minimum_degree, ...
    "Degree is recomputed without using run_08 audit columns.");
Audit = i_add(Audit, "stored_degree_recomputation", "structural", ...
    "exact agreement", string(degreeStoredPass), degreeStoredPass, ...
    "Stored stable induced degree must equal edge-list recomputation.");
Audit = i_add(Audit, "induced_weighted_degree_recomputed", ...
    "structural", "all finite", ...
    "all_finite=" + string(weightedDegreeStoredPass) + ...
    ";maximum_delta_vs_precore_audit_column=" + ...
    compose('%.17g', weightedDegreeMaximumDelta), ...
    weightedDegreeStoredPass, ...
    "The adapter uses only induced edge-list recomputation. The node " + ...
    "consensus_weighted_degree column is pre-core audit provenance and is not used.");

freezeReady = i_freeze_value(Freeze, "handoff_ready") == "true";
freezeLabels = i_freeze_value(Freeze, "labels_used_for_consensus") == "none";
freezeMotifs = i_freeze_value(Freeze, "motifs_defined_in_run08") == "false";
freezeMinDegree = str2double(i_freeze_value(Freeze, "stable_min_degree"));
freezeContractPass = freezeReady && freezeLabels && freezeMotifs && ...
    freezeMinDegree == params.expected_minimum_degree;
Audit = i_add(Audit, "freeze_config_readiness_contract", "structural", ...
    "ready;labels=none;motifs=false;min_degree=10", ...
    "ready=" + string(freezeReady) + ";labels_none=" + ...
    string(freezeLabels) + ";motifs_false=" + string(freezeMotifs) + ...
    ";min_degree=" + string(freezeMinDegree), freezeContractPass, ...
    "Freeze-config readiness and scientific-role flags are immutable.");

topologyPass = height(Topology) == 1 && ...
    double(Topology.n_run09_stable_nodes) == params.expected_n_nodes && ...
    double(Topology.n_run09_stable_edges) == params.expected_n_edges && ...
    double(Topology.minimum_run09_stable_induced_degree) == ...
        params.expected_minimum_degree && ...
    double(Topology.n_components) == params.expected_n_components && ...
    i_as_logical(Topology.handoff_ready) && ...
    i_as_logical(Topology.all_handoff_gates_pass) && ...
    i_as_logical(Topology.selected_for_frozen_handoff) && ...
    string(Topology.handoff_status) == "ready_frozen_consensus_graph";
Audit = i_add(Audit, "topology_summary_readiness_contract", ...
    "structural", "counts and all readiness gates pass", ...
    "pass=" + string(topologyPass), topologyPass, ...
    "Frozen topology summary must agree with independent recomputation.");
Audit = i_add(Audit, "structural_validation_executed", ...
    "structural", "true", "true", true, ...
    "Byte identity passed before structural graph validation.");

i_write(Audit, auditPath);
allPass = all(Audit.pass);
i_require(allPass, ...
    'validate_run09_frozen_handoff:StructuralMismatch', ...
    ['Frozen run_08 graph structure differs from the pinned contract. ' ...
     'No graph backend was called.']);

Validation = struct();
Validation.pass = allPass;
Validation.freeze_id = params.expected_freeze_id;
Validation.input_root = inputRoot;
Validation.audit = Audit;
Validation.audit_path = auditPath;
Validation.manifest = Manifest;
Validation.nodes = Nodes;
Validation.edges = Edges;
Validation.degree = degree;
Validation.weighted_degree = weightedDegree;
Validation.actual_hashes = table(artifactIds, actualHashes, ...
    'VariableNames', {'artifact_id', 'sha256'});
end

function [T, allColumns] = i_read_selected(pathText, selectedColumns)
opts = detectImportOptions(pathText, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
opts.DataLines = [2 Inf];
opts.VariableNamesLine = 1;
opts.VariableUnitsLine = 0;
allColumns = string(opts.VariableNames);
missing = setdiff(selectedColumns, allColumns);
assert(isempty(missing), ...
    'validate_run09_frozen_handoff:MissingInputColumn', ...
    'Input %s is missing required fields: %s', ...
    pathText, strjoin(missing, ', '));
opts.SelectedVariableNames = cellstr(selectedColumns);
T = readtable(pathText, opts);
end

function T = i_read_all_text(pathText)
opts = detectImportOptions(pathText, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
opts.DataLines = [2 Inf];
opts.VariableNamesLine = 1;
opts.VariableUnitsLine = 0;
opts = setvartype(opts, opts.VariableNames, 'string');
T = readtable(pathText, opts);
end

function value = i_freeze_value(T, parameter)
mask = string(T.parameter) == string(parameter);
assert(nnz(mask) == 1, ...
    'validate_run09_frozen_handoff:BadFreezeConfig', ...
    'Freeze config parameter %s must occur exactly once.', parameter);
value = lower(strtrim(string(T.effective_value(mask))));
end

function values = i_as_logical(valuesIn)
if islogical(valuesIn)
    values = valuesIn;
elseif isnumeric(valuesIn)
    values = valuesIn ~= 0;
else
    text = lower(strtrim(string(valuesIn)));
    valid = ismember(text, ["1", "0", "true", "false", "yes", "no"]);
    assert(all(valid), ...
        'validate_run09_frozen_handoff:BadLogicalValue', ...
        'Handoff logical field contains invalid values.');
    values = ismember(text, ["1", "true", "yes"]);
end
values = logical(values);
end

function Audit = i_empty_audit()
Audit = table(strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), false(0, 1), strings(0, 1), ...
    'VariableNames', {'check_id', 'stage', 'expected_value', ...
    'observed_value', 'pass', 'details'});
end

function Audit = i_add(Audit, checkId, stage, expected, observed, pass, details)
one = table(string(checkId), string(stage), string(expected), ...
    string(observed), logical(pass), string(details), ...
    'VariableNames', Audit.Properties.VariableNames);
Audit = [Audit; one];
end

function i_write(Audit, auditPath)
writetable(Audit, auditPath);
end

function i_require(condition, identifier, message)
if ~condition
    error(identifier, '%s', message);
end
end
