function audit = local_empty_audit()
audit = struct( ...
    'badframe_fraction', NaN, ...
    'n_prediction_issue_animal_frames', NaN, ...
    'n_interpolated_prediction_issue_animal_frames', NaN, ...
    'n_usable_prediction_issue_animal_frames', NaN, ...
    'n_repaired_prediction_issue_animal_frames', NaN, ...
    'n_unresolved_prediction_issue_animal_frames', NaN, ...
    'prediction_issue_fraction', NaN, ...
    'interpolated_prediction_issue_fraction', NaN, ...
    'usable_prediction_issue_fraction', NaN, ...
    'repaired_prediction_issue_fraction', NaN, ...
    'unresolved_prediction_issue_fraction', NaN, ...
    'prediction_issue_usable_rate', NaN, ...
    'prediction_issue_repair_rate', NaN, ...
    'prediction_issue_unresolved_rate', NaN, ...
    'n_prediction_issue_frames_any_animal', NaN, ...
    'n_repaired_prediction_issue_frames_any_animal', NaN, ...
    'n_unresolved_prediction_issue_frames_any_animal', NaN, ...
    'prediction_issue_any_animal_fraction', NaN, ...
    'repaired_prediction_issue_any_animal_fraction', NaN, ...
    'unresolved_prediction_issue_any_animal_fraction', NaN);
end