function nodeSummary = summarize_node_qc(qcAnimal)
%SUMMARIZE_NODE_QC Summarize node-level QC fractions.

nNodes = size(qcAnimal.finalNanMask, 2);
nodeSummary = table((1:nNodes)', ...
    mean(full(qcAnimal.lowConfMask), 1)', ...
    mean(full(qcAnimal.jumpMask), 1)', ...
    mean(full(qcAnimal.interpMask), 1)', ...
    mean(full(qcAnimal.geomMask), 1)', ...
    mean(full(qcAnimal.arenaMask), 1)', ...
    mean(full(qcAnimal.finalNanMask), 1)', ...
    'VariableNames', {'node','fracLowConf','fracJump','fracInterp','fracGeom','fracArena','fracFinalNaN'});
end
