function tests = test_scale_usefulness_basic()
%TEST_SCALE_USEFULNESS_BASIC Basic tests for scale-usefulness scoring.
tests = functiontests(localfunctions);
end

function testScoreLayerRuns(testCase)
dyad = i_make_mock_dyad(1200, 80);
ChunkSet = build_multiscale_chunk_dataset({dyad}, ...
    'useLogScaleBank', true, ...
    'minScaleSec', 0.2, ...
    'maxScaleSec', 4.0, ...
    'nScales', 12, ...
    'strideSec', 0.1, ...
    'anchorMode', 'center', ...
    'minValidFrac', 0.90);

ScaleScore = score_multiscale_chunk_bank(ChunkSet, ...
    'nPCs', 4, ...
    'nClusters', 5, ...
    'maxChunksPerScale', 1200, ...
    'verbose', false);

verifyTrue(testCase, isfield(ScaleScore, 'scaleTable'));
verifyEqual(testCase, height(ScaleScore.scaleTable), 12);
verifyTrue(testCase, height(ScaleScore.selectedTable) >= 3);
end

function testValidateLayerRuns(testCase)
dyad = i_make_mock_dyad(1000, 80);
ChunkSet = build_multiscale_chunk_dataset({dyad}, ...
    'useLogScaleBank', true, ...
    'minScaleSec', 0.2, ...
    'maxScaleSec', 3.0, ...
    'nScales', 10, ...
    'strideSec', 0.1, ...
    'anchorMode', 'center', ...
    'minValidFrac', 0.90);

ScaleScore = score_multiscale_chunk_bank(ChunkSet, ...
    'nPCs', 4, ...
    'nClusters', 4, ...
    'maxChunksPerScale', 1000, ...
    'verbose', false);

Report = validate_scale_usefulness_scores(ScaleScore, 'makePlots', false, 'verbose', false);
verifyTrue(testCase, Report.isValid);
end

function dyad = i_make_mock_dyad(T, fps)
[featureNames, featureMeta] = default_dyad_feature_metadata();
time_s = (0:T-1)' ./ fps;
X = zeros(T, numel(featureNames));
for f = 1:numel(featureNames)
    if featureMeta.IsBoolean(f)
        x = double(rand(T,1) > 0.7);
    elseif featureMeta.IsCircular(f)
        x = mod(cumsum(randn(T,1) * 5), 360) - 180;
    elseif string(featureMeta.TransformHint{f}) == "log1p"
        x = abs(40 + cumsum(randn(T,1) * 0.5));
    else
        x = cumsum(randn(T,1) * 0.15);
    end
    X(:,f) = x;
end
raw = struct();
for f = 1:numel(featureNames)
    raw.(featureNames{f}) = X(:,f);
end
frameMask = true(T,1);
frameMask(randperm(T, round(0.03*T))) = false;
dyad = struct('time_s', time_s, 'fps', fps, 'X', X, ...
    'featureNames', {featureNames}, 'featureMeta', featureMeta, ...
    'raw', raw, 'frameMask', frameMask);
end
