function Audit = analyze_run10_graph_behavior_correspondence( ...
        Validation, Coherence, ReviewSummary, params)
%ANALYZE_RUN10_GRAPH_BEHAVIOR_CORRESPONDENCE Post-validation audit only.

candidateIds = Validation.candidate_ids;
[a,ia] = ismember(candidateIds,Coherence.motif_candidate_id);
[b,ib] = ismember(candidateIds,ReviewSummary.motif_candidate_id);
[c,ic] = ismember(candidateIds,string( ...
    Validation.topology.motif_candidate_id));
assert(all(a&b&c), ...
    'analyze_run10_graph_behavior_correspondence:MissingCandidate', ...
    'Graph-behavior audit inputs must cover all candidates.');

graphStability = double(Validation.topology.mean_node_stability(ic));
boundaryFraction = double(Validation.topology.boundary_node_fraction(ic));
conductance = double(Validation.topology.weighted_conductance(ic));
behaviorCoherence = double(Coherence. ...
    relative_dispersion_improvement(ia));
blindedAmbiguity = double(ReviewSummary.mean_tile_ambiguity_score(ib));
eligible = logical(Validation.topology. ...
    eligible_for_behavioral_interpretation(ic));
rhoStability = i_spearman(graphStability(eligible), ...
    behaviorCoherence(eligible));
rhoConductance = i_spearman(conductance(eligible), ...
    behaviorCoherence(eligible));
rhoBoundaryHuman = i_spearman(boundaryFraction(eligible), ...
    blindedAmbiguity(eligible));

Audit = table(candidateIds,graphStability,boundaryFraction,conductance, ...
    behaviorCoherence,blindedAmbiguity,eligible, ...
    repmat(rhoStability,numel(candidateIds),1), ...
    repmat(rhoConductance,numel(candidateIds),1), ...
    repmat(rhoBoundaryHuman,numel(candidateIds),1), ...
    repmat("post_validation_audit_only",numel(candidateIds),1), ...
    repmat(false,numel(candidateIds),1), ...
    repmat(params.expected_membership_sha256,numel(candidateIds),1), ...
    repmat("none",numel(candidateIds),1), ...
    'VariableNames', {'motif_candidate_id','run09_mean_node_stability', ...
    'run09_boundary_node_fraction','run09_weighted_conductance', ...
    'independent_behavioral_coherence_effect', ...
    'blinded_mean_ambiguity_score', ...
    'run09_graph_interpretation_eligible', ...
    'eligible_spearman_graph_stability_vs_behavior_coherence', ...
    'eligible_spearman_conductance_vs_behavior_coherence', ...
    'eligible_spearman_boundary_vs_blinded_ambiguity', ...
    'analysis_role','used_for_validation_status', ...
    'frozen_membership_sha256','experimental_labels_used'});
end

function value = i_spearman(a,b)
ok = isfinite(a)&isfinite(b);
if nnz(ok)<3
    value = NaN;
    return
end
ra = i_rank(a(ok));
rb = i_rank(b(ok));
C = corrcoef(ra,rb);
value = C(1,2);
end

function r = i_rank(x)
[s,order] = sort(x);
r = zeros(size(x));
i = 1;
while i<=numel(s)
    j = i;
    while j<numel(s) && s(j+1)==s(i)
        j = j+1;
    end
    r(order(i:j)) = mean(i:j);
    i = j+1;
end
end
