function Status = assign_run10_behavioral_validation_status( ...
        Validation, Coherence, Heldout, CrossSession, CrossScale, ...
        ReviewSummary, params)
%ASSIGN_RUN10_BEHAVIORAL_VALIDATION_STATUS Apply frozen v1 rules only.

candidateIds = Validation.candidate_ids;
n = numel(candidateIds);
[a,ia] = ismember(candidateIds,Coherence.motif_candidate_id);
[b,ib] = ismember(candidateIds,Heldout.motif_candidate_id);
[c,ic] = ismember(candidateIds,CrossSession.motif_candidate_id);
[d,id] = ismember(candidateIds,CrossScale.motif_candidate_id);
[e,ie] = ismember(candidateIds,ReviewSummary.motif_candidate_id);
[tf,loc] = ismember(candidateIds,string( ...
    Validation.topology.motif_candidate_id));
assert(all(tf), ...
    'assign_run10_behavioral_validation_status:TopologyMismatch', ...
    'Topology rows are incomplete.');
eligible = logical(Validation.topology. ...
    eligible_for_behavioral_interpretation(loc));
assert(all(a&c&d&e) && all(b(eligible)), ...
    'assign_run10_behavioral_validation_status:MissingCandidateMetric', ...
    'Every frozen candidate requires its applicable status input rows.');

coherencePass = logical(Coherence.coherence_primary_gate_pass(ia));
heldoutPass = false(n,1);
heldoutSufficient = false(n,1);
heldoutPass(b) = logical(Heldout.heldout_primary_gate_pass(ib(b)));
heldoutSufficient(b) = logical(Heldout.sufficient_evidence(ib(b)));
sessionPass = logical(CrossSession.cross_session_primary_gate_pass(ic));
coherenceSufficient = logical(Coherence.sufficient_evidence(ia));
sessionSufficient = logical(CrossSession.sufficient_evidence(ic));
primaryGateCount = double(coherencePass)+double(heldoutPass)+ ...
    double(sessionPass);

allSufficient = coherenceSufficient & heldoutSufficient & sessionSufficient;
automated = repmat("not_evaluated_run09_residual",n,1);
automated(eligible & ~allSufficient) = "insufficient_evidence";
automated(eligible & allSufficient & primaryGateCount >= ...
    params.supported_required_primary_gates) = "behaviorally_supported";
automated(eligible & allSufficient & primaryGateCount == ...
    params.partial_required_primary_gates) = "partially_supported";
automated(eligible & allSufficient & primaryGateCount < ...
    params.partial_required_primary_gates) = "not_supported";
paperClaimAllowed = repmat(params.run_mode=="full",n,1);
if params.run_mode=="smoke"
    automated(eligible) = "smoke_only_not_for_paper_claim";
end

human = string(ReviewSummary.blinded_review_status(ie));
concordance = repmat("not_applicable_run09_residual",n,1);
for i = find(eligible)'
    if human(i)=="awaiting_ratings" || human(i)=="insufficient_ratings"
        concordance(i) = human(i);
    else
        automatedPositive = any(automated(i)== ...
            ["behaviorally_supported","partially_supported"]);
        humanPositive = any(human(i)== ...
            ["blinded_review_supported", ...
             "coherent_but_agreement_below_rule"]);
        if automatedPositive==humanPositive
            concordance(i) = "automated_human_concordant";
        else
            concordance(i) = "automated_human_discordant";
        end
    end
end

Status = table(candidateIds,eligible,coherencePass,heldoutPass, ...
    sessionPass,primaryGateCount,allSufficient,automated,human, ...
    concordance,string(CrossScale.cross_scale_status(id)), ...
    repmat(params.run_mode,n,1),paperClaimAllowed, ...
    repmat(params.validation_status_rule_version,n,1), ...
    repmat("membership_candidate_ids_hierarchy_and_run09_eligibility_immutable", ...
    n,1),repmat(params.expected_candidate_freeze_id,n,1), ...
    repmat(params.expected_membership_sha256,n,1), ...
    repmat("none",n,1), ...
    'VariableNames', {'motif_candidate_id', ...
    'run09_graph_interpretation_eligible','coherence_gate_pass', ...
    'heldout_discriminability_gate_pass','cross_session_gate_pass', ...
    'primary_gate_count','all_primary_evidence_sufficient', ...
    'run10_validation_status','blinded_review_status', ...
    'automated_human_concordance','cross_scale_audit_status', ...
    'execution_mode','paper_claim_allowed', ...
    'validation_status_rule_version','membership_invariance_policy', ...
    'candidate_freeze_id','frozen_membership_sha256', ...
    'experimental_labels_used'});
assert(height(Status)==params.expected_candidate_count && ...
    numel(unique(Status.motif_candidate_id))==height(Status) && ...
    all(Status.run10_validation_status(~eligible)== ...
    "not_evaluated_run09_residual") && ...
    (params.run_mode=="full" || ~any(Status.paper_claim_allowed)), ...
    'assign_run10_behavioral_validation_status:StatusContractFailure', ...
    'Run_10 status assignment violated the frozen candidate scope.');
end
