function Sample = build_run10_validation_sample_manifest( ...
        repoRoot, params, Validation, Registry)
%BUILD_RUN10_VALIDATION_SAMPLE_MANIFEST Value-blind deterministic node sample.

assert(Validation.membership_sha256 == params.expected_membership_sha256 && ...
    all(Registry.included_in_primary_validation), ...
    'build_run10_validation_sample_manifest:GateNotPassed', ...
    'Freeze and feature-lineage gates must pass before sampling.');
repoRoot = string(repoRoot);

Node = i_read_selected(resolve_repo_path(repoRoot, ...
    params.run08_node_manifest_file), ...
    ["graph_node_id","embedding_row_id","scale_index","chunk_sec", ...
     "session_index","session_id","raw_index","anchor_frame", ...
     "anchor_time_s"]);
Membership = Validation.membership(:, ...
    {'graph_node_id','motif_candidate_id'});
Sample = innerjoin(Membership, Node, 'Keys', 'graph_node_id');
assert(height(Sample) == height(Membership), ...
    'build_run10_validation_sample_manifest:MissingNodeProvenance', ...
    'Every frozen member requires safe-column run_08 provenance.');

Topology = Validation.topology(:, ...
    {'motif_candidate_id','candidate_local_index', ...
     'eligible_for_behavioral_interpretation'});
Sample = innerjoin(Sample, Topology, 'Keys', 'motif_candidate_id');
assert(height(Sample) == height(Membership), ...
    'build_run10_validation_sample_manifest:MissingTopology', ...
    'Every frozen member requires graph-only eligibility provenance.');

Qc = i_read_selected(resolve_repo_path(repoRoot, ...
    params.preprocess_qc_file), ...
    ["raw_index","session_id","n_frames","preprocess_output_file", ...
     "preprocess_success"]);
assert(numel(unique(Qc.raw_index)) == height(Qc), ...
    'build_run10_validation_sample_manifest:DuplicateQcRow', ...
    'Preprocessing QC requires one row per raw index.');
[present, loc] = ismember(Sample.raw_index, Qc.raw_index);
assert(all(present) && all(logical(Qc.preprocess_success(loc))), ...
    'build_run10_validation_sample_manifest:PoseProvenanceFailure', ...
    'Every frozen node requires a successful preprocessing file.');
assert(all(string(Sample.session_id) == string(Qc.session_id(loc))), ...
    'build_run10_validation_sample_manifest:SessionMismatch', ...
    'Run_08 and preprocessing safe session identities differ.');
Sample.preprocess_output_file = string(Qc.preprocess_output_file(loc));
Sample.source_frame_count = double(Qc.n_frames(loc));
assert(all(Sample.anchor_frame >= 1 & ...
    Sample.anchor_frame <= Sample.source_frame_count), ...
    'build_run10_validation_sample_manifest:AnchorOutOfBounds', ...
    'A frozen anchor lies outside its pose source.');

Sample = sortrows(Sample, {'motif_candidate_id','session_index', ...
    'scale_index','anchor_time_s','graph_node_id'});
Sample.in_smoke_session_panel = true(height(Sample), 1);
if isfinite(params.active_smoke_session_count)
    sessions = sort(unique(Sample.session_index));
    nKeep = min(numel(sessions), params.active_smoke_session_count);
    idx = unique(round(linspace(1, numel(sessions), nKeep)));
    selectedSessions = sessions(idx);
    Sample.in_smoke_session_panel = ismember( ...
        Sample.session_index, selectedSessions);
end

Sample.sample_selected = false(height(Sample), 1);
Sample.sample_exclusion_reason = repmat("cell_cap_or_anchor_separation", ...
    height(Sample), 1);
groups = findgroups(string(Sample.motif_candidate_id), ...
    Sample.session_index, Sample.scale_index);
for g = 1:max(groups)
    rows = find(groups == g & Sample.in_smoke_session_panel);
    if isempty(rows)
        continue
    end
    lastTime = -Inf;
    nSelected = 0;
    for j = 1:numel(rows)
        row = rows(j);
        if nSelected >= params.active_maximum_rows_per_cell
            break
        end
        if Sample.anchor_time_s(row) - lastTime + eps >= ...
                params.minimum_anchor_separation_sec
            Sample.sample_selected(row) = true;
            Sample.sample_exclusion_reason(row) = "selected";
            lastTime = Sample.anchor_time_s(row);
            nSelected = nSelected + 1;
        end
    end
end
Sample.sample_exclusion_reason(~Sample.in_smoke_session_panel) = ...
    "not_in_smoke_session_panel";

Sample.selection_rule = repmat( ...
    "sorted_graph_node_provenance_then_fixed_time_separation_and_cell_cap", ...
    height(Sample), 1);
Sample.maximum_rows_per_candidate_session_scale = repmat( ...
    params.active_maximum_rows_per_cell, height(Sample), 1);
Sample.minimum_anchor_separation_sec = repmat( ...
    params.minimum_anchor_separation_sec, height(Sample), 1);
Sample.candidate_freeze_id = repmat( ...
    params.expected_candidate_freeze_id, height(Sample), 1);
Sample.frozen_membership_sha256 = repmat( ...
    params.expected_membership_sha256, height(Sample), 1);
Sample.candidate_id_used_as_validation_target_only = true( ...
    height(Sample), 1);
Sample.session_used_for_blocking_and_sampling_only = true( ...
    height(Sample), 1);
Sample.scale_used_for_stratification_and_audit_only = true( ...
    height(Sample), 1);
Sample.experimental_labels_used = repmat("none", height(Sample), 1);
Sample.arena_used_for_sampling = false(height(Sample), 1);
Sample.graph_stability_used_for_sampling = false(height(Sample), 1);
Sample.annotation_used_for_sampling = false(height(Sample), 1);
Sample.visual_appearance_used_for_sampling = false(height(Sample), 1);

assert(any(Sample.sample_selected), ...
    'build_run10_validation_sample_manifest:EmptySample', ...
    'Deterministic validation sampling selected no nodes.');
assert(all(Sample.experimental_labels_used == "none") && ...
    ~any(Sample.arena_used_for_sampling) && ...
    ~any(Sample.graph_stability_used_for_sampling) && ...
    ~any(Sample.annotation_used_for_sampling) && ...
    ~any(Sample.visual_appearance_used_for_sampling), ...
    'build_run10_validation_sample_manifest:FirewallFailure', ...
    'Forbidden metadata cannot enter validation sampling.');
end

function T = i_read_selected(pathText, names)
opts = detectImportOptions(pathText, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
missing = setdiff(names, string(opts.VariableNames));
assert(isempty(missing), ...
    'build_run10_validation_sample_manifest:MissingColumn', ...
    'Input %s lacks columns: %s', pathText, strjoin(missing, ', '));
opts.SelectedVariableNames = cellstr(names);
T = readtable(pathText, opts);
end
