function [Registry, OverlapAudit] = ...
        build_run10_validation_feature_registry(repoRoot, params, Validation)
%BUILD_RUN10_VALIDATION_FEATURE_REGISTRY Freeze lineage before measurements.
%
% This function inventories discovery feature names and transformations but
% never reads their candidate-specific values.

assert(Validation.membership_sha256 == params.expected_membership_sha256, ...
    'build_run10_validation_feature_registry:FreezeNotValidated', ...
    'The candidate freeze must pass before lineage construction.');
repoRoot = string(repoRoot);

run05Path = string(resolve_repo_path(repoRoot, ...
    params.run05_feature_dictionary_file));
run06TransformPath = string(resolve_repo_path(repoRoot, ...
    params.run06_transform_audit_file));
run06EventPath = string(resolve_repo_path(repoRoot, ...
    params.run06_event_summary_file));
run07Path = string(resolve_repo_path(repoRoot, ...
    params.run07_feature_dictionary_file));
sourcePaths = [run05Path; run06TransformPath; run06EventPath; run07Path];
sourceHashes = strings(size(sourcePaths));
for i = 1:numel(sourcePaths)
    sourceHashes(i) = compute_file_sha256(sourcePaths(i));
end

Run05 = readtable(run05Path, 'Delimiter', ',', 'TextType', 'string');
Run06 = readtable(run06TransformPath, 'Delimiter', ',', ...
    'TextType', 'string');
Run07 = readtable(run07Path, 'Delimiter', ',', 'TextType', 'string');
eventOpts = detectImportOptions(run06EventPath, 'FileType', 'text', ...
    'Delimiter', ',');
eventNames = [ ...
    "event_valid_fraction","contact_dwell_fraction", ...
    "contact_transition_count","first_contact_latency_s", ...
    "mutual_approach_dwell_fraction","withdrawal_dwell_fraction", ...
    "approach_withdraw_transition_count","asym_positive_dwell_fraction", ...
    "asym_negative_dwell_fraction","role_asymmetry_bias_mean", ...
    "centroid_distance_mean_mm","centroid_distance_min_mm", ...
    "centroid_distance_delta_mm","radial_speed_mean_mm_s", ...
    "radial_speed_sign_change_count","approach1_positive_fraction", ...
    "approach2_positive_fraction","role_approach_imbalance", ...
    "mutual_facing_mean","heading_abs_change_deg", ...
    "heading_large_turn_count"];
missingEvents = setdiff(eventNames, string(eventOpts.VariableNames));
assert(isempty(missingEvents), ...
    'build_run10_validation_feature_registry:MissingEventFeature', ...
    'Run_06 event inventory lacks: %s', strjoin(missingEvents, ', '));

OverlapAudit = i_empty_overlap();
for i = 1:height(Run05)
    OverlapAudit = [OverlapAudit; i_overlap_row( ... %#ok<AGROW>
        "run_05", run05Path, sourceHashes(1), ...
        string(Run05.Name(i)), string(Run05.Name(i)), ...
        string(Run05.TransformHint(i)), ...
        "discovery_feature_overlap", ...
        "Canonical run_05 frame-level discovery feature")];
end
for i = 1:height(Run06)
    OverlapAudit = [OverlapAudit; i_overlap_row( ... %#ok<AGROW>
        "run_06", run06TransformPath, sourceHashes(2), ...
        string(Run06.ObsName(i)), string(Run06.BaseFeature(i)), ...
        string(Run06.ChannelType(i)) + ":" + ...
        string(Run06.TransformHint(i)), ...
        "derived_from_discovery_feature", ...
        "Run_06 transformed channel derived from a run_05 feature")];
end
for i = 1:numel(eventNames)
    OverlapAudit = [OverlapAudit; i_overlap_row( ... %#ok<AGROW>
        "run_06", run06EventPath, sourceHashes(3), eventNames(i), ...
        eventNames(i), "within_chunk_event_summary", ...
        "derived_from_discovery_feature", ...
        "Run_06 event summary explicitly excluded from independent validation")];
end
n7 = height(Run07);
featureName7 = "scale" + string(Run07.scale_index) + ":" + ...
    string(Run07.obs_name) + ":" + string(Run07.summary_kind) + ":" + ...
    string(Run07.summary_dim_index);
run07Rows = table(repmat("run_07", n7, 1), ...
    repmat(run07Path, n7, 1), repmat(sourceHashes(4), n7, 1), ...
    featureName7, string(Run07.base_feature), ...
    string(Run07.source_tensor) + ":" + string(Run07.summary_kind), ...
    repmat("derived_from_discovery_feature", n7, 1), ...
    true(n7, 1), repmat("Run_07 summary/PCA input dimension", n7, 1), ...
    false(n7, 1), repmat("none", n7, 1), ...
    'VariableNames', OverlapAudit.Properties.VariableNames);
OverlapAudit = [OverlapAudit; run07Rows];

nonIndependent = {
    "run_07","global_pc_scores","PCA or embedding score","discovery_feature_overlap"
    "run_07","umap_coordinates","visualization coordinate","discovery_feature_overlap"
    "run_08","graph_edge_weight","frozen graph construction","audit_only_covariate"
    "run_08","graph_plot_pc_coordinates","visualization coordinate","discovery_feature_overlap"
    "run_08","graph_umap_coordinates","visualization coordinate","discovery_feature_overlap"
    "run_09","motif_candidate_behavioral_profile","post-fit run_07 profile","discovery_feature_overlap"
    "run_09","motif_candidate_event_profile","post-fit run_06 profile","discovery_feature_overlap"
    "run_09","motif_candidate_annotation","provisional annotation","audit_only_covariate"
    "run_09","motif_candidate_node_ambiguity","graph stability/ambiguity","audit_only_covariate"
    "run_09","figure_appearance","rendered appearance","audit_only_covariate"
    };
for i = 1:size(nonIndependent, 1)
    OverlapAudit = [OverlapAudit; i_overlap_row( ... %#ok<AGROW>
        string(nonIndependent{i,1}), "documented_nonindependent_channel", ...
        "", string(nonIndependent{i,2}), string(nonIndependent{i,2}), ...
        string(nonIndependent{i,3}), string(nonIndependent{i,4}), ...
        "Non-independent or audit-only channel forbidden from primary status")];
end

Specs = params.feature_specs;
n = height(Specs);
Registry = Specs;
Registry.panel_version = repmat( ...
    params.validation_feature_panel_version, n, 1);
Registry.source_measurement_channel = repmat( ...
    "cleaned_pose_landmarks_not_used_for_run05_feature_values", n, 1);
Registry.source_pose_tensor = repmat( ...
    "sessionPreproc.clean.tracks", n, 1);
Registry.fixed_window_sec = repmat(params.validation_window_sec, n, 1);
Registry.summary_window_rule = repmat( ...
    "fixed_symmetric_anchor_window_independent_of_discovery_scale", n, 1);
Registry.missing_data_rule = repmat( ...
    "NaN_unless_finite_fraction_meets_config_and_correlation_has_minimum_pairs", ...
    n, 1);
Registry.minimum_finite_fraction = repmat( ...
    params.minimum_feature_finite_fraction, n, 1);
Registry.minimum_correlation_frames = repmat( ...
    params.minimum_correlation_frames, n, 1);
Registry.discovery_value_pose_nodes = repmat( ...
    strjoin(params.discovery_value_pose_nodes, ";"), n, 1);
Registry.raw_pose_node_overlap = false(n, 1);
Registry.exact_discovery_feature_name_overlap = false(n, 1);
Registry.renamed_or_deterministic_discovery_transform = false(n, 1);
Registry.included_in_primary_validation = false(n, 1);
Registry.exclusion_reason = strings(n, 1);
Registry.candidate_freeze_id = repmat( ...
    params.expected_candidate_freeze_id, n, 1);
Registry.frozen_membership_sha256 = repmat( ...
    params.expected_membership_sha256, n, 1);
Registry.experimental_labels_used = repmat("none", n, 1);

discoveryNames = lower([string(Run05.Name); string(Run06.ObsName); ...
    eventNames(:)]);
for i = 1:n
    nodes = string(split(Registry.raw_pose_nodes(i), ";"));
    nodes = nodes(nodes ~= "");
    Registry.raw_pose_node_overlap(i) = ~isempty(intersect( ...
        lower(nodes), lower(params.discovery_value_pose_nodes)));
    Registry.exact_discovery_feature_name_overlap(i) = ...
        any(lower(Registry.feature_name(i)) == discoveryNames);
    Registry.renamed_or_deterministic_discovery_transform(i) = ...
        i_equation_mentions_discovery_feature( ...
        Registry.equation(i), string(Run05.Name));
    Registry.included_in_primary_validation(i) = ...
        Registry.lineage_class(i) == "independent_behavioral_measure" && ...
        ~Registry.raw_pose_node_overlap(i) && ...
        ~Registry.exact_discovery_feature_name_overlap(i) && ...
        ~Registry.renamed_or_deterministic_discovery_transform(i);
    if ~Registry.included_in_primary_validation(i)
        Registry.exclusion_reason(i) = ...
            "failed_discovery_lineage_or_pose_node_overlap_gate";
    else
        Registry.exclusion_reason(i) = "none";
    end
end

assert(all(Registry.included_in_primary_validation), ...
    'build_run10_validation_feature_registry:LineageFailure', ...
    ['At least one frozen validation feature overlaps or derives from a ' ...
     'discovery feature. No pose values may be extracted.']);
assert(all(Registry.experimental_labels_used == "none"), ...
    'build_run10_validation_feature_registry:LabelFirewallFailure', ...
    'Experimental labels cannot enter the feature registry.');
end

function tf = i_equation_mentions_discovery_feature(equation, names)
equation = lower(string(equation));
names = lower(string(names));
tf = false;
for i = 1:numel(names)
    if strlength(names(i)) >= 5 && contains(equation, names(i))
        tf = true;
        return
    end
end
end

function row = i_overlap_row(stage, pathText, hash, feature, base, ...
        transform, lineage, reason)
row = table(string(stage), string(pathText), string(hash), ...
    string(feature), string(base), string(transform), string(lineage), ...
    true, string(reason), false, "none", ...
    'VariableNames', {'discovery_stage','source_artifact', ...
    'source_sha256','discovery_feature_name','base_feature', ...
    'transformation_or_role','lineage_class', ...
    'prohibited_from_primary_validation','prohibition_reason', ...
    'used_for_run10_validation_status','experimental_labels_used'});
end

function T = i_empty_overlap()
T = table(strings(0,1), strings(0,1), strings(0,1), strings(0,1), ...
    strings(0,1), strings(0,1), strings(0,1), false(0,1), ...
    strings(0,1), false(0,1), strings(0,1), ...
    'VariableNames', {'discovery_stage','source_artifact', ...
    'source_sha256','discovery_feature_name','base_feature', ...
    'transformation_or_role','lineage_class', ...
    'prohibited_from_primary_validation','prohibition_reason', ...
    'used_for_run10_validation_status','experimental_labels_used'});
end
