function [Ratings, Audit] = ingest_run10_blinded_ratings( ...
        outRoot, params, Packet)
%INGEST_RUN10_BLINDED_RATINGS Validate and freeze external ratings.

outRoot = string(outRoot);
ratingPath = string(params.ratings_input_file);
if ~i_is_absolute(ratingPath)
    ratingPath = fullfile(outRoot,ratingPath);
end

if ~isfile(ratingPath)
    Ratings = table();
    Audit = table(ratingPath,false,"","awaiting_ratings",0,false,false, ...
        params.rating_schema_version, ...
        "No rating file exists; absence is not negative evidence.", ...
        "none", ...
        'VariableNames', {'rating_input_file','rating_input_present', ...
        'rating_input_sha256','ingestion_status','rating_row_count', ...
        'schema_valid','ratings_frozen_before_unblinding', ...
        'rating_schema_version','details','experimental_labels_used'});
    return
end

ratingHash = compute_file_sha256(ratingPath);
Ratings = readtable(ratingPath,'Delimiter',',','TextType','string');
required = string(Packet.template.Properties.VariableNames);
missing = setdiff(required,string(Ratings.Properties.VariableNames));
assert(isempty(missing), ...
    'ingest_run10_blinded_ratings:MissingColumn', ...
    'Rating input lacks columns: %s',strjoin(missing,', '));
Ratings = Ratings(:,cellstr(required));
assert(height(Ratings)>0 && ...
    all(strlength(strtrim(string(Ratings.rater_id)))>0), ...
    'ingest_run10_blinded_ratings:MissingRater', ...
    'Every imported rating row requires a nonempty rater_id.');
assert(all(ismember(string(Ratings.review_id), ...
    string(Packet.manifest.review_id))), ...
    'ingest_run10_blinded_ratings:UnknownReviewId', ...
    'Rating input contains an unknown review_id.');
assert(all(ismember(string(Ratings.rating_level),["tile","candidate"])), ...
    'ingest_run10_blinded_ratings:BadLevel', ...
    'rating_level must be tile or candidate.');
tile = string(Ratings.rating_level)=="tile";
candidate = string(Ratings.rating_level)=="candidate";
assert(all(ismember(string(Ratings.tile_label(tile)), ...
    string(char('A'+(0:8))'))) && ...
    all(strlength(strtrim(string(Ratings.tile_label(candidate))))==0), ...
    'ingest_run10_blinded_ratings:BadTileLabel', ...
    'Tile rows require A-I and candidate rows require blank tile_label.');

key = string(Ratings.rater_id)+"|"+string(Ratings.review_id)+"|"+ ...
    string(Ratings.rating_level)+"|"+string(Ratings.tile_label);
assert(numel(unique(key))==height(Ratings), ...
    'ingest_run10_blinded_ratings:DuplicateRatingKey', ...
    'Rating rows must be unique by rater, review, level, and tile.');
i_validate_score(Ratings.behavioral_coherence_score,tile, ...
    'behavioral_coherence_score');
i_validate_score(Ratings.ambiguity_score,tile,'ambiguity_score');
i_validate_score(Ratings.confidence_score,tile,'confidence_score');
i_validate_score(Ratings.candidate_overall_coherence_score,candidate, ...
    'candidate_overall_coherence_score');
i_validate_category(Ratings.interactive_impression,tile, ...
    ["interactive","not_interactive","uncertain"], ...
    'interactive_impression');
i_validate_category(Ratings.contact_configuration,tile, ...
    ["none","head_head","head_body","body_body","paw_or_tail", ...
     "mixed","uncertain"],'contact_configuration');
i_validate_category(Ratings.relative_orientation,tile, ...
    ["facing","parallel","opposed","perpendicular","mixed","uncertain"], ...
    'relative_orientation');
i_validate_category(Ratings.motion_impression,tile, ...
    ["approach","withdrawal","stationary","locomotor","mixed","uncertain"], ...
    'motion_impression');

% The byte hash is established before the sealed candidate/stratum map is
% joined. This is the rating freeze boundary.
map = unique(Packet.randomization(:, ...
    {'review_id','motif_candidate_id'}),'rows');
[present,loc] = ismember(string(Ratings.review_id),string(map.review_id));
assert(all(present), ...
    'ingest_run10_blinded_ratings:UnblindingMapFailure', ...
    'Every frozen rating row requires a sealed candidate mapping.');
Ratings.motif_candidate_id = string(map.motif_candidate_id(loc));
tileMap = Packet.randomization(:, ...
    {'review_id','tile_label','hidden_selection_stratum', ...
     'hidden_node_stability','hidden_boundary_ambiguity'});
ratingTileKey = string(Ratings.review_id)+"|"+string(Ratings.tile_label);
mapTileKey = string(tileMap.review_id)+"|"+string(tileMap.tile_label);
[presentTile,locTile] = ismember(ratingTileKey,mapTileKey);
Ratings.hidden_selection_stratum = strings(height(Ratings),1);
Ratings.hidden_node_stability = nan(height(Ratings),1);
Ratings.hidden_boundary_ambiguity = false(height(Ratings),1);
Ratings.hidden_selection_stratum(tile) = ...
    string(tileMap.hidden_selection_stratum(locTile(tile)));
Ratings.hidden_node_stability(tile) = ...
    double(tileMap.hidden_node_stability(locTile(tile)));
Ratings.hidden_boundary_ambiguity(tile) = ...
    logical(tileMap.hidden_boundary_ambiguity(locTile(tile)));
assert(all(presentTile(tile)), ...
    'ingest_run10_blinded_ratings:TileUnblindingMapFailure', ...
    'Every frozen tile rating requires a sealed stratum mapping.');
Ratings.rating_input_sha256 = repmat(ratingHash,height(Ratings),1);
Ratings.ratings_frozen_before_unblinding = true(height(Ratings),1);
Ratings.experimental_labels_used = repmat("none",height(Ratings),1);

Audit = table(ratingPath,true,ratingHash,"ratings_frozen_and_ingested", ...
    height(Ratings),true,true,params.rating_schema_version, ...
    "Schema and visible IDs validated after hashing; sealed mapping joined only afterward.", ...
    "none", ...
    'VariableNames', {'rating_input_file','rating_input_present', ...
    'rating_input_sha256','ingestion_status','rating_row_count', ...
    'schema_valid','ratings_frozen_before_unblinding', ...
    'rating_schema_version','details','experimental_labels_used'});
end

function i_validate_score(x,requiredMask,name)
if isnumeric(x)
    v = double(x);
else
    v = str2double(string(x));
end
assert(all(isfinite(v(requiredMask)) & v(requiredMask)>=1 & ...
    v(requiredMask)<=5 & mod(v(requiredMask),1)==0), ...
    'ingest_run10_blinded_ratings:BadScore', ...
    '%s requires integer scores from 1 to 5.',name);
other = ~requiredMask;
assert(all(~isfinite(v(other))), ...
    'ingest_run10_blinded_ratings:ScoreAtWrongLevel', ...
    '%s is populated at the wrong rating level.',name);
end

function i_validate_category(x,requiredMask,allowed,name)
x = string(x);
assert(all(ismember(x(requiredMask),allowed)), ...
    'ingest_run10_blinded_ratings:BadCategory', ...
    '%s contains an invalid category.',name);
assert(all(strlength(strtrim(x(~requiredMask)))==0), ...
    'ingest_run10_blinded_ratings:CategoryAtWrongLevel', ...
    '%s is populated at the wrong rating level.',name);
end

function tf = i_is_absolute(pathText)
pathText = char(pathText);
tf = ~isempty(regexp(pathText,'^[A-Za-z]:[\\/]','once')) || ...
    startsWith(pathText,'\\') || startsWith(pathText,'/');
end
