function params = load_motif_candidate_video_review_config(configPath)
%LOAD_MOTIF_CANDIDATE_VIDEO_REVIEW_CONFIG Load blinded-review parameters.

if nargin < 1 || strlength(string(configPath)) == 0
    repoRoot = fileparts(fileparts(mfilename('fullpath')));
    configPath = fullfile(repoRoot, 'config', ...
        'motif_candidate_video_review_config.csv');
end

opts = detectImportOptions(configPath, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
opts.DataLines = [2, Inf];
opts = setvartype(opts, opts.VariableNames, 'string');
T = readtable(configPath, opts);
required = ["parameter", "value", "type", "env_override", "description"];
missing = setdiff(required, string(T.Properties.VariableNames));
assert(isempty(missing), ...
    'load_motif_candidate_video_review_config:MissingColumn', ...
    'Config is missing required columns: %s', strjoin(missing, ', '));
assert(numel(unique(T.parameter)) == height(T), ...
    'load_motif_candidate_video_review_config:DuplicateParameter', ...
    'Every video-review parameter must be unique.');

params = struct();
envOverrideUsed = false(height(T), 1);
for i = 1:height(T)
    fieldName = matlab.lang.makeValidName(T.parameter(i));
    rawValue = string(T.value(i));
    envName = strtrim(string(T.env_override(i)));
    if ismissing(envName)
        envName = "";
    end
    if envName ~= ""
        envValue = strtrim(string(getenv(envName)));
        if envValue ~= ""
            rawValue = envValue;
            envOverrideUsed(i) = true;
        end
    end
    params.(fieldName) = i_parse_value( ...
        rawValue, lower(strtrim(string(T.type(i)))), T.parameter(i));
end

T.env_override_used = envOverrideUsed;
[params, T] = i_apply_mode(params, T);
T.effective_value = strings(height(T), 1);
for i = 1:height(T)
    fieldName = matlab.lang.makeValidName(T.parameter(i));
    T.effective_value(i) = i_value_to_string(params.(fieldName));
end
params.config_path = string(configPath);
params.config_table = T;
i_validate(params);
end

function [params, T] = i_apply_mode(params, T)
smokeRoot = "derived/pre_run10_blinded_motif_candidate_video_review_smoke";
fullRoot = "derived/pre_run10_blinded_motif_candidate_video_review";
outputExplicit = any(T.parameter == "output_dir" & T.env_override_used);
if params.run_mode == "full"
    if ~outputExplicit && any(params.output_dir == [smokeRoot fullRoot])
        params.output_dir = fullRoot;
    end
    params.active_candidate_limit = params.candidate_limit_full;
else
    if ~outputExplicit && any(params.output_dir == [smokeRoot fullRoot])
        params.output_dir = smokeRoot;
    end
    params.active_candidate_limit = params.candidate_limit_smoke;
end
end

function i_validate(params)
assert(any(params.run_mode == ["smoke", "full"]), ...
    'load_motif_candidate_video_review_config:BadRunMode', ...
    'run_mode must be smoke or full.');
outputDir = lower(replace(string(params.output_dir), "\", "/"));
if params.run_mode == "full"
    assert(~contains(outputDir, "smoke"), ...
        'load_motif_candidate_video_review_config:BadFullOutput', ...
        'Full output_dir must not be a smoke directory.');
else
    assert(contains(outputDir, "smoke"), ...
        'load_motif_candidate_video_review_config:BadSmokeOutput', ...
        'Smoke output_dir must be a separate smoke directory.');
end
assert(params.expected_candidate_freeze_id == ...
    "run09_candidates_2e58d214683b_8817d942_0e956a2c", ...
    'load_motif_candidate_video_review_config:BadFreezeId', ...
    'The issued run_09 candidate freeze ID is immutable.');
assert(strlength(params.expected_membership_sha256) == 64 && ...
    ~isempty(regexp(char(params.expected_membership_sha256), ...
    '^[0-9a-f]{64}$', 'once')), ...
    'load_motif_candidate_video_review_config:BadMembershipHash', ...
    'expected_membership_sha256 must be a lowercase SHA-256 value.');
assert(params.candidate_scope == "interpretation_eligible_only", ...
    'load_motif_candidate_video_review_config:BadCandidateScope', ...
    'Primary blinded mosaics must use only graph-eligible candidates.');
tileCounts = [params.central_tiles, params.core_random_tiles, ...
    params.boundary_random_tiles];
assert(params.tiles_per_candidate == 9 && sum(tileCounts) == 9 && ...
    all(tileCounts == 3), ...
    'load_motif_candidate_video_review_config:BadTileContract', ...
    'The blinded mosaic contract requires three rows of three examples.');
assert(params.maximum_examples_per_session >= 1 && ...
    params.maximum_examples_per_session == ...
    floor(params.maximum_examples_per_session), ...
    'load_motif_candidate_video_review_config:BadSessionLimit', ...
    'maximum_examples_per_session must be a positive integer.');
assert(params.core_minimum_node_stability >= 0 && ...
    params.core_minimum_node_stability <= 1, ...
    'load_motif_candidate_video_review_config:BadCoreStability', ...
    'core_minimum_node_stability must lie in [0,1].');
assert(params.random_stream_algorithm == "mt19937ar" && ...
    params.random_seed >= 0 && ...
    params.random_seed == floor(params.random_seed), ...
    'load_motif_candidate_video_review_config:BadRandomContract', ...
    'A fixed nonnegative mt19937ar seed is required.');
assert(params.input_frame_rate_hz > 0 && ...
    params.output_frame_rate_hz > 0 && ...
    params.output_frame_rate_hz <= params.input_frame_rate_hz, ...
    'load_motif_candidate_video_review_config:BadFrameRate', ...
    'Frame rates must be positive and output cannot exceed input.');
assert(params.minimum_clip_half_window_sec > 0 && ...
    params.maximum_clip_half_window_sec >= ...
    params.minimum_clip_half_window_sec && ...
    params.clip_context_padding_sec >= 0, ...
    'load_motif_candidate_video_review_config:BadClipWindow', ...
    'Clip-window limits are invalid.');
assert(numel(params.camera_x_limits) == 2 && ...
    numel(params.camera_y_limits) == 2 && ...
    diff(params.camera_x_limits) > 0 && ...
    diff(params.camera_y_limits) > 0, ...
    'load_motif_candidate_video_review_config:BadCameraLimits', ...
    'Camera limits must contain increasing two-element vectors.');
assert(params.video_profile == "MPEG-4", ...
    'load_motif_candidate_video_review_config:BadVideoProfile', ...
    'The validated video profile is MPEG-4.');
end

function value = i_parse_value(rawValue, valueType, parameterName)
rawValue = string(rawValue);
switch valueType
    case "number"
        if lower(strtrim(rawValue)) == "inf"
            value = Inf;
        else
            value = str2double(rawValue);
        end
        assert(~isnan(value), ...
            'load_motif_candidate_video_review_config:BadNumber', ...
            '%s must be numeric.', parameterName);
    case "number_list"
        parts = strtrim(string(split(rawValue, {';', '|', ','})))';
        parts = parts(parts ~= "");
        value = str2double(parts);
        assert(~isempty(value) && all(isfinite(value)), ...
            'load_motif_candidate_video_review_config:BadNumberList', ...
            '%s must be a finite numeric list.', parameterName);
    case "logical"
        text = lower(strtrim(rawValue));
        assert(any(text == ["true", "false", "1", "0", "yes", "no"]), ...
            'load_motif_candidate_video_review_config:BadLogical', ...
            '%s must be logical-like.', parameterName);
        value = any(text == ["true", "1", "yes"]);
    case {"string", "path"}
        value = strtrim(rawValue);
    otherwise
        error('load_motif_candidate_video_review_config:BadType', ...
            'Unsupported type %s for %s.', valueType, parameterName);
end
end

function value = i_value_to_string(x)
if islogical(x)
    value = string(x);
elseif isnumeric(x)
    value = strjoin(compose('%.17g', x(:)'), ';');
else
    value = string(x);
end
end
