function [QcManifest, PaperManifest] = ...
        make_run10_behavioral_validation_figures(outRoot, Registry, ...
        Measurement, Coherence, Heldout, Confusion, CrossSession, ...
        CrossScale, ReviewSummary, Status, GraphAudit, params)
%MAKE_RUN10_BEHAVIORAL_VALIDATION_FIGURES Validation-only figures.

outRoot = string(outRoot);
qcRoot = fullfile(outRoot,'qc_figures');
paperRoot = fullfile(outRoot,'paper_figures');
if ~isfolder(qcRoot), mkdir(qcRoot); end
if ~isfolder(paperRoot), mkdir(paperRoot); end

QcManifest = i_empty_manifest();
PaperManifest = i_empty_manifest();

fig = i_figure();
featureNames = string(Registry.feature_name);
missing = zeros(numel(featureNames),1);
for i = 1:numel(featureNames)
    missing(i) = mean(~isfinite(Measurement.(featureNames(i))));
end
barh(missing,'FaceColor',[0.25 0.55 0.75]);
yticks(1:numel(featureNames)); yticklabels(replace(featureNames,"_"," "));
xlabel('Missing node-level fraction'); title('Independent feature missingness');
grid on;
QcManifest = [QcManifest;i_export_pair(fig,qcRoot, ...
    "run10_qc_independent_feature_missingness", ...
    "Independent disjoint-landmark feature completeness", ...
    "run10_validation_feature_registry.csv;motif_candidate_independent_behavioral_measurement.csv", ...
    params)]; %#ok<AGROW>
close(fig);

fig = i_figure();
eligible = Status.run09_graph_interpretation_eligible;
bar(categorical(i_short(Status.motif_candidate_id(eligible))), ...
    [Coherence.validation_node_count(ismember(Coherence.motif_candidate_id, ...
    Status.motif_candidate_id(eligible))), ...
    CrossSession.contributing_session_count(ismember( ...
    CrossSession.motif_candidate_id,Status.motif_candidate_id(eligible)))]);
ylabel('Count'); legend({'validation nodes','sessions'},'Location','best');
title('Eligible-candidate independent evidence coverage'); grid on;
QcManifest = [QcManifest;i_export_pair(fig,qcRoot, ...
    "run10_qc_candidate_coverage", ...
    "Independent validation node and session coverage", ...
    "motif_candidate_behavioral_coherence_audit.csv;motif_candidate_cross_session_reproducibility.csv", ...
    params)]; %#ok<AGROW>
close(fig);

fig = i_figure();
axis off
annotation(fig,'textbox',[0.03 0.72 0.20 0.16], ...
    'String',"Frozen run_09" + newline + "membership", ...
    'HorizontalAlignment','center','VerticalAlignment','middle', ...
    'FontWeight','bold','EdgeColor',[0.2 0.2 0.2]);
annotation(fig,'textbox',[0.28 0.72 0.20 0.16], ...
    'String',"Disjoint-landmark" + newline + "lineage gate", ...
    'HorizontalAlignment','center','VerticalAlignment','middle', ...
    'FontWeight','bold','EdgeColor',[0.1 0.45 0.7]);
annotation(fig,'textbox',[0.53 0.72 0.20 0.16], ...
    'String',"Grouped-session" + newline + "automated validation", ...
    'HorizontalAlignment','center','VerticalAlignment','middle', ...
    'FontWeight','bold','EdgeColor',[0.1 0.55 0.3]);
annotation(fig,'textbox',[0.78 0.72 0.19 0.16], ...
    'String',"Blinded review" + newline + "or awaiting ratings", ...
    'HorizontalAlignment','center','VerticalAlignment','middle', ...
    'FontWeight','bold','EdgeColor',[0.55 0.3 0.65]);
for x = [0.235 0.485 0.735]
    annotation(fig,'arrow',[x x+0.035],[0.8 0.8]);
end
annotation(fig,'textbox',[0.08 0.35 0.84 0.22], ...
    'String',["Primary evidence: within-candidate coherence | held-out candidate ID recall | cross-session profile reliability"; ...
    "Audit only: scale dependence | frozen graph-to-independent-behavior correspondence"; ...
    "Never used: condition/cohort/treatment/outcome | run_07 PCA/UMAP | run_06 events | run_09 annotations"], ...
    'HorizontalAlignment','center','VerticalAlignment','middle', ...
    'EdgeColor','none','FontSize',11);
PaperManifest = [PaperManifest;i_export_pair(fig,paperRoot, ...
    "run10_paper_independence_design", ...
    "Run_10 independence firewall and validation design", ...
    "run10_input_freeze_validation.csv;run10_validation_feature_registry.csv;run10_blinded_rating_packet_manifest.csv", ...
    params)]; %#ok<AGROW>
close(fig);

eligibleIds = Status.motif_candidate_id(eligible);
[~,cLoc] = ismember(eligibleIds,Coherence.motif_candidate_id);
[~,hLoc] = ismember(eligibleIds,Heldout.motif_candidate_id);
[~,sLoc] = ismember(eligibleIds,CrossSession.motif_candidate_id);
[~,xLoc] = ismember(eligibleIds,CrossScale.motif_candidate_id);
[~,rLoc] = ismember(eligibleIds,ReviewSummary.motif_candidate_id);
M = [Coherence.relative_dispersion_improvement(cLoc), ...
    Heldout.heldout_recall(hLoc), ...
    CrossSession.split_session_profile_correlation(sLoc), ...
    CrossScale.median_pairwise_scale_profile_correlation(xLoc), ...
    ReviewSummary.mean_candidate_coherence_score(rLoc)./5];
fig = i_figure();
ax = axes(fig);
ax.Color = [0.88 0.88 0.88];
imageHandle = imagesc(ax,M,[-0.25 1]);
imageHandle.AlphaData = isfinite(M);
colorbar(ax);
xticks(1:5); xticklabels({'coherence effect','held-out recall', ...
    'session reliability','scale consistency','blinded coherence'});
yticks(1:numel(eligibleIds)); yticklabels(i_short(eligibleIds));
pending = ~isfinite(M);
[pendingRow,pendingColumn] = find(pending);
if ~isempty(pendingRow)
    text(ax,pendingColumn,pendingRow,repmat("pending",numel(pendingRow),1), ...
        'HorizontalAlignment','center','VerticalAlignment','middle', ...
        'Color',[0.25 0.25 0.25],'FontSize',8);
end
title('Independent behavioral validation matrix (gray = awaiting ratings)');
PaperManifest = [PaperManifest;i_export_pair(fig,paperRoot, ...
    "run10_paper_candidate_validation_matrix", ...
    "Nine-candidate automated and blinded validation matrix", ...
    "motif_candidate_behavioral_coherence_audit.csv;motif_candidate_heldout_discriminability.csv;motif_candidate_cross_session_reproducibility.csv;motif_candidate_cross_scale_validation_audit.csv;motif_candidate_blinded_review_summary.csv", ...
    params)]; %#ok<AGROW>
close(fig);

fig = i_figure();
C = reshape(Confusion.row_fraction, ...
    numel(eligibleIds),numel(eligibleIds))';
imagesc(C,[0 1]); axis image; colorbar;
xticks(1:numel(eligibleIds)); yticks(1:numel(eligibleIds));
xticklabels(i_short(eligibleIds)); yticklabels(i_short(eligibleIds));
xlabel('Predicted candidate'); ylabel('Frozen candidate');
title(sprintf('Grouped held-out nearest-centroid recall; macro = %.3f', ...
    mean(Heldout.heldout_recall,'omitnan')));
PaperManifest = [PaperManifest;i_export_pair(fig,paperRoot, ...
    "run10_paper_heldout_discriminability", ...
    "Grouped held-out candidate confusion matrix", ...
    "motif_candidate_validation_confusion_matrix.csv;motif_candidate_heldout_discriminability.csv;motif_candidate_validation_null_audit.csv", ...
    params)]; %#ok<AGROW>
close(fig);

fig = i_figure();
mask = GraphAudit.run09_graph_interpretation_eligible;
scatter(GraphAudit.run09_mean_node_stability(mask), ...
    GraphAudit.independent_behavioral_coherence_effect(mask),70, ...
    GraphAudit.run09_boundary_node_fraction(mask),'filled');
text(GraphAudit.run09_mean_node_stability(mask), ...
    GraphAudit.independent_behavioral_coherence_effect(mask), ...
    "  "+i_short(GraphAudit.motif_candidate_id(mask)));
xlabel('Frozen graph mean node stability');
ylabel('Independent coherence effect');
title('Graph-to-independent-behavior correspondence (audit only)');
cb = colorbar; cb.Label.String = 'Frozen boundary fraction'; grid on;
PaperManifest = [PaperManifest;i_export_pair(fig,paperRoot, ...
    "run10_paper_graph_behavior_correspondence", ...
    "Post-validation graph-to-independent-behavior audit", ...
    "motif_candidate_graph_behavior_correspondence.csv",params)]; %#ok<AGROW>
close(fig);
end

function fig = i_figure()
fig = figure('Visible','off','Color','w','Position',[100 100 1200 760]);
end

function rows = i_export_pair(fig,root,id,role,inputs,params)
formats = [params.figure_raster_format;params.figure_vector_format];
rows = i_empty_manifest();
for i = 1:2
    pathText = fullfile(root,id+"."+formats(i));
    if formats(i)=="png"
        exportgraphics(fig,pathText,'Resolution',params.figure_raster_dpi);
        fileType = "raster";
    else
        exportgraphics(fig,pathText,'ContentType','vector');
        fileType = "vector";
    end
    info = dir(pathText);
    rows = [rows;table(id+"_"+fileType,id,pathText,fileType, ...
        string(role),string(inputs),double(info.bytes), ...
        compute_file_sha256(pathText),true,false,false,"none", ...
        'VariableNames',rows.Properties.VariableNames)]; %#ok<AGROW>
end
end

function T = i_empty_manifest()
T = table(strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),nan(0,1),strings(0,1),false(0,1), ...
    false(0,1),false(0,1),strings(0,1), ...
    'VariableNames', {'figure_id','figure_design_id','figure_path', ...
    'file_type','scientific_role','input_artifacts','file_bytes', ...
    'sha256','generated_after_validation_freeze', ...
    'used_for_validation_status','used_for_membership', ...
    'experimental_labels_used'});
end

function out = i_short(ids)
out = extractAfter(string(ids),"_C");
out = "C"+out;
end
