function Packet = prepare_run10_blinded_rating_packet( ...
        repoRoot, outRoot, params, Validation)
%PREPARE_RUN10_BLINDED_RATING_PACKET Build blank randomized rater materials.
%
% This function never generates a rating. Candidate and hidden sampling
% strata are retained only in the sealed randomization table.

assert(Validation.membership_sha256 == params.expected_membership_sha256, ...
    'prepare_run10_blinded_rating_packet:FreezeNotValidated', ...
    'The candidate freeze must pass before review media are read.');
repoRoot = string(repoRoot);
outRoot = string(outRoot);
reviewRoot = string(resolve_repo_path(repoRoot, ...
    params.pre_run10_review_dir));
manifestPath = fullfile(reviewRoot, ...
    'pre_run10_blinded_video_review_output_manifest.csv');
selectionPath = fullfile(reviewRoot, ...
    'blinded_motif_candidate_video_selection.csv');
renderPath = fullfile(reviewRoot, ...
    'blinded_motif_candidate_video_render_audit.csv');
Manifest = readtable(manifestPath, 'Delimiter', ',', 'TextType', 'string');
Selection = readtable(selectionPath, 'Delimiter', ',', 'TextType', 'string');
Render = readtable(renderPath, 'Delimiter', ',', 'TextType', 'string');

assert(all(string(Manifest.candidate_freeze_id) == ...
    params.expected_candidate_freeze_id) && ...
    all(string(Manifest.frozen_membership_sha256) == ...
    params.expected_membership_sha256), ...
    'prepare_run10_blinded_rating_packet:PreparationFreezeMismatch', ...
    'Pre-run_10 review preparation is bound to a different freeze.');
for i = 1:height(Manifest)
    pathText = string(Manifest.artifact_path(i));
    assert(isfile(pathText), ...
        'prepare_run10_blinded_rating_packet:MissingPreparedArtifact', ...
        'Missing prepared review artifact: %s', pathText);
    assert(compute_file_sha256(pathText) == string(Manifest.sha256(i)), ...
        'prepare_run10_blinded_rating_packet:PreparedHashMismatch', ...
        'Prepared review artifact hash mismatch: %s', pathText);
end
assert(all(Selection.experimental_labels_used == "none") && ...
    all(Render.experimental_labels_used == "none"), ...
    'prepare_run10_blinded_rating_packet:ReviewFirewallFailure', ...
    'Prepared review media violated the label-blinding contract.');

candidateIds = sort(unique(string(Selection.motif_candidate_id)));
assert(isequal(candidateIds,Validation.eligible_candidate_ids), ...
    'prepare_run10_blinded_rating_packet:CandidateSetMismatch', ...
    'Rater packet must contain the exact nine graph-eligible candidates.');
n = numel(candidateIds);
reviewId = strings(n,1);
for i = 1:n
    digest = compute_run09_sha256_text(candidateIds(i) + "|" + ...
        string(params.rating_packet_seed));
    reviewId(i) = "RVW-" + upper(extractBefore(digest,9));
end
assert(numel(unique(reviewId))==n, ...
    'prepare_run10_blinded_rating_packet:ReviewIdCollision', ...
    'Non-semantic review IDs must be unique.');
stream = RandStream(char(params.random_stream_algorithm), ...
    'Seed',params.rating_packet_seed);
order = randperm(stream,n)';
displayOrder = zeros(n,1);
displayOrder(order) = (1:n)';

mediaRoot = fullfile(outRoot,'rating_packet','media');
if ~isfolder(mediaRoot)
    mkdir(mediaRoot);
end
raterVideo = strings(n,1);
raterSheet = strings(n,1);
videoHash = strings(n,1);
sheetHash = strings(n,1);
for i = 1:n
    row = string(Render.motif_candidate_id)==candidateIds(i);
    assert(nnz(row)==1 && string(Render.render_status(row))=="success", ...
        'prepare_run10_blinded_rating_packet:RenderUnavailable', ...
        'Prepared review media are unavailable for %s.',candidateIds(i));
    sourceVideo = string(Render.video_file(row));
    sourceSheet = string(Render.contact_sheet_file(row));
    raterVideo(i) = fullfile(mediaRoot,reviewId(i)+".mp4");
    raterSheet(i) = fullfile(mediaRoot,reviewId(i)+".png");
    i_copy_exact(sourceVideo,raterVideo(i));
    i_copy_exact(sourceSheet,raterSheet(i));
    videoHash(i) = compute_file_sha256(raterVideo(i));
    sheetHash(i) = compute_file_sha256(raterSheet(i));
end

PacketManifest = table(reviewId,displayOrder,raterVideo,videoHash, ...
    raterSheet,sheetHash,repmat("neutral_pose_only_3x3_mosaic",n,1), ...
    repmat(true,n,1),repmat(false,n,1),repmat("none",n,1), ...
    'VariableNames', {'review_id','display_order','video_file', ...
    'video_sha256','contact_sheet_file','contact_sheet_sha256', ...
    'media_role','rater_visible','candidate_identity_visible_in_manifest', ...
    'experimental_labels_used'});
PacketManifest = sortrows(PacketManifest,'display_order');

randomRows = table();
for i = 1:n
    selected = Selection(string(Selection.motif_candidate_id)== ...
        candidateIds(i),:);
    selected = sortrows(selected,'display_tile_index');
    row = table(repmat(reviewId(i),height(selected),1), ...
        repmat(displayOrder(i),height(selected),1), ...
        repmat(candidateIds(i),height(selected),1), ...
        selected.display_tile_label,selected.display_tile_index, ...
        selected.graph_node_id,selected.selection_stratum, ...
        selected.node_stability,selected.is_boundary_ambiguous, ...
        repmat(false,height(selected),1), ...
        repmat("sealed_until_rating_input_is_frozen",height(selected),1), ...
        repmat(params.expected_membership_sha256,height(selected),1), ...
        repmat("none",height(selected),1), ...
        'VariableNames', {'review_id','display_order', ...
        'motif_candidate_id','tile_label','tile_index','graph_node_id', ...
        'hidden_selection_stratum','hidden_node_stability', ...
        'hidden_boundary_ambiguity','rater_visible','unblinding_policy', ...
        'frozen_membership_sha256','experimental_labels_used'});
    randomRows = [randomRows;row]; %#ok<AGROW>
end
Randomization = sortrows(randomRows,{'display_order','tile_index'});

Template = table();
for i = 1:n
    tile = string(char('A'+(0:8))');
    tileRows = table(repmat("",9,1),repmat(reviewId(i),9,1), ...
        repmat("tile",9,1),tile,nan(9,1),strings(9,1), ...
        strings(9,1),strings(9,1),strings(9,1),nan(9,1), ...
        nan(9,1),nan(9,1),strings(9,1), ...
        'VariableNames',i_rating_names());
    candidateRow = table("",reviewId(i),"candidate","",NaN,"","","","", ...
        NaN,NaN,NaN,"",'VariableNames',i_rating_names());
    Template = [Template;tileRows;candidateRow]; %#ok<AGROW>
end

Codebook = table( ...
    ["rater_id";"review_id";"rating_level";"tile_label"; ...
     "behavioral_coherence_score";"interactive_impression"; ...
     "contact_configuration";"relative_orientation"; ...
     "motion_impression";"ambiguity_score";"confidence_score"; ...
     "candidate_overall_coherence_score";"free_text_description"], ...
    ["Nonempty blinded rater identifier"; ...
     "Packet review ID; do not infer biological meaning"; ...
     "tile or candidate";"A through I for tile rows; blank for candidate"; ...
     "Tile coherence/clarity score from 1 to 5"; ...
     "interactive|not_interactive|uncertain"; ...
     "none|head_head|head_body|body_body|paw_or_tail|mixed|uncertain"; ...
     "facing|parallel|opposed|perpendicular|mixed|uncertain"; ...
     "approach|withdrawal|stationary|locomotor|mixed|uncertain"; ...
     "Ambiguity score from 1 low to 5 high"; ...
     "Confidence score from 1 low to 5 high"; ...
     "Candidate-level within-mosaic coherence score from 1 to 5"; ...
     "Optional description without experimental guesses"], ...
    ["string";"string";"categorical";"categorical";"ordinal"; ...
     "categorical";"categorical";"categorical";"categorical"; ...
     "ordinal";"ordinal";"ordinal";"free_text"], ...
    ["required";"required";"required";"conditional";"tile_only"; ...
     "tile_only";"tile_only";"tile_only";"tile_only";"tile_only"; ...
     "tile_only";"candidate_only";"optional"], ...
    repmat(params.rating_schema_version,13,1), ...
    'VariableNames', {'field_name','definition_or_allowed_values', ...
    'field_type','requirement','rating_schema_version'});

Instructions = [
    "Run_10 blinded dyadic behavior review"
    ""
    "Review entries in display_order. Review IDs and any code drawn inside the legacy source mosaic are arbitrary non-semantic identifiers."
    "Do not infer condition, cohort, session, candidate prevalence, graph status, sampling stratum, annotation, or experimental hypothesis."
    "For each tile A-I, complete the tile row using only visible pose dynamics. Use uncertain when the display does not support a categorical judgment."
    "After all nine tiles, complete the candidate row with the overall within-mosaic coherence score."
    "Do not leave a required field blank merely because the behavior is ambiguous; use the ambiguity and confidence scores."
    "Free text should describe visible dyadic behavior and must not guess treatment, genotype, outcome, or condition."
    "Return the completed CSV without changing review_id, rating_level, or tile_label."
    ""
    "No ratings are pre-filled. Missing ratings remain missing and are not negative evidence."
    ];

Packet = struct();
Packet.manifest = PacketManifest;
Packet.template = Template;
Packet.codebook = Codebook;
Packet.randomization = Randomization;
Packet.instructions = Instructions;
end

function names = i_rating_names()
names = {'rater_id','review_id','rating_level','tile_label', ...
    'behavioral_coherence_score','interactive_impression', ...
    'contact_configuration','relative_orientation','motion_impression', ...
    'ambiguity_score','confidence_score', ...
    'candidate_overall_coherence_score','free_text_description'};
end

function i_copy_exact(source,target)
assert(isfile(source), ...
    'prepare_run10_blinded_rating_packet:MissingMedia', ...
    'Prepared media file is missing: %s',source);
parent = fileparts(target);
if ~isfolder(parent)
    mkdir(parent);
end
[ok,message] = copyfile(source,target,'f');
assert(ok, ...
    'prepare_run10_blinded_rating_packet:CopyFailed', ...
    'Could not copy %s to %s: %s',source,target,message);
assert(compute_file_sha256(source)==compute_file_sha256(target), ...
    'prepare_run10_blinded_rating_packet:CopyHashMismatch', ...
    'Rater media copy differs from the prepared source.');
end
