function [Selection, CandidateSummary] = ...
        select_blinded_motif_candidate_video_examples(repoRoot, params)
%SELECT_BLINDED_MOTIF_CANDIDATE_VIDEO_EXAMPLES Freeze 3x3 review samples.
%
% Selection is downstream of the run_09 candidate freeze. It uses frozen
% membership, graph stability, graph centrality, and a deterministic random
% stream. Session identity is used only to prevent a post-fit display from
% being dominated by one session. Experimental labels, behavioral profiles,
% event profiles, annotations, arena, and visual appearance are not read.

repoRoot = string(repoRoot);
run09Root = string(resolve_repo_path(repoRoot, params.run09_output_dir));
membershipPath = fullfile(run09Root, params.candidate_membership_file);
[membershipHash, ~] = compute_file_sha256(membershipPath);
assert(membershipHash == params.expected_membership_sha256, ...
    'select_blinded_motif_candidate_video_examples:MembershipHashMismatch', ...
    'Frozen run_09 membership hash differs from the configured value.');

Membership = i_read_columns(membershipPath, ...
    ["graph_node_id", "motif_candidate_id"]);
Ambiguity = i_read_columns(fullfile(run09Root, ...
    params.candidate_ambiguity_file), ...
    ["graph_node_id", "motif_candidate_id", ...
     "coassignment_jaccard_mean", "is_boundary_ambiguous"]);
Topology = i_read_columns(fullfile(run09Root, ...
    params.candidate_topology_file), ...
    ["motif_candidate_id", "candidate_local_index", "node_count", ...
     "eligible_for_behavioral_interpretation", "interpretation_status"]);
Exemplars = i_read_columns(fullfile(run09Root, ...
    params.candidate_exemplar_file), ...
    ["motif_candidate_id", "exemplar_rank", "graph_node_id"]);
NodeMetadata = i_read_columns(resolve_repo_path(repoRoot, ...
    params.run08_node_manifest_file), ...
    ["graph_node_id", "embedding_row_id", "scale_index", "chunk_sec", ...
     "session_index", "session_id", "raw_index", "anchor_frame", ...
     "anchor_time_s"]);

assert(height(Membership) == numel(unique(Membership.graph_node_id)), ...
    'select_blinded_motif_candidate_video_examples:DuplicateMembership', ...
    'Frozen membership must contain exactly one row per graph node.');
NodeTable = innerjoin(Membership, Ambiguity, ...
    'Keys', {'graph_node_id', 'motif_candidate_id'});
NodeTable = innerjoin(NodeTable, NodeMetadata, 'Keys', 'graph_node_id');
assert(height(NodeTable) == height(Membership), ...
    'select_blinded_motif_candidate_video_examples:MissingNodeMetadata', ...
    'Every frozen member must have ambiguity and node-provenance rows.');

eligible = logical(Topology.eligible_for_behavioral_interpretation);
CandidateTable = sortrows(Topology(eligible, :), 'candidate_local_index');
if isfinite(params.active_candidate_limit)
    CandidateTable = CandidateTable( ...
        1:min(height(CandidateTable), params.active_candidate_limit), :);
end
assert(~isempty(CandidateTable), ...
    'select_blinded_motif_candidate_video_examples:NoCandidates', ...
    'No graph-eligible candidates are available for blinded review.');

Selection = table();
CandidateSummary = table();
for iCandidate = 1:height(CandidateTable)
    candidateId = string(CandidateTable.motif_candidate_id(iCandidate));
    nodes = NodeTable(string(NodeTable.motif_candidate_id) == candidateId, :);
    nodes = sortrows(nodes, 'graph_node_id');
    assert(height(nodes) == CandidateTable.node_count(iCandidate), ...
        'select_blinded_motif_candidate_video_examples:CandidateSizeMismatch', ...
        'Candidate %s node count differs from the topology audit.', candidateId);

    candidateExemplars = Exemplars( ...
        string(Exemplars.motif_candidate_id) == candidateId, :);
    candidateExemplars = sortrows(candidateExemplars, 'exemplar_rank');
    [present, exemplarLoc] = ismember( ...
        candidateExemplars.graph_node_id, nodes.graph_node_id);
    assert(all(present), ...
        'select_blinded_motif_candidate_video_examples:MissingExemplar', ...
        'Candidate %s has an exemplar outside frozen membership.', candidateId);

    usedNodeIds = zeros(0, 1);
    usedSessions = zeros(0, 1);
    centralOrder = exemplarLoc(:);
    [centralIdx, usedSessions] = i_take_session_diverse( ...
        nodes, centralOrder, params.central_tiles, usedSessions, ...
        params.maximum_examples_per_session);
    usedNodeIds = [usedNodeIds; nodes.graph_node_id(centralIdx)]; %#ok<AGROW>

    coreMask = ~logical(nodes.is_boundary_ambiguous) & ...
        nodes.coassignment_jaccard_mean >= ...
        params.core_minimum_node_stability & ...
        ~ismember(nodes.graph_node_id, usedNodeIds);
    corePool = find(coreMask);
    coreKeys = i_random_keys(numel(corePool), params, ...
        CandidateTable.candidate_local_index(iCandidate), 1);
    [~, coreOrder] = sort(coreKeys);
    coreOrder = corePool(coreOrder);
    [coreIdx, usedSessions] = i_take_session_diverse( ...
        nodes, coreOrder, params.core_random_tiles, usedSessions, ...
        params.maximum_examples_per_session);
    usedNodeIds = [usedNodeIds; nodes.graph_node_id(coreIdx)]; %#ok<AGROW>

    boundaryMask = logical(nodes.is_boundary_ambiguous) & ...
        ~ismember(nodes.graph_node_id, usedNodeIds);
    boundaryPool = find(boundaryMask);
    boundaryKeys = i_random_keys(numel(boundaryPool), params, ...
        CandidateTable.candidate_local_index(iCandidate), 2);
    [~, boundaryOrder] = sort(boundaryKeys);
    boundaryOrder = boundaryPool(boundaryOrder);
    [boundaryIdx, ~] = i_take_session_diverse( ...
        nodes, boundaryOrder, params.boundary_random_tiles, usedSessions, ...
        params.maximum_examples_per_session);

    selectedIdx = [centralIdx; coreIdx; boundaryIdx];
    selectedStratum = [ ...
        repmat("central_graph_exemplar", params.central_tiles, 1)
        repmat("high_confidence_core_random", ...
            params.core_random_tiles, 1)
        repmat("boundary_random", params.boundary_random_tiles, 1)];
    stratumRank = [ ...
        (1:params.central_tiles)'
        (1:params.core_random_tiles)'
        (1:params.boundary_random_tiles)'];
    sourceExemplarRank = nan(params.tiles_per_candidate, 1);
    for iCentral = 1:numel(centralIdx)
        row = candidateExemplars.graph_node_id == ...
            nodes.graph_node_id(centralIdx(iCentral));
        sourceExemplarRank(iCentral) = ...
            candidateExemplars.exemplar_rank(find(row, 1));
    end
    deterministicKey = nan(params.tiles_per_candidate, 1);
    deterministicKey(params.central_tiles + (1:params.core_random_tiles)) = ...
        i_key_for_selected(nodes, corePool, coreKeys, coreIdx);
    boundaryStart = params.central_tiles + params.core_random_tiles;
    deterministicKey(boundaryStart + (1:params.boundary_random_tiles)) = ...
        i_key_for_selected(nodes, boundaryPool, boundaryKeys, boundaryIdx);

    medianChunkSec = median(nodes.chunk_sec, 'omitnan');
    clipHalfWindowSec = min(params.maximum_clip_half_window_sec, ...
        max(params.minimum_clip_half_window_sec, ...
        0.5 * medianChunkSec + params.clip_context_padding_sec));
    displayStream = RandStream(char(params.random_stream_algorithm), ...
        'Seed', params.random_seed + ...
        100 * CandidateTable.candidate_local_index(iCandidate) + 3);
    displayTileIndex = randperm(displayStream, ...
        params.tiles_per_candidate)';
    displayTileLabels = string(cellstr( ...
        char('A' + (0:params.tiles_per_candidate - 1))'));
    displayTileLabel = displayTileLabels(displayTileIndex);
    selected = nodes(selectedIdx, {'graph_node_id', 'embedding_row_id', ...
        'scale_index', 'chunk_sec', 'session_index', 'session_id', ...
        'raw_index', 'anchor_frame', 'anchor_time_s', ...
        'coassignment_jaccard_mean', 'is_boundary_ambiguous'});
    selected.Properties.VariableNames{ ...
        strcmp(selected.Properties.VariableNames, ...
        'coassignment_jaccard_mean')} = 'node_stability';
    selected.motif_candidate_id = repmat(candidateId, ...
        params.tiles_per_candidate, 1);
    selected.candidate_local_index = repmat( ...
        CandidateTable.candidate_local_index(iCandidate), ...
        params.tiles_per_candidate, 1);
    selected.selection_index = (1:params.tiles_per_candidate)';
    selected.display_tile_index = displayTileIndex;
    selected.display_tile_label = displayTileLabel;
    selected.selection_stratum = selectedStratum;
    selected.selection_rank_within_stratum = stratumRank;
    selected.source_run09_exemplar_rank = sourceExemplarRank;
    selected.deterministic_random_key = deterministicKey;
    selected.candidate_median_chunk_sec = repmat( ...
        medianChunkSec, params.tiles_per_candidate, 1);
    selected.clip_half_window_sec = repmat( ...
        clipHalfWindowSec, params.tiles_per_candidate, 1);
    selected.selected_after_candidate_freeze = true( ...
        params.tiles_per_candidate, 1);
    selected.used_for_membership = false(params.tiles_per_candidate, 1);
    selected.used_for_interpretation_eligibility = false( ...
        params.tiles_per_candidate, 1);
    selected.session_used_for_visual_diversity_only = true( ...
        params.tiles_per_candidate, 1);
    selected.visual_appearance_used_for_selection = false( ...
        params.tiles_per_candidate, 1);
    selected.frozen_membership_sha256 = repmat( ...
        membershipHash, params.tiles_per_candidate, 1);
    selected.candidate_freeze_id = repmat( ...
        params.expected_candidate_freeze_id, ...
        params.tiles_per_candidate, 1);
    selected.experimental_labels_used = repmat( ...
        "none", params.tiles_per_candidate, 1);
    selected = movevars(selected, {'motif_candidate_id', ...
        'candidate_local_index', 'display_tile_index', ...
        'display_tile_label', 'selection_index', ...
        'selection_stratum', 'selection_rank_within_stratum'}, ...
        'Before', 1);
    Selection = [Selection; selected]; %#ok<AGROW>

    summaryRow = table(candidateId, ...
        CandidateTable.candidate_local_index(iCandidate), height(nodes), ...
        nnz(coreMask), nnz(boundaryMask), ...
        numel(unique(selected.session_index)), medianChunkSec, ...
        clipHalfWindowSec, params.tiles_per_candidate, ...
        params.central_tiles, params.core_random_tiles, ...
        params.boundary_random_tiles, ...
        string(CandidateTable.interpretation_status(iCandidate)), ...
        membershipHash, params.expected_candidate_freeze_id, "none", ...
        'VariableNames', {'motif_candidate_id', ...
        'candidate_local_index', 'candidate_node_count', ...
        'available_core_node_count', 'available_boundary_node_count', ...
        'selected_session_count', 'candidate_median_chunk_sec', ...
        'clip_half_window_sec', 'selected_example_count', ...
        'central_example_count', 'core_random_example_count', ...
        'boundary_random_example_count', ...
        'graph_only_interpretation_status', ...
        'frozen_membership_sha256', 'candidate_freeze_id', ...
        'experimental_labels_used'});
    CandidateSummary = [CandidateSummary; summaryRow]; %#ok<AGROW>
end

assert(height(Selection) == ...
    height(CandidateTable) * params.tiles_per_candidate && ...
    numel(unique(Selection.graph_node_id)) == height(Selection), ...
    'select_blinded_motif_candidate_video_examples:BadSelectionSize', ...
    'Every candidate requires nine globally unique selected graph nodes.');
Selection = i_attach_preprocessing_provenance( ...
    Selection, repoRoot, params);
end

function [selectedIdx, usedSessions] = i_take_session_diverse( ...
        nodes, orderedIdx, count, usedSessions, maximumPerSession)
selectedIdx = zeros(0, 1);
for i = 1:numel(orderedIdx)
    idx = orderedIdx(i);
    sessionId = nodes.session_index(idx);
    if nnz(usedSessions == sessionId) < maximumPerSession
        selectedIdx(end + 1, 1) = idx; %#ok<AGROW>
        usedSessions(end + 1, 1) = sessionId; %#ok<AGROW>
        if numel(selectedIdx) == count
            break
        end
    end
end
assert(numel(selectedIdx) == count, ...
    'select_blinded_motif_candidate_video_examples:InsufficientDiversity', ...
    ['The configured stratum lacks enough nodes after applying the ' ...
     'post-fit session-diversity constraint.']);
end

function keys = i_random_keys(n, params, candidateIndex, stratumIndex)
seed = params.random_seed + 100 * candidateIndex + stratumIndex;
stream = RandStream(char(params.random_stream_algorithm), 'Seed', seed);
keys = rand(stream, n, 1);
end

function keys = i_key_for_selected(nodes, pool, poolKeys, selectedIdx)
[present, loc] = ismember(nodes.graph_node_id(selectedIdx), ...
    nodes.graph_node_id(pool));
assert(all(present), ...
    'select_blinded_motif_candidate_video_examples:MissingRandomKey', ...
    'Selected random examples must retain deterministic priority keys.');
keys = poolKeys(loc);
end

function Selection = i_attach_preprocessing_provenance( ...
        Selection, repoRoot, params)
Qc = i_read_columns(resolve_repo_path(repoRoot, params.preprocess_qc_file), ...
    ["raw_index", "session_id", "n_frames", "preprocess_output_file", ...
     "preprocess_success"]);
assert(numel(unique(Qc.raw_index)) == height(Qc), ...
    'select_blinded_motif_candidate_video_examples:DuplicateQcRow', ...
    'Preprocessing QC must contain one row per raw_index.');
[present, loc] = ismember(Selection.raw_index, Qc.raw_index);
assert(all(present), ...
    'select_blinded_motif_candidate_video_examples:MissingQcRow', ...
    'A selected example lacks preprocessing provenance.');
assert(all(logical(Qc.preprocess_success(loc))), ...
    'select_blinded_motif_candidate_video_examples:PreprocessFailure', ...
    'Every selected example requires a successful preprocessing output.');
assert(all(string(Selection.session_id) == string(Qc.session_id(loc))), ...
    'select_blinded_motif_candidate_video_examples:SessionMismatch', ...
    'Node and preprocessing session provenance differ.');
Selection.preprocess_output_file = string(Qc.preprocess_output_file(loc));
Selection.source_frame_count = double(Qc.n_frames(loc));
assert(all(isfinite(Selection.anchor_frame)) && ...
    all(Selection.anchor_frame >= 1) && ...
    all(Selection.anchor_frame <= Selection.source_frame_count), ...
    'select_blinded_motif_candidate_video_examples:AnchorOutOfBounds', ...
    'Every selected anchor must lie within its preprocessed pose file.');
for i = 1:height(Selection)
    pathText = resolve_repo_path(repoRoot, ...
        Selection.preprocess_output_file(i));
    assert(isfile(pathText), ...
        'select_blinded_motif_candidate_video_examples:MissingPoseFile', ...
        'Selected preprocessed pose file is missing: %s', pathText);
end
end

function T = i_read_columns(pathText, columnNames)
opts = detectImportOptions(pathText, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
missing = setdiff(columnNames, string(opts.VariableNames));
assert(isempty(missing), ...
    'select_blinded_motif_candidate_video_examples:MissingColumn', ...
    'Input %s is missing columns: %s', pathText, strjoin(missing, ', '));
opts.SelectedVariableNames = cellstr(columnNames);
T = readtable(pathText, opts);
end
