function Validation = validate_run10_candidate_freeze(repoRoot, params, outputPath)
%VALIDATE_RUN10_CANDIDATE_FREEZE Fail-closed run_09 identity gate.
%
% This function reads only run_09 freeze and topology artifacts. It must
% complete before run_10 reads pose, video, ratings, provisional annotation,
% or any proposed validation-feature value.

repoRoot = string(repoRoot);
run09Root = string(resolve_repo_path(repoRoot, params.run09_output_dir));
paths = struct();
paths.membership = fullfile(run09Root, params.membership_file);
paths.definition = fullfile(run09Root, params.candidate_definition_file);
paths.hierarchy = fullfile(run09Root, params.candidate_hierarchy_file);
paths.topology = fullfile(run09Root, params.candidate_topology_file);
paths.ambiguity = fullfile(run09Root, params.candidate_ambiguity_file);
paths.manifest = fullfile(run09Root, params.run09_manifest_file);
paths.run09FreezeValidation = fullfile(run09Root, ...
    params.run09_freeze_validation_file);

checkId = strings(0, 1);
stage = strings(0, 1);
expected = strings(0, 1);
observed = strings(0, 1);
passed = false(0, 1);
details = strings(0, 1);

pathNames = string(fieldnames(paths));
for i = 1:numel(pathNames)
    p = paths.(pathNames(i));
    add("file_exists_" + pathNames(i), "identity", "true", ...
        string(isfile(p)), isfile(p), p);
end
Gate = table(checkId, stage, expected, observed, passed, details, ...
    'VariableNames', {'check_id','stage','expected_value', ...
    'observed_value','pass','details'});
if ~all(passed)
    if nargin >= 3 && strlength(string(outputPath)) > 0
        write_table_atomic(Gate, outputPath);
    end
    error('validate_run10_candidate_freeze:MissingFrozenInput', ...
        'A required frozen run_09 input is missing.');
end

[membershipHash, membershipBytes] = compute_file_sha256(paths.membership);
add("membership_sha256", "identity", ...
    params.expected_membership_sha256, membershipHash, ...
    membershipHash == params.expected_membership_sha256, ...
    "Exact file bytes; bytes=" + string(membershipBytes));

Manifest = i_read(paths.manifest);
requiredManifestColumns = ["record_type","artifact_id","artifact_path", ...
    "artifact_role","status","row_count","file_bytes","sha256", ...
    "candidate_freeze_id","no_experimental_labels_used"];
manifestColumnsOk = isempty(setdiff(requiredManifestColumns, ...
    string(Manifest.Properties.VariableNames)));
add("manifest_required_columns", "identity", ...
    strjoin(requiredManifestColumns, ";"), ...
    strjoin(string(Manifest.Properties.VariableNames), ";"), ...
    manifestColumnsOk, "Run_09 manifest schema required by run_10.");

freezeIds = unique(string(Manifest.candidate_freeze_id));
freezeIds = freezeIds(~ismissing(freezeIds) & freezeIds ~= "");
add("manifest_candidate_freeze_id", "identity", ...
    params.expected_candidate_freeze_id, strjoin(freezeIds, ";"), ...
    numel(freezeIds) == 1 && ...
    freezeIds == params.expected_candidate_freeze_id, ...
    "Every manifested run_09 artifact is bound to one candidate freeze.");

requiredIds = [params.membership_file; params.candidate_definition_file; ...
    params.candidate_hierarchy_file; params.candidate_topology_file; ...
    params.candidate_ambiguity_file];
requiredPaths = [paths.membership; paths.definition; paths.hierarchy; ...
    paths.topology; paths.ambiguity];
requiredRoles = [ ...
    "defines_frozen_candidate_membership"
    "defines_frozen_candidate_ids"
    "defines_frozen_candidate_hierarchy"
    "postfreeze_graph_topology_and_interpretation_eligibility_audit"
    "retained_node_ambiguity_audit"];
for i = 1:numel(requiredIds)
    row = Manifest.artifact_id == requiredIds(i) & ...
        Manifest.record_type == "output_artifact";
    add("manifest_unique_" + erase(requiredIds(i), ".csv"), ...
        "identity", "one row", string(nnz(row)), nnz(row) == 1, ...
        "Required frozen or graph-only run_09 artifact.");
    if nnz(row) == 1
        [actualHash, actualBytes] = compute_file_sha256(requiredPaths(i));
        add("manifest_hash_" + erase(requiredIds(i), ".csv"), ...
            "identity", string(Manifest.sha256(row)), actualHash, ...
            actualHash == string(Manifest.sha256(row)), ...
            "Independent byte-exact re-hash.");
        add("manifest_bytes_" + erase(requiredIds(i), ".csv"), ...
            "identity", string(Manifest.file_bytes(row)), ...
            string(actualBytes), actualBytes == Manifest.file_bytes(row), ...
            "Independent file-size check.");
        add("manifest_role_" + erase(requiredIds(i), ".csv"), ...
            "identity", requiredRoles(i), ...
            string(Manifest.artifact_role(row)), ...
            string(Manifest.artifact_role(row)) == requiredRoles(i), ...
            "Frozen artifact role cannot be reinterpreted by run_10.");
    end
end

membershipManifest = Manifest.artifact_id == params.membership_file & ...
    Manifest.record_type == "output_artifact";
if nnz(membershipManifest) == 1
    add("membership_manifest_hash_matches_pin", "identity", ...
        params.expected_membership_sha256, ...
        string(Manifest.sha256(membershipManifest)), ...
        string(Manifest.sha256(membershipManifest)) == ...
        params.expected_membership_sha256, ...
        "Manifest and explicit run_10 pin must agree.");
end
freezeContract = Manifest.record_type == "run_contract" & ...
    Manifest.artifact_id == "candidate_membership_freeze_hash";
add("membership_freeze_contract", "identity", ...
    params.expected_membership_sha256, ...
    i_single_detail(Manifest, freezeContract), ...
    nnz(freezeContract) == 1 && ...
    i_single_detail(Manifest, freezeContract) == ...
    params.expected_membership_sha256, ...
    "Run_09 reviewer contract membership hash.");

Membership = i_read_selected(paths.membership, ...
    ["graph_node_id","resolution_id","motif_candidate_id", ...
    "membership_status"]);
Definition = i_read(paths.definition);
Hierarchy = i_read(paths.hierarchy);
Topology = i_read(paths.topology);
Ambiguity = i_read_selected(paths.ambiguity, ...
    ["graph_node_id","motif_candidate_id","membership_status"]);

add("membership_row_count", "structural", ...
    string(params.expected_node_count), string(height(Membership)), ...
    height(Membership) == params.expected_node_count, ...
    "Every frozen graph node must be retained.");
add("membership_unique_graph_node", "structural", ...
    string(params.expected_node_count), ...
    string(numel(unique(Membership.graph_node_id))), ...
    numel(unique(Membership.graph_node_id)) == height(Membership), ...
    "Exactly one assignment per graph node.");
add("membership_one_resolution", "structural", "CPM_M000750", ...
    strjoin(unique(string(Membership.resolution_id)), ";"), ...
    numel(unique(string(Membership.resolution_id))) == 1 && ...
    unique(string(Membership.resolution_id)) == "CPM_M000750", ...
    "No alternate run_09 resolution may enter run_10.");

candidateIds = sort(unique(string(Definition.motif_candidate_id)));
membershipIds = sort(unique(string(Membership.motif_candidate_id)));
topologyIds = sort(unique(string(Topology.motif_candidate_id)));
hierarchyIds = sort(unique(string(Hierarchy.child_motif_candidate_id)));
add("candidate_count", "structural", ...
    string(params.expected_candidate_count), string(numel(candidateIds)), ...
    numel(candidateIds) == params.expected_candidate_count, ...
    "Exact frozen candidate count.");
add("candidate_set_membership_definition", "structural", ...
    strjoin(candidateIds, ";"), strjoin(membershipIds, ";"), ...
    isequal(candidateIds, membershipIds), ...
    "Membership candidate IDs equal frozen definitions.");
add("candidate_set_definition_topology", "structural", ...
    strjoin(candidateIds, ";"), strjoin(topologyIds, ";"), ...
    isequal(candidateIds, topologyIds), ...
    "Topology candidate IDs equal frozen definitions.");
add("candidate_set_definition_hierarchy", "structural", ...
    strjoin(candidateIds, ";"), strjoin(hierarchyIds, ";"), ...
    isequal(candidateIds, hierarchyIds), ...
    "Hierarchy child IDs equal frozen definitions.");

parent = string(Hierarchy.hierarchy_parent_candidate_id);
hasParent = ~ismissing(parent) & strlength(strtrim(parent)) > 0;
add("flat_hierarchy_root_count", "structural", ...
    string(params.expected_hierarchy_root_count), ...
    string(nnz(~hasParent)), height(Hierarchy) == ...
    params.expected_hierarchy_root_count && ~any(hasParent), ...
    "Run_10 cannot manufacture parent links.");

[tfAmb, locAmb] = ismember(Membership.graph_node_id, ...
    Ambiguity.graph_node_id);
ambiguityCandidate = strings(height(Membership), 1);
ambiguityCandidate(tfAmb) = string( ...
    Ambiguity.motif_candidate_id(locAmb(tfAmb)));
ambiguityOk = all(tfAmb) && all(ambiguityCandidate == ...
    string(Membership.motif_candidate_id));
add("ambiguity_membership_alignment", "structural", ...
    "all nodes and assignments match", ...
    "matched=" + string(nnz(tfAmb)) + ...
    ";candidate_mismatches=" + string(nnz(tfAmb & ...
    ambiguityCandidate ~= string(Membership.motif_candidate_id))), ...
    ambiguityOk, "Ambiguity metadata cannot reassign a node.");

eligible = sort(string(Topology.motif_candidate_id( ...
    logical(Topology.eligible_for_behavioral_interpretation))));
expectedEligible = sort(params.expected_eligible_candidate_ids(:));
add("graph_only_eligible_candidate_set", "structural", ...
    strjoin(expectedEligible, ";"), strjoin(eligible, ";"), ...
    isequal(expectedEligible, eligible), ...
    "Run_10 validation status is distinct from this frozen set.");
add("postfreeze_merge_prohibited", "structural", "all false", ...
    string(nnz(logical(Topology.postfreeze_merge_allowed))), ...
    ~any(logical(Topology.postfreeze_merge_allowed)), ...
    "Run_10 cannot merge candidates.");
add("postfreeze_split_prohibited", "structural", "all false", ...
    string(nnz(logical(Topology.postfreeze_split_allowed))), ...
    ~any(logical(Topology.postfreeze_split_allowed)), ...
    "Run_10 cannot split candidates.");
add("candidate_ids_retained", "structural", "all true", ...
    string(nnz(logical(Topology.candidate_id_retained))), ...
    all(logical(Topology.candidate_id_retained)), ...
    "All 42 candidate IDs remain frozen.");

Run09Gate = i_read(paths.run09FreezeValidation);
run09Pass = i_to_logical(Run09Gate.pass);
add("run09_input_freeze_validation_passed", "provenance", ...
    "all true", string(nnz(run09Pass)) + "/" + ...
    string(height(Run09Gate)), all(run09Pass), ...
    "Run_09's recorded run_08 freeze checks remain part of provenance.");
add("no_experimental_labels_in_manifest", "firewall", "all true", ...
    string(nnz(i_to_logical(Manifest.no_experimental_labels_used))) + ...
    "/" + string(height(Manifest)), ...
    all(i_to_logical(Manifest.no_experimental_labels_used)), ...
    "Run_09 freeze was generated condition-blind.");

Gate = table(checkId, stage, expected, observed, passed, details, ...
    'VariableNames', {'check_id','stage','expected_value', ...
    'observed_value','pass','details'});
if nargin >= 3 && strlength(string(outputPath)) > 0
    write_table_atomic(Gate, outputPath);
end
assert(all(Gate.pass), ...
    'validate_run10_candidate_freeze:FreezeMismatch', ...
    ['Run_10 candidate freeze validation failed. No pose, video, ' ...
     'validation-feature, annotation, or rating input may be read.']);

Validation = struct();
Validation.gate = Gate;
Validation.paths = paths;
Validation.membership_sha256 = membershipHash;
Validation.candidate_freeze_id = params.expected_candidate_freeze_id;
Validation.membership = Membership;
Validation.definition = Definition;
Validation.hierarchy = Hierarchy;
Validation.topology = Topology;
Validation.candidate_ids = candidateIds;
Validation.eligible_candidate_ids = eligible;

    function add(id, stageValue, expectedValue, observedValue, passValue, detail)
        checkId(end + 1, 1) = string(id);
        stage(end + 1, 1) = string(stageValue);
        expected(end + 1, 1) = string(expectedValue);
        observed(end + 1, 1) = string(observedValue);
        passed(end + 1, 1) = logical(passValue);
        details(end + 1, 1) = string(detail);
    end
end

function T = i_read(pathText)
T = readtable(pathText, 'Delimiter', ',', 'TextType', 'string');
end

function T = i_read_selected(pathText, names)
opts = detectImportOptions(pathText, 'FileType', 'text', ...
    'Delimiter', ',', 'TextType', 'string');
missing = setdiff(names, string(opts.VariableNames));
assert(isempty(missing), ...
    'validate_run10_candidate_freeze:MissingColumn', ...
    'Input %s lacks columns: %s', pathText, strjoin(missing, ', '));
opts.SelectedVariableNames = cellstr(names);
T = readtable(pathText, opts);
end

function value = i_single_detail(T, mask)
if nnz(mask) == 1
    value = string(T.details(mask));
else
    value = "";
end
end

function out = i_to_logical(x)
if islogical(x)
    out = x;
elseif isnumeric(x)
    out = x ~= 0;
else
    out = ismember(lower(string(x)), ["1","true","yes"]);
end
end
